INSERT INTO TABLE au.gas_sw1_50 
SELECT  cod_servizio      ,
        cod_flusso        ,
        dataElaborazione  ,
        pivaUtente        ,
        piva_distr        ,
        cod_prat_utente   ,
        cod_prat_distr    ,
        cod_pdr           ,
        matr_mis          ,
        data_deco_switch  ,
        vol_annuo_sost    ,
        classe_gruppo_mis ,
        n_cifre_mis       ,
        segn_mis_sost     ,
        tipo_lettura      ,
        pre_conv          ,
        gruppo_mis_int    ,
        coeff_corr        ,
        data_mis_eff      ,
        segn_mis_eff      ,
        matr_conv         ,
        n_cifre_conv      ,
        segn_conv         ,
        segn_conv_eff     ,
        note                    
from au_test.gas_sw1_50