agg.db = agg
sbg.db = sbg
cdp.db = cdp
ccg.db = ccg
rcugas.db=rcugas

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo/AGG_TMP
isilon.basepath.out=/mnt/Settlement

table.path.hdfs = /user/hive/warehouse/ccg.db

deploy.path = /home/sii_misure_gas/CCG/pubblicazione
deploy.path.hdfs = /apps/CCG/pubblicazione

hadoop.username = sii_misure_gas
sqoop.config.path = /apps/deploy/job.properties