hdfs.output.basepath.csv=/user/hive/warehouse/cdp.db/cdp_dati_prelievo_gas
hdfs.output.basepath.csv.export=/user/hive/warehouse/cdp.db/cdp_dati_prelievo_gas_export
hdfs.output.basepath.infoLog=/user/hive/warehouse/cdp.db/aggregatore_info_log_cdp

cdp.db = cdp
rcugas.db = rcugas
rcugasMassivo.db = cdp
rcu.db = rcu
hive.db = cdp
isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/Settlement

sqoop.config.path=/apps/deploy/job.properties
params.config.path=/apps/CDP/deploy_aggregazione/params.properties
hadoop_username=sii_misure_gas
sqoop.null.character=\\\\N

spark.app.url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = scancl01-01.siiau.local)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = SIIP)))

isilon.deploy.path=/home/sii_misure_gas/CDP/aggregatore
hdfs.deploy.path=/apps/CDP/deploy_aggregazione