agg.db = eng_test
agg.output.rootpath = /user/eng_test/sbg
deploy.path = /user/eng_test/sbg/deploy
deploy.path.hdfs = /user/eng_test/sbg/deploy
deploy.path.strong.exclusion = /user/eng_test/sbg/deploy
deploy.path.strong.forceExclusion=/user/eng_test/sbg/deploy/force_exclusion
strong.exclusion.backuptable.basepath = /user/hive/warehouse/eng_test.db/strong_exclusion_backuptable_agg