agg.db=sbg
rcugas.db=rcugas

dailyConsumption.tableName=daily_consumption_sbg
validateFlows.tableName=validated_flows_sbg
rcugas.sospensioni.tableName=rcugas_sospensioni_p
rcugas.pdr.tableName=rcugas_pdr_p

hdfs.basePath=/user/hive/warehouse/au.db/misure_gas_au/sbg/queries

deploy.path=/home/sii_misure_gas/SBG/deploy/deploy_reportistica
hdfs.config.path=/apps/SBG/deploy/deploy_reportistica
aggregazione.sbg.hdfs.path=/apps/SBG/deploy/deploy_aggregazione