agg.db=sbg
rcugas.db=rcugas
dailyConsumption.tableName=daily_consumption_sbg

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo/SBG_TMP
isilon.basepath.out=/mnt/Settlement
hdfs.tmp.basepath=/apps/SBG/tmp
hdfs.output.basepath=/user/hive/warehouse/au.db/misure_gas_au/sbg/aggregatore_info_log
#the previous has to be checked

pdrAnomali.listaC.csvPath=/apps/SBG/deploy/csv_pdr_anomali/PDR_ANOMALI_LISTA_C.csv
pdrAnomali.listaD.csvPath=/apps/SBG/deploy/csv_pdr_anomali/PDR_ANOMALI_LISTA_D.csv

deploy.path = /home/sii_misure_gas/SBG/deploy/deploy_aggregazione
hdfs.path = /apps/SBG/deploy/deploy_aggregazione