agg.db = eng_test
agg.output.rootpath = /user/eng_test/sbg
deploy.path = /home/eng_test/sbg/deploy
deploy.path.hdfs = /user/eng_test/sbg/deploy
deploy.path.strong.exclusion = /user/eng_test/agg/deploy
strong.exclusion.backuptable.basepath = /user/eng_test/agg/deploy/backup_strong_exclusion_filter