agg.db = sbg
agg.output.rootpath = /user/hive/warehouse/au.db/misure_gas_au/sbg
deploy.path = /home/sii_misure_gas/SBG/deploy
deploy.path.hdfs = /apps/SBG/deploy
deploy.path.strong.exclusion = /apps/esclusione_definitiva
deploy.path.strong.forceExclusion = /apps/esclusione_definitiva/force_exclusion
strong.exclusion.backuptable.basepath = /user/hive/warehouse/au.db/misure_gas_au/sbg/strong_exclusion_backuptable_sbg