--Tabella di consultazione
  CREATE TABLE "TMPOD_CLOUD"."PRT_TMO_AGGREGATI_CALCOLATI" 
   (	"N_ID" NUMBER NOT NULL ENABLE, 
	"N_ID_DISTR" VARCHAR2(20 BYTE), 
	"T_AREA_RIF" VARCHAR2(20 BYTE), 
	"ANNOMESE" NUMBER, 
	"N_ID_UDD" VARCHAR2(20 BYTE), 
	"GIORNO" NUMBER, 
	"N_H1" NUMBER(10,2), 
	"N_H2" NUMBER(10,2), 
	"N_H3" NUMBER(10,2), 
	"N_H4" NUMBER(10,2), 
	"N_H5" NUMBER(10,2), 
	"N_H6" NUMBER(10,2), 
	"N_H7" NUMBER(10,2), 
	"N_H8" NUMBER(10,2), 
	"N_H9" NUMBER(10,2), 
	"N_H10" NUMBER(10,2), 
	"N_H11" NUMBER(10,2), 
	"N_H12" NUMBER(10,2), 
	"N_H13" NUMBER(10,2), 
	"N_H14" NUMBER(10,2), 
	"N_H15" NUMBER(10,2), 
	"N_H16" NUMBER(10,2), 
	"N_H17" NUMBER(10,2), 
	"N_H18" NUMBER(10,2), 
	"N_H19" NUMBER(10,2), 
	"N_H20" NUMBER(10,2), 
	"N_H21" NUMBER(10,2), 
	"N_H22" NUMBER(10,2), 
	"N_H23" NUMBER(10,2), 
	"N_H24" NUMBER(10,2), 
	"N_H25" NUMBER(10,2), 
	"D_DATA_AGGREGAZIONE" TIMESTAMP (6), 
	"T_AGGR_SOTTESI" VARCHAR2(20 BYTE), 
	"N_ID_DISTR_RIF" VARCHAR2(20 BYTE), 
	"UID_ELAB" NUMBER, 
	"UID_ELAB_ORARIE" NUMBER, 
	 CONSTRAINT "PRT_TMO_AGGREGATI_CALCOLATI_PK" PRIMARY KEY ("N_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "AREATECNICA_DATA" ;

  CREATE OR REPLACE TRIGGER "TMPOD_CLOUD"."PRT_TMO_AGGR_CALC_ON_INSERT" 
  BEFORE INSERT ON PRT_TMO_AGGREGATI_CALCOLATI
  FOR EACH ROW
BEGIN
  SELECT PRT_TMO_AGGR_CALC_SEQ.nextval
  INTO :new.N_ID
  FROM dual;
END;
/
ALTER TRIGGER "TMPOD_CLOUD"."PRT_TMO_AGGR_CALC_ON_INSERT" ENABLE;


--VISTE

  CREATE OR REPLACE FORCE VIEW "TMPOD_CLOUD"."DISTR_AZ" ("N_ID_DISTR", "N_ID_DISTR_RIF", "T_TIPO", "T_PIVA") AS 
  SELECT DISTR.N_ID_DISTR, DISTR.N_ID_DISTR_RIF, DISTR.T_TIPO, AZ.T_PIVA 
	FROM RCU.RCU_DISTR DISTR
	JOIN RCU.RCU_AZIENDA AZ ON DISTR.N_ID_DISTR = AZ.N_ID_AZIENDA;


  CREATE OR REPLACE FORCE VIEW "TMPOD_CLOUD"."IS_T_TRATTAMENTO_STATO_POD" ("T_CODICE_POD", "STATO_POD", "IS_T_TRATTAMENTO") AS 
  SELECT  substr(p.T_CODICE_POD,1,14) T_CODICE_POD,tmp.STATO_POD,  CASE   WHEN EXISTS ( SELECT 'Y'  FROM RCU.RCU_POD_MISURE a  where a.n_id_pod = b.n_id_pod AND a.T_TRATTAMENTO = 'O' and  TO_DATE('201807'||01,'yyyymmdd') >= a.D_ANNO_MESE and D_ANNO_MESE = ( SELECT max(D_ANNO_MESE)  FROM RCU.rcu_pod_misure x where x.n_id_pod = b.n_id_pod and TO_DATE('201807'||01,'YYYYMMDD') >= x.D_ANNO_MESE))  THEN 'Y'  WHEN EXISTS ( SELECT 'Y'  FROM RCU.RCU_POD_MISURE a  where a.n_id_pod = b.n_id_pod AND a.T_TRATTAMENTO != 'O' and  TO_DATE('201807'||01,'yyyymmdd') >= a.D_ANNO_MESE and D_ANNO_MESE = ( SELECT max(D_ANNO_MESE)  FROM RCU.rcu_pod_misure x where x.n_id_pod = b.n_id_pod and TO_DATE('201807'||01,'YYYYMMDD') >= x.D_ANNO_MESE))  THEN 'N'  WHEN MISUS.IS_T_TRATTAMENTO = 'Y' THEN 'Y'  ELSE 'N' END AS IS_T_TRATTAMENTO  FROM RCU.RCU_POD_MISURE b  JOIN RCU.RCU_POD p ON p.n_id_pod=b.n_id_pod  JOIN (  SELECT b.n_id_pod,  CASE WHEN EXISTS (  SELECT a.n_id_pod FROM RCU.RCU_POD_STATO a  WHERE a.n_id_pod = b.n_id_pod  AND '201807' between TO_CHAR(NVL(a.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(a.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM')  and a.D_AGGIORNAMENTO = (SELECT max(z.d_aggiornamento) from RCU.RCU_POD_STATO z where z.n_id_pod = a.n_id_pod  and '201807' between TO_CHAR(NVL(z.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(z.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM'))  ) THEN 'Y'  WHEN EXISTS (  SELECT 'Y'  FROM RCUS.RCUS_PODSTATO r  WHERE r.n_id_pod = b.n_id_pod  and '201807'  between TO_CHAR(NVL(r.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(r.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM') and r.b_valido='Y'  and r.D_AGGIORNAMENTO = (SELECT max(z.d_aggiornamento) from RCUS.RCUS_PODSTATO z where z.n_id_pod = r.n_id_pod  and '201807'  between TO_CHAR(NVL(r.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(r.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM') and z.b_valido='Y') ) THEN 'Y'  ELSE 'N' END AS STATO_POD  FROM RCU.RCU_POD_STATO b ) tmp on tmp.n_id_pod=p.n_id_pod LEFT JOIN (select case when TRATTAMENTO = 'O' THEN 'Y' ELSE 'N' END IS_T_TRATTAMENTO, N_ID_POD from ( select CASE WHEN D_ANNO_MESE < TRUNC(TO_DATE('201807'||01,'yyyymmdd'),'MM') THEN T_TRATTAMENTO_SUCC ELSE T_TRATTAMENTO END TRATTAMENTO, n_id_pod, RANG, POD14 from ( SELECT n_id_pod, RANK() OVER (PARTITION BY n_id_pod ORDER BY d_anno_mese desc, d_aggiornamento desc) rang, t_trattamento, t_trattamento_succ, D_ANNO_MESE, POD14 from ( SELECT Y.n_id_pod, t_trattamento, t_trattamento_succ, D_ANNO_MESE, X.d_aggiornamento, SUBSTR(Y.T_CODICE_POD,1,14) POD14 FROM RCUS.rcus_podmisure x, RCU.RCU_POD Y where x.D_ANNO_MESE <=  TO_DATE('201807'||01,'YYYYMMDD') AND X.N_ID_POD = Y.N_ID_POD AND SUBSTR(Y.T_CODICE_POD,1,14)=SUBSTR(Y.T_CODICE_POD,1,14) ) ) where rang = 1 ) ) MISUS ON p.N_ID_POD = MISUS.N_ID_POD;

  
  
  CREATE OR REPLACE FORCE VIEW "TMPOD_CLOUD"."POD_POD_UDD" ("T_PIVA", "POD_14", "T_AREA_RIF", "D_INIZIO", "D_FINE", "N_ID_UDD") AS 
  SELECT /*+ parallel (4) */ a.T_PIVA,
substr(p.T_CODICE_POD,1,14) POD_14,p.T_AREA_RIF,u.D_INIZIO,u.D_FINE , 
CAST(u.N_ID_UDD AS VARCHAR2(50)) AS N_ID_UDD
  FROM RCU.RCU_POD p 
  JOIN RCU.RCU_POD_UDD u ON p.N_ID_POD=u.N_ID_POD
  JOIN RCU.RCU_AZIENDA a ON a.N_ID_AZIENDA=u.N_ID_UDD;

  
  CREATE OR REPLACE FORCE VIEW "TMPOD_CLOUD"."POD_POD_UDD_STOR_CM" ("T_PIVA", "POD_14", "T_AREA_RIF", "D_INIZIO", "D_FINE", "N_ID_UDD") AS 
  select distinct "T_PIVA","POD_14","T_AREA_RIF","D_INIZIO","D_FINE","N_ID_UDD" from (
SELECT /*+ parallel (2) */ a.T_PIVA,
substr(p.T_CODICE_POD,1,14) POD_14,p.T_AREA_RIF,u.D_INIZIO,u.D_FINE , 
CAST(u.N_ID_UDD AS VARCHAR2(50)) AS N_ID_UDD
  FROM (SELECT distinct T_CODICE_POD, N_ID_POD, T_AREA_RIF FROM RCU.RCU_POD UNION SELECT T_CODICE_POD, N_ID_POD,T_AREA_RIF FROM RCUS.RCUS_POD) p 
  JOIN RCU.RCU_POD_UDD u ON p.N_ID_POD=u.N_ID_POD
  JOIN RCU.RCU_AZIENDA a ON a.N_ID_AZIENDA=u.N_ID_UDD
  union
  SELECT /*+ parallel (2) */ a.T_PIVA,
substr(p.T_CODICE_POD,1,14) POD_14,p.T_AREA_RIF,u.D_INIZIO,u.D_FINE , 
CAST(u.N_ID_UDD AS VARCHAR2(50)) AS N_ID_UDD
  FROM (SELECT distinct T_CODICE_POD, N_ID_POD,T_AREA_RIF FROM RCU.RCU_POD UNION SELECT T_CODICE_POD, N_ID_POD,T_AREA_RIF FROM RCUS.RCUS_POD) p 
  JOIN RCUS.RCUS_POD_UDD u ON p.N_ID_POD=u.N_ID_POD
  JOIN RCU.RCU_AZIENDA a ON a.N_ID_AZIENDA=u.N_ID_UDD WHERE U.B_VALIDO = 'N');

  
  CREATE OR REPLACE FORCE VIEW "TMPOD_CLOUD"."STATO_POD" ("T_CODICE_POD", "STATO_POD") AS 
  SELECT substr(a.T_CODICE_POD,1,14) T_CODICE_POD, CASE WHEN EXISTS (  SELECT a.n_id_pod FROM RCU.RCU_POD_STATO a  WHERE a.n_id_pod = b.n_id_pod  AND '201803' between TO_CHAR(NVL(a.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(a.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM')  and a.D_AGGIORNAMENTO = (SELECT max(z.d_aggiornamento) from RCU.RCU_POD_STATO z where z.n_id_pod = a.n_id_pod  and '201803' between TO_CHAR(NVL(z.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(z.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM'))  ) THEN 'Y'  WHEN EXISTS ( SELECT 'Y'  FROM RCUS.RCUS_PODSTATO r  WHERE r.n_id_pod = b.n_id_pod  and '201803'  between TO_CHAR(NVL(r.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(r.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM') and r.b_valido='Y'  and r.D_AGGIORNAMENTO = (SELECT max(z.d_aggiornamento) from RCUS.RCUS_PODSTATO z where z.n_id_pod = r.n_id_pod  and '201803'  between TO_CHAR(NVL(r.D_ATTIVAZIONE,TO_DATE('19000101','yyyymmdd')),'YYYYMM')  AND TO_CHAR(NVL(r.D_DISATTIVAZIONE,TO_DATE('20991231','yyyymmdd')),'YYYYMM') and z.b_valido='Y') ) THEN 'Y'  ELSE 'N' END AS STATO_POD  FROM RCU.RCU_POD_STATO b  JOIN RCU.RCU_POD a ON a.n_id_pod = b.n_id_pod;

--Sequence

   CREATE SEQUENCE  "TMPOD_CLOUD"."PRT_TMO_AGGR_CALC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5040061 CACHE 20 NOORDER  NOCYCLE ;

  
--Trigger
CREATE OR replace TRIGGER PRT_TMO_AGGR_CALC_ON_INSERT
  BEFORE INSERT ON PRT_TMO_AGGREGATI_CALCOLATI
  FOR EACH ROW
BEGIN
  SELECT PRT_TMO_AGGR_CALC_SEQ.nextval
  INTO :new.N_ID
  FROM dual;
END;
