rule.csv.alreadyTransmittedTFC.enabled=true
rule.csv.alreadyTransmittedVPG.enabled=true
rule.csv.alreadyTransmittedQKRIUD.enabled=true

rule.csv.alreadyComputedTFC.enabled=true
rule.csv.alreadyComputedVPG.enabled=true
rule.csv.alreadyComputedQKRIUD.enabled=true

rule.csv.checkTFCFileName.enabled=true
rule.csv.checkVPGFileName.enabled=true

rule.csv.checkTFCPivaRdb.enabled=true
rule.csv.checkVPGPivaRdb.enabled=true
rule.csv.checkQKRIUDPivaRdb.enabled=true

rule.csv.checkTFCFileHeader.enabled=true
rule.csv.checkVPGFileHeader.enabled=true
rule.csv.checkQKRIUDFileHeader.enabled=true

rule.csv.checkTFCFileExtension.enabled=true
rule.csv.checkVPGFileExtension.enabled=true
rule.csv.checkQKRIUDFileExtension.enabled=true

rule.csv.checkTFCFieldsNumber.enabled=true
rule.csv.checkVPGFieldsNumber.enabled=true

rule.csv.checkTFCFileIntegrity.enabled=true
rule.csv.checkVPGFileIntegrity.enabled=true
rule.csv.checkQKRIUDFileIntegrity.enabled=true

rule.csv.checkTFCDate.enabled=true
rule.csv.checkTFCDateFormat.enabled=true
rule.csv.checkTFCDateConsistence.enabled=true

rule.csv.checkTFCRegClimMandatory.enabled=true
rule.csv.checkTFCRegClimMismatch.enabled=true

rule.csv.checkTFCWKRDefined.enabled=true
rule.csv.checkTFCWKRFormat.enabled=true


rule.csv.checkVPGDate.enabled=true
rule.csv.checkVPGDateConsistence.enabled=true
rule.csv.checkVPGMandatoryFields.enabled=true
rule.csv.checkVPGFieldsFormat.enabled=true
rule.csv.checkVPGFields.enabled=true

rule.csv.checkQKRIUDDate.enabled=true
rule.csv.checkQKRIUDDateConsistence.enabled=true
rule.csv.checkQKRIUDcodRemi.enabled=true
rule.csv.checkQKRIUDMandatoryField.enabled=true
rule.csv.checkQKRIUDDateFormat.enabled=true
rule.csv.checkQKRIUDDateExistance.enabled=true
rule.csv.checkQKRIUDCodRemiFormat.enabled=true
rule.csv.checkQKRIUDQKRIUDfieldFormat.enabled=true
rule.csv.checkCodRemiExistanceRcugas.enabled=true


csv.input.path=${isilon.csv.inputPath}
csvAmmissibilita.output.path=${isilon.csv.ammissibilitaOutputPath}

tsg.TFCFile.basepath=${tsg.TFCFile.basepath}
tsg.TFCFile.tableName=${tsg.db}.${tsg.TFCFile.tableName}
tsg.VPGFile.basepath=${tsg.VPGFile.basepath}
tsg.VPGFile.tableName=${tsg.db}.${tsg.VPGFile.tableName}
tsg.QKRIUDFile.basepath=${tsg.QKRIUDFile.basepath}
tsg.QKRIUDFile.tableName=${tsg.db}.${tsg.QKRIUDFile.tableName}

tsg.ReportAmmissibilitaTFC.basepath=${tsg.ReportAmmissibilitaTFC.basepath}
tsg.ReportAmmissibilitaTFC.tableName=${tsg.db}.${tsg.ReportAmmissibilitaTFC.tableName}
tsg.ReportAmmissibilitaVPG.basepath=${tsg.ReportAmmissibilitaVPG.basepath}
tsg.ReportAmmissibilitaVPG.tableName=${tsg.db}.${tsg.ReportAmmissibilitaVPG.tableName}
tsg.ReportAmmissibilitaQKRIUD.basepath=${tsg.ReportAmmissibilitaQKRIUD.basepath}
tsg.ReportAmmissibilitaQKRIUD.tableName=${tsg.db}.${tsg.ReportAmmissibilitaQKRIUD.tableName}

tsg.PubblicazioneAmmissibilitaTFC.basepath=${tsg.PubblicazioneAmmissibilitaTFC.basepath}
tsg.PubblicazioneAmmissibilitaTFC.tableName=${tsg.db}.${tsg.PubblicazioneAmmissibilitaTFC.tableName}
tsg.PubblicazioneAmmissibilitaVPG.basepath=${tsg.PubblicazioneAmmissibilitaVPG.basepath}
tsg.PubblicazioneAmmissibilitaVPG.tableName=${tsg.db}.${tsg.PubblicazioneAmmissibilitaVPG.tableName}
tsg.PubblicazioneAmmissibilitaQKRIUD.basepath=${tsg.PubblicazioneAmmissibilitaQKRIUD.basepath}
tsg.PubblicazioneAmmissibilitaQKRIUD.tableName=${tsg.db}.${tsg.PubblicazioneAmmissibilitaQKRIUD.tableName}

tsg.TSGTFC.basepath =${tsg.TSGTFC.basepath}
tsg.TSGTFC.tableName=${tsg.db}.${tsg.TSGTFC.tableName}
tsg.TSGVPG.basepath=${tsg.TSGVPG.basepath}
tsg.TSGVPG.tableName=${tsg.db}.${tsg.TSGVPG.tableName}
tsg.TSGQKRIUD.basepath=${tsg.TSGQKRIUD.basepath}
tsg.TSGQKRIUD.tableName=${tsg.db}.${tsg.TSGQKRIUD.tableName}

rcugas.remiStato.tableName=${rcugas.db}.${rcugas.remiStato.tableName}
rcugas.remi.tableName=${rcugas.db}.${rcugas.remi.tableName}
