CREATE TABLE IF NOT EXISTS ${hiveconf:switching_db}.dati_storici
(
d_data_decorrenza string
, pod14 string
, piva_distr string
, piva_udd string
, trattamento string
, trattamento_online string
, dp string
, tipo_dato string
, last_potf1 string
, last_potf2 string
, last_potf3 string
, last_potf4 string
, last_potf5 string
, last_potf6 string
, last_potmax string
, somma_eaf1 string
, somma_eaf2 string
, somma_eaf3 string
, somma_eaf4 string
, somma_eaf5 string
, somma_eaf6 string
, somma_eam string
, somma_giorni bigint
, giorni_mese int
, anno_misura_next int
, mese_misura_next int
, pod string
, data_misura string
, e1 string
, e2 string
, e3 string
, e4 string
, e5 string
, e6 string
, e7 string
, e8 string
, e9 string
, e10 string
, e11 string
, e12 string
, e13 string
, e14 string
, e15 string
, e16 string
, e17 string
, e18 string
, e19 string
, e20 string
, e21 string
, e22 string
, e23 string
, e24 string
, e25 string
, e26 string
, e27 string
, e28 string
, e29 string
, e30 string
, e31 string
, e32 string
, e33 string
, e34 string
, e35 string
, e36 string
, e37 string
, e38 string
, e39 string
, e40 string
, e41 string
, e42 string
, e43 string
, e44 string
, e45 string
, e46 string
, e47 string
, e48 string
, e49 string
, e50 string
, e51 string
, e52 string
, e53 string
, e54 string
, e55 string
, e56 string
, e57 string
, e58 string
, e59 string
, e60 string
, e61 string
, e62 string
, e63 string
, e64 string
, e65 string
, e66 string
, e67 string
, e68 string
, e69 string
, e70 string
, e71 string
, e72 string
, e73 string
, e74 string
, e75 string
, e76 string
, e77 string
, e78 string
, e79 string
, e80 string
, e81 string
, e82 string
, e83 string
, e84 string
, e85 string
, e86 string
, e87 string
, e88 string
, e89 string
, e90 string
, e91 string
, e92 string
, e93 string
, e94 string
, e95 string
, e96 string
, e97 string
, e98 string
, e99 string
, e100 string
, anno_misura int
, mese_misura int
, messa_regime string
, tipo_misuratore string
, t_tipo_configurazione string
, somma_eaf1_riconf string
, somma_eaf2_riconf string
, somma_eaf3_riconf string
, d_creazione timestamp
, d_caricamento timestamp
)
PARTITIONED BY
(
annomese_sw string
, nome_flusso string
)
STORED AS PARQUET;
