package it.eng.au.portale_consumi_ee.model.mongodbs

case class podModel(
                         n_id_pod:String = null,
                         t_codice_pod:String = null,
                         id_indirizzo:String = null,
                         n_id_fornitura:String = null,
                         n_id_cliente:String = null,
                         d_inizio_titolarita:  java.lang.Long = null,
                         d_inizio_titolarita_str:String = null,
                         d_fine_titolarita:  java.lang.Long = null,
                         d_fine_titolarita_str:String = null,
                         tipo_mercato:String = null,
                         n_id_fornitore:String = null,
                         t_residente:String = null,
                         tariffa:String = null,
                         t_toponimo:String = null,
                         t_nomestrada:String = null,
                         t_civico:String = null,
                         t_comune:String = null,
                         t_cap:String = null,
                         t_provincia:String = null,
                         t_nazione:String = null,
                         potenza_disponibile:String = null,
                         potenza_impegnata:String = null,
                         tensione:String = null,
                         tipo_misuratore:String = null,
                         cambio_gdm:String = null,
                         data_cambio_gdm:  java.lang.Long = null,
                         data_cambio_gdm_str:String = null,
                         d_inst_misurator_att:  java.lang.Long = null,
                         stato_misuratore_2g:String = null,
                         trattamento:String = null,
                         data_switch:  java.lang.Long = null,
                         switching_in_corso:String = null,
                         d_oper_misurator_att:  java.lang.Long = null,
                         d_oper_misurator_att_str:String = null,
                         matricola_misuratore:String = null,
                         anno_start_misure_orarie: java.lang.Integer = null,
                         mese_start_misure_orarie: java.lang.Integer = null,
                         t_piva:String = null,
                         t_rag_soc:String = null,
                         t_servizio_tutela_sii:String = null
                         )
