# proprietà processo
output.file.csv_max_row=10000
# 25MB
output.file.zip_max_byte_size=25000000
output.file.temporary_path=/mnt/isilonshare1_Parallelo/CCE/tmpOutPath/
output.file.path=/mnt/isilonshare1_Parallelo/CCE/outPath/

# tabelle hive
# output
hive.table.cceRichiestaPod=eng_test.cce_richiesta_pod
hive.table.cceRichiestaFiltro=eng_test.cce_richiesta_filtro
hive.table.cceEsito=eng_test.cce_esito
hive.table.cceEsitoExport=eng_test.cce_esito_export
hive.table.cceCalcoloCa=eng_test.cce_calcolo_ca
hive.table.cceCalcoloCaFlussi=eng_test.cce_calcolo_ca_flussi
# input
hive.table.cceCalcoloAnagrafica=eng_test.cce_calcolo_anag
hive.table.cceCalcoloP=eng_test.cce_calcolo_p
hive.table.cceCalcoloPein=eng_test.cce_calcolo_p_ein
hive.table.cceCalcoloPR=eng_test.cce_calcolo_pr
hive.table.cceCalcoloPRein=eng_test.cce_calcolo_pr_ein
hive.table.cceCalcoloTrattamento=eng_test.cce_calcolo_trattamento
hive.table.cceCalcTrack=eng_test.cce_calc_track


# properties per script SH (non necessario riportarle su params.properties)
# tabelle oracle
oracle.table.cceRichiestaPod=cce.cce_richiesta_pod
oracle.table.cceRichiestaFiltro=cce.cce_richiesta_filtro
oracle.table.cceEsito=cce.cce_esito
oracle.table.cceEsitoStaging=cce.cce_esito_stg
# tabelle hive per hcatalog
sqoop.db.import=eng_test
sqoop.table.cceRichiestaPod=cce_richiesta_pod
sqoop.table.cceRichiestaFiltro=cce_richiesta_filtro
sqoop.table.cceEsito=cce_esito_export

# percorsi rilascio e properties
# hdfs
deploy.path.hdfs=/user/eng_test/cce/pubblicazione
sqoop.config.path=/apps/deploy/sqoop-collaudo.properties
# local-linux
deploy.path.local=/home/eng_test/cce/pubblicazione
deploy.path.logs=/home/eng_test/cce/pubblicazione/logs
# user
hadoop_username=eng_test
