# DEPLOY HDFS
hdfs.user=eng_test
hdfs.deploy.path=/user/eng_test/calcolo_capacita/deploy
hdfs.hive.site.path=/user/${hdfs.user}/ee-switching/hive-site.xml

#LOGS
root.path=/mnt
logs.root.path=${root.path}/isilonshare1_Parallelo/calcolo_capacita/logs

#APPLICATION
application.spark.date.format=yyyy/MM/dd
application.sh.date.format=+%Y/%m/%d
application.oracle.date.format=yyyy/mm/dd

# SPARK
deploy.mode=cluster
#deploy.mode=client
spark.num.executors=59
spark.executor.cores=5
spark.executor.memory=39G
spark.driver.memory=5G
spark.parallelism=590
spark.shuffle=590
spark.memoryoverhead=3G


#HIVE
#IMPORT
hive.db=eng_test
hive.jdbc.url=jdbc:hive2://dmphclo07:10000
hive.jdbc.user=eng_test

#ORACLE IMPORT AND EXPORT
oracle.schema=CLG

oracle.table.clg_perimetro_remi_gm_view.db=${oracle.schema}
oracle.table.clg_perimetro_pdr_gm_view.db=${oracle.schema}
oracle.table.perimetropdr.name.db=${oracle.schema}

hive.table.clg_perimetro_remi_gm_view.db=${hive.db}
hive.table.clg_perimetro_pdr_gm_view.db=${hive.db}
hive.table.perimetropdr.db=${hive.db}

oracle.table.clg_perimetro_remi_gm_view.name=CLG_PERIMETRO_REMI_V_COLL
oracle.table.clg_perimetro_pdr_gm_view.name=CLG_PERIMETRO_PDR_V_COLL
oracle.table.perimetropdr.name=CLG_PERIMETRO_PDR_PUNTUALE_V

hive.table.clg_perimetro_pdr_gm_view.name=CLG_PERIMETRO_PDR_V
hive.table.clg_perimetro_remi_gm_view.name=CLG_PERIMETRO_REMI_V
hive.table.perimetropdr.name=CLG_PERIMETRO_PDR_PUNTUALE_V


oracle.table.clg_pdr_capacita_tmp.name=CLG_PDR_CAPACITA_TMP
oracle.table.clg_pdr_capacita_tmp.db=${oracle.schema}

#SCRIPT
oracle.query.create_view_pdr=create-view-pdr-mocked.sh
oracle.query.create_view_remi=create-view-remi-mocked.sh

#SQOOP TECHNICAL DETAIL
sqoop.num.mappers=5
sqoop.cat.command=hdfs dfs -cat
sqoop.properties.hdfs.path=/user/eng_test/calcolo_capacita/oracle_collaudo.properties
sqoop.null.character=\\\\N
#************************************************************

#MISURE TABLE
#dove il job py scrive le misure
py.hive.table.sbgmisure.db=${hive.db}
py.hive.table.sbgmisure.name=calcolo_consumi_sbg
#dove il job scala legge scrive le misure
hive.table.sbgmisure.db=${hive.db}
hive.table.sbgmisure.name=calcolo_consumi_sbg


#ANAGRAFICA TABLE
hive.table.anagrafica.db=${hive.db}
hive.table.anagrafica.name=clg_anagrafica_gm_view


#RESULT TABLE
hive.table.result.db=${hive.db}
hive.table.result.name=CLG_PDR_CAPACITA_TMP


#rcu gas massivo p
hive.table.rcugasmassivop.db=rcugas
hive.table.rcugasmassivop.name=rcugas_massivo_p

# HIVE DATE FORTMAT TO EXPORT

hive.date.format.to_export="yyyy-MM-dd HH:mm:ss"
#*****************************************************************