package it.eng.au.sgsFlussoStoricoGas.schema.pubblicazione

import it.eng.au.sgsFlussoStoricoGas.schema.SchemaEnum

object XmlOutputSchema extends SchemaEnum {
  val
  piva_utente,
  matr_mis,
  data_inst_mis,
  gruppo_mis_int,
  classe_gruppo_mis,
  telegestione,
  pre_conv,
  matr_conv,
  coeff_cor,
  data_inst_conv,
  cod_remi,
  id_reg_clim,
  tipo_mis,
  cod_pdr,
  mese_anno,
  mese_anno_decorr,
  mese_anno_pub,
  trattamento,
  piva_distr,
  prel_aggregato,
  prelievo_1,
  prelievo_2,
  prelievo_3,
  prelievo_4,
  prelievo_5,
  prelievo_6,
  prelievo_7,
  prelievo_8,
  prelievo_9,
  prelievo_10,
  prelievo_11,
  prelievo_12,
  prelievo_13,
  prelievo_14,
  prelievo_15,
  prelievo_16,
  prelievo_17,
  prelievo_18,
  prelievo_19,
  prelievo_20,
  prelievo_21,
  prelievo_22,
  prelievo_23,
  prelievo_24,
  prelievo_25,
  prelievo_26,
  prelievo_27,
  prelievo_28,
  prelievo_29,
  prelievo_30,
  prelievo_31
  = Value
}