oozie.use.system.libpath=true
security_enabled=False
dryrun=False
send_email=False
nameNode=hdfs://hdfs.fsisilon.siiau.local:8020
jobTracker=yarnRM
softwarePath=/user/${hdfs.user}/Software/ee-switching

HDFS_DEPLOY_PATH=${nameNode}${softwarePath}/deploy
HIVE_SITE_XML_PATH=${nameNode}${softwarePath}/hive-site.xml

startTime=2021-12-31T00:00Z
endTime=2121-12-31T00:00Z
frequenza=30 9 23 * *
workflowPath=${nameNode}${softwarePath}/deploy/oozie/workflow.xml
coordinatorName=Switching EE Coordinator
workflowName=Switching EE Workflow

oozie.coord.application.path=${nameNode}${softwarePath}/deploy/oozie/coordinator.xml
