agg.dailyConsumption.tableName=${agg.db}.${dailyConsumption.tableName}
agg.dailyConsumption.executionid=1624261923745
#agg.dailyConsumption.infodb=${agg.db}

agg.validateFlow.tableName=${agg.db}.validated_flows_agg
rcugas.varMisuratore.tableName=${rcugas.db}.rcugas_var_misuratore_p
rcugas.remiAnagrafica.tableName=${rcugas.db}.rcugas_remi_anagrafica_p
rcugas.gestTrasporto.tableName=${rcugas.db}.rcugas_gesttrasporto_p
rcugas.vIt.tableName=${rcugas.db}.v_rcugas_it_p
rcugas.connDistr2.tableName=${rcugas.db}.rcugas_connessioni_distr2_p

isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}
hdfs.tmp.basepath=${hdfs.tmp.basepath}
hdfs.output.basepath=${hdfs.output.basepath}
hdfs.infoLog.tableName=${agg.db}.aggregatore_info_log

#da nuovo sw con le perfomance
hdfs.output.basepath.infoLog=${hdfs.output.basepath}


zip.session.name=AGG_S1_PRE
year=2021

maxDimensionZipFileByte=100000000
maxNumRowFile=600000
maxSizeThresholdZip = 60000000

#da nuovo sw con le perfomance
csvMaxRowLength=600000

# Lista csv di coppie. Una coppia ha la seguente sintassi: left_value->right_value.
# Valori consentiti per left_value: aggregato, dettaglioUnico, esclusi, dettaglio, dtg, incoerenti
# Valori consentiti per right_value: AGG1, AGG2, AGG3, AGG4, AGG5
# Esempio: genera aggregato.zip per AGG1 e AGG5 e Esclusi.zip per AGG2
#          file.couples.type=aggregato->AGG1,aggregato->AGG5,esclusi->AGG2
output.file.couples=Aggregato->AGG1
publication.type=AGG