package it.eng.au.sgsFlussoStoricoGas.schema.aggregazione

import it.eng.au.sgsFlussoStoricoGas.schema.SchemaEnum

object AggregatoreInfoDettSchema extends SchemaEnum {
  val
  id_aggregatore_info,
  tipo_flusso,
  tipo_pratica,
  nome_servizio,
  piva_utente_dest,
  anno_mese_comp,
  execution_id_perimetro_sgs,
  execution_id,
  n_id_pratica,
  d_data_decorrenza,
  cod_pdr,
  matr_mis,
  data_inst_mis,
  classe_mis_int,
  classe_gruppo_mis,
  telegestione,
  pre_conv,
  tipo_mis,
  coeff_corr,
  matr_conv,
  data_inst_conv,
  cod_remi,
  id_reg_clim,
  piva_distr,
  trattamento,
  anno_mese,
  prelievo_aggregato,
  prelievo_1,
  prelievo_2,
  prelievo_3,
  prelievo_4,
  prelievo_5,
  prelievo_6,
  prelievo_7,
  prelievo_8,
  prelievo_9,
  prelievo_10,
  prelievo_11,
  prelievo_12,
  prelievo_13,
  prelievo_14,
  prelievo_15,
  prelievo_16,
  prelievo_17,
  prelievo_18,
  prelievo_19,
  prelievo_20,
  prelievo_21,
  prelievo_22,
  prelievo_23,
  prelievo_24,
  prelievo_25,
  prelievo_26,
  prelievo_27,
  prelievo_28,
  prelievo_29,
  prelievo_30,
  prelievo_31,
  t_stato_dett
  = Value
}
