agg.dailyConsumption.tableName=${agg.db}.${dailyConsumption.tableName}
agg.dailyConsumption.executionid=1624261923745
agg.dailyConsumptionIncoerenti.tableName=${agg.db}.${dailyConsumptionIncoerenti.tableName}
agg.dailyConsumptionIncoerenti.executionid=1624261923745
agg.dailyConsumptionEsclusi.tableName=${agg.db}.${dailyConsumptionEsclusi.tableName}
agg.dailyConsumptionEsclusi.executionid=1624261923745
#agg.dailyConsumption.infodb=${agg.db}

agg.validateFlow.tableName=${agg.db}.validated_flows_agg
rcugas.varMisuratore.tableName=${rcugas.db}.rcugas_var_misuratore_p
rcugas.pdr.tableName=${rcugas.db}.rcugas_pdr_p
rcugas.remiAnagrafica.tableName=${rcugas.db}.rcugas_remi_anagrafica_p
rcugas.gestTrasporto.tableName=${rcugas.db}.rcugas_gesttrasporto_p
rcugas.vIt.tableName=${rcugas.db}.v_rcugas_it_p
rcugas.connDistr2.tableName=${rcugas.db}.rcugas_connessioni_distr2_p


isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}
hdfs.tmp.basepath=${hdfs.tmp.basepath}
hdfs.output.basepath=${hdfs.output.basepath}
hdfs.infoLog.tableName=${agg.db}.aggregatore_info_log

#da nuovo sw con le perfomance
hdfs.output.basepath.infoLog=${hdfs.output.basepath}


zip.session.name=AGG_S1_PRE
year=2021

maxDimensionZipFileByte=100000000
maxNumRowFile=600000
maxSizeThresholdZip = 60000000

#da nuovo sw con le perfomance
csvMaxRowLength=600000

# Utilizzato per la sterilizzazione degli incoerenti
class.group.measure.range.max.path=${hdfs.path}/gruppo_mis_limit.csv
incoerenzaGDM.numberOfDays.threshold=5

# Lista csv di coppie. Una coppia ha la seguente sintassi: left_value->right_value.
# Valori consentiti per left_value: aggregato, dettaglioUnico, esclusi, dettaglio, dtg, incoerenti, incoerentidettaglio
# Valori consentiti per right_value: AGG1, AGG2, AGG3, AGG4, AGG5
# Esempio: genera aggregato.zip per AGG1 e AGG5 e Esclusi.zip per AGG2
#          file.couples.type=aggregato->AGG1,aggregato->AGG5,esclusi->AGG2

#Configurazione per Esclusi 1/2/4/5
#output.file.couples=esclusi->AGG1,esclusi->AGG2,esclusi->AGG4,esclusi->AGG5

#Solo INCOERENTI/ANOMALI
#output.file.couples=incoerenti->AGG1,incoerenti->AGG2,incoerenti->AGG3,incoerenti->AGG4,incoerenti->AGG5

#Configurazione per file aggregati AGG1-2/3/4/5
#output.file.couples=aggregato->AGG1,aggregato->AGG2,aggregato->AGG3,aggregato->AGG4,aggregato->AGG5

#Configurazione per Esclusi 1/2/4/5, Dettaglio PDR_G AGG-1/4/5
#output.file.couples=esclusi->AGG1,esclusi->AGG2,esclusi->AGG4,esclusi->AGG5,dettaglio->AGG1,dettaglio->AGG4,dettaglio->AGG5

#Configurazione per DTG AGG-5
#output.file.couples=dtg->AGG5

#Configurazione Dettaglio Unico AGG1 AGG4 AGG5
#output.file.couples=dettaglioUnico->AGG5

output.file.couples=Aggregato->AGG1

publication.type=AGG