#PYTHON SCRIPT
daily.consumption.hdfs.path=/user/hive/warehouse/au.db/misure_gas_au/sbg/daily_consumption_sbg
py.hive.table.sbgmisure.db=clg
py.hive.table.sbgmisure.name=calcolo_consumi_sbg

#SPARK SUBMIT
isilon.path=/home/sii_misure_gas/CLG/deploy
month.offset=2
sbg.type=POST
num.csv.lines=110000
sbgmisure-hdfs-path=/user/hive/warehouse/clg.db/calcolo_consumi_sbg
daily.consumption.table.name=sbg.daily_consumption_sbg
isilon.output.path=/mnt/Settlement
hdfs.output.basepath.infoLog=/user/hive/warehouse/clg.db/aggregatore_info_log_clg