agg.db=eng_test
agg.rootpath=/user/eng_test/agg
dailyConsumption.tableName=daily_consumption_agg
dailyConsumptionIncoerenti.tableName=daily_consumption_agg_incoerenti
dailyConsumptionEsclusi.tableName=daily_consumption_agg_esclusi

dataset.numberPartitions=10

deploy.path=/home/eng_test/gsv/deploy
deploy.path.hdfs=/user/eng_test/gsv/deploy

hive.gsv=eng_test
hive.sqoop.location=/user/eng_test/hive
hive.gsvrichiestalocation=/user/eng_test/hive/gsv5_cons_richiesta
hive.gsvforniturelocation=/user/eng_test/hive/gsv5_cons_forniture
hive.gsvaggregatolocation=/user/eng_test/hive/gsv5_cons_aggr

connection.string.oracle = /user/eng_test/agg/oracle_collaudo.properties

ISILON_DEPLOY_PATH = /home/eng_test/agg/deploy/sqoop