# DEPLOY HDFS
#
hdfs.deploy.path=/user/eng_test/calcolo_capacita/deploy
#

#LOGS
root.path=/tmp
logs.root.path=${root.path}/calcolo_capacita/logs

#APPLICATION
application.spark.date.format=yyyy/MM/dd
application.sh.date.format=+%Y/%m/%d
application.oracle.date.format=yyyy/mm/dd

# SPARK
#deploy.mode=cluster
deploy.mode=client
spark.num.executors=2
spark.executor.cores=2
spark.executor.memory=4G
spark.driver.memory=1G
spark.parallelism=1000
spark.shuffle=590
spark.memoryoverhead=2G

#HIVE
#IMPORT
hive.db=eng_test_flussi_switching_ee
hive.jdbc.url=jdbc:hive2://dmphclo07:10000
hive.jdbc.user=eng_test

#ORACLE IMPORT AND EXPORT
oracle.schema=MADDARII

oracle.table.clg_perimetro_remi_gm_view.db=${oracle.schema}
oracle.table.clg_perimetro_pdr_gm_view.db=${oracle.schema}
oracle.table.perimetropdr.name.db=${oracle.schema}

hive.table.clg_perimetro_remi_gm_view.db=${hive.db}
hive.table.clg_perimetro_pdr_gm_view.db=${hive.db}
hive.table.perimetropdr.db=${hive.db}

oracle.table.clg_perimetro_remi_gm_view.name=CLG_PERIMETRO_REMI_V_COLL
oracle.table.clg_perimetro_pdr_gm_view.name=CLG_PERIMETRO_PDR_V_COLL
oracle.table.perimetropdr.name=CLG_CONFIG_ESECUZIONI_PUNTUALI

hive.table.clg_perimetro_pdr_gm_view.name=CLG_PERIMETRO_PDR_V
hive.table.clg_perimetro_remi_gm_view.name=CLG_PERIMETRO_REMI_V
hive.table.perimetropdr.name=CLG_PERIMETRO_PDR_PUNTUALE_V


oracle.table.clg_pdr_capacita_tmp.name=CLG_PDR_CAPACITA_TMP
oracle.table.clg_pdr_capacita_tmp.db=${oracle.schema}
#SCRIPT
oracle.query.create_view_pdr=create-view-pdr.sh
oracle.query.create_view_remi=create-view-remi.sh

#SQOOP TECHNICAL DETAIL
sqoop.num.mappers=1
sqoop.cat.command=hdfs dfs -cat
sqoop.properties.hdfs.path=/apps/deploy/job.properties
sqoop.null.character=\\\\N
#************************************************************

#MISURE TABLE
#dove il job py scrive le misure
py.hive.table.sbgmisure.db=${hive.db}
py.hive.table.sbgmisure.name=calcolo_consumi_sbg
#dove il job scala legge scrive le misure
hive.table.sbgmisure.db=${hive.db}
hive.table.sbgmisure.name=calcolo_consumi_sbg_clg

#ANAGRAFICA TABLE
hive.table.anagrafica.db=${hive.db}
hive.table.anagrafica.name=clg_anagrafica_gm_view

#RESULT TABLE
hive.table.result.db=${hive.db}
hive.table.result.name=CLG_PDR_CAPACITA_TMP

#rcu gas massivo p
hive.table.rcugasmassivop.db=${hive.db}
hive.table.rcugasmassivop.name=rcugas_massivo_p

# HIVE DATE FORTMAT TO EXPORT

hive.date.format.to_export="yyyy-MM-dd HH:mm:ss"
#*****************************************************************