CREATE TABLE ${hive.db.mongodbs}.${hive.table.pod} (
  n_id_pod STRING,
  t_codice_pod STRING,
  id_indirizzo STRING,
  n_id_fornitura STRING,
  n_id_cliente STRING,
  d_inizio_titolarita BIGINT,
  d_inizio_titolarita_str STRING,
  d_fine_titolarita BIGINT,
  d_fine_titolarita_str STRING,
  tipo_mercato STRING,
  n_id_fornitore STRING,
  t_residente STRING,
  tariffa STRING,
  t_toponimo STRING,
  t_nomestrada STRING,
  t_civico STRING,
  t_comune STRING,
  t_cap STRING,
  t_provincia STRING,
  t_nazione STRING,
  potenza_disponibile STRING,
  potenza_impegnata STRING,
  tensione STRING,
  tipo_misuratore STRING,
  cambio_gdm STRING,
  data_cambio_gdm BIGINT,
  data_cambio_gdm_str STRING,
  d_inst_misurator_att BIGINT,
  stato_misuratore_2g STRING,
  trattamento STRING,
  data_switch BIGINT,
  switching_in_corso STRING,
  d_oper_misurator_att BIGINT,
  d_oper_misurator_att_str STRING,
  matricola_misuratore STRING,
  anno_start_misure_orarie INT,
  mese_start_misure_orarie INT,
  t_piva STRING,
  t_rag_soc STRING,
  t_servizio_tutela_sii STRING
)
STORED AS PARQUET
TBLPROPERTIES (
  'bucketing_version' = '2'
);
