CREATE EXTERNAL TABLE ${hiveconf:hive_db}.prt_cmg_s02r_p(
  n_id_file string,
  t_name_file string,
  annomese_riferimento string,
  d_caricamento string,
  local_file string,
  cod_flusso string,
  piva_utente string,
  piva_distr string,
  cod_pdr string,
  mese_comp string,
  data_comp string,
  tipo_rettifica string,
  mot_ret_lett string,
  data_prest string,
  codprat_sii string,
  trattamento string,
  matr_mis string,
  matr_conv string,
  coeff_corr string,
  freq_let string,
  vol_annuo_rettificato string,
  data_racc string,
  let_tot_prel string,
  let_tot_conv string,
  vol_ric string,
  ini_periodo string,
  fine_periodo string,
  ammissibilita string)
PARTITIONED BY (
  annomese string)
STORED AS PARQUET