include "ammissibilita.conf"

hive{
  table {
    misure {
        autoletture=${hive.table.misure.autoletture}
        misure_mensili_c=${hive.table.misure.misure_mensili_c}
        misure_non_orarie_c=${hive.table.misure.misure_non_orarie_c}
        misure_orarie_c=${hive.table.misure.misure_orarie_c}
        volture=${hive.table.misure.volture}
        etl_stage3m_2=${hive.table.misure.etl_stage3m_2}
        etl_stage33m_2=${hive.table.misure.etl_stage33m_2}
        registro_load=${hive.table.misure.registro_load}
    }
  }
}

ambiente
{
lavoro=${ambiente.lavoro}
}

