package it.eng.au.pubblicazionePcg.schema

import it.eng.au.pubblicazionePcg.utility.Constants.CSV_SEPARATOR

object OutputCsvSchema extends SchemaEnum {
  val
  ANNOMESE,
  COD_PDR,
  PIVA_IT,
  COD_REMI,
  ID_REG_CLIM,
  COD_PROF_PREL_STD,
  TRATTAMENTO,
  TIPO_CLIENTE,
  UN_MIS_PREL,
  PRELIEVO_GIORN_1,
  PRELIEVO_GIORN_2,
  PRELIEVO_GIORN_3,
  PRELIEVO_GIORN_4,
  PRELIEVO_GIORN_5,
  PRELIEVO_GIORN_6,
  PRELIEVO_GIORN_7,
  PRELIEVO_GIORN_8,
  PRELIEVO_GIORN_9,
  PRELIEVO_GIORN_10,
  PRELIEVO_GIORN_11,
  PRELIEVO_GIORN_12,
  PRELIEVO_GIORN_13,
  PRELIEVO_GIORN_14,
  PRELIEVO_GIORN_15,
  PRELIEVO_GIORN_16,
  PRELIEVO_GIORN_17,
  PRELIEVO_GIORN_18,
  PRELIEVO_GIORN_19,
  PRELIEVO_GIORN_20,
  PRELIEVO_GIORN_21,
  PRELIEVO_GIORN_22,
  PRELIEVO_GIORN_23,
  PRELIEVO_GIORN_24,
  PRELIEVO_GIORN_25,
  PRELIEVO_GIORN_26,
  PRELIEVO_GIORN_27,
  PRELIEVO_GIORN_28,
  PRELIEVO_GIORN_29,
  PRELIEVO_GIORN_30,
  PRELIEVO_GIORN_31 = Value

  def header: String = this.getValues.mkString(CSV_SEPARATOR)

  def dailyColumns: List[String] = this.getValues.takeRight(31)
}
