package it.eng.au.portale_consumi_ee.model.misure

case class MisureStoricModel(
//                                  pod: String = null: String = null: String = null,
                                  pod: String = null,
                                  data_lettura: java.lang.Long = null,
                                  data_ricezione: java.lang.Long = null,
                                  motivazione: String = null,
                                  tipo_rettifica: String = null,
                                  eam: java.lang.Double = null,
                                  eaf1: java.lang.Double = null,
                                  eaf2: java.lang.Double = null,
                                  eaf3: java.lang.Double = null,
                                  eaf4: java.lang.Double = null,
                                  eaf5: java.lang.Double = null,
                                  eaf6: java.lang.Double = null,
                                  ea: String = null,
                                  er: String = null,
                                  consumo: java.lang.Double = null,
                                  perdita: java.lang.Double = null,
                                  potmax: java.lang.Double = null,
                                  is2g: String = null,
                                  tipo_flusso_num: java.lang.Byte = null,
                                  cod_flusso: String = null,
                                  tipo_flusso: String = null,
                                  descr_tipoflusso: String = null,
                                  descr_motivazione: String = null,
                                  data_lettura_str: String = null,
                                  data_ricezione_str: String = null,
                                  annomese: java.lang.Integer = null
                                )
