# Mid2
### preparazione (step 1)
# parametri
job.param.mid2_annomese_da=${job.param.mid2_annomese_da}
job.param.mid2_annomese_a=${job.param.mid2_annomese_a}
# indica il valore minimo di N per cui i PDR sono nel perimetro di calcolo (N > soglia)
job.param.mid2_soglia=${job.param.mid2_soglia}
# input
hive.table.mid_contatori=${hive.table.mid_contatori}
hive.table.agg_daily_consumption=${hive.table.agg_daily_consumption}
hive.table.rcu_azienda_p =${hive.table.rcu_azienda_p}
hive.table.rcugas_connessioni_distr2_remi_p =${hive.table.rcugas_connessioni_distr2_remi_p}
hive.table.variazioni_soc =${hive.table.variazioni_soc}

file.path.mid_alpha_valori=${file.path.mid_alpha_valori}

# output preparazione - input pubblicazione
hive.table.mid2_dettaglio=${hive.table.mid2_dettaglio}

# file esclusioni
file.path.mid2_esclusioni_pdr=${file.path.mid2_esclusioni_pdr}
file.path.mid2_esclusioni_distr=${file.path.mid2_esclusioni_distr}
file.path.mid2_esclusioni_tratt=${file.path.mid2_esclusioni_tratt}
file.path.mid2_esclusioni_annomese=${file.path.mid2_esclusioni_annomese}

### pubblicazione (step 2)
job.param.mid2_executionid_dett=${job.param.mid2_executionid_dett}
# nome sessione da forzare
job.param.mid2_session=${job.param.mid2_session}
job.param.mid2_split=${job.param.mid2_split}

## output pubblicazioni
# parita iva csea
job.param.csea_piva=${job.param.csea_piva}
# posizione file output
file.path.mid2=${file.path.mid2}
hive.table.mid_aggregatore_info=${hive.table.mid_aggregatore_info}
