### Parametri Job
# SBG
job.params.offset_sbg=${job.params.offset_sbg}
# Abilita/disabilita inclusioni ed esclusioni (TRUE/FALSE)
job.params.inclusion_sbg_enabled=${job.params.inclusion_sbg_enabled}
job.params.exclusion_sbg_enabled=${job.params.exclusion_sbg_enabled}
# Percorso file (HDFS)
file.path.inclusioni_sbg=${file.path.inclusioni_sbg}
file.path.esclusioni_sbg=${file.path.esclusioni_sbg}

### Tabelle Hive
# Input
# SBG
hive.table.sbg_incoerenti=${hive.table.sbg_incoerenti}
hive.table.sbg_esclusi=${hive.table.sbg_esclusi}
hive.table.sbg_daily_consumption=${hive.table.sbg_daily_consumption}
# Output
hive.table.mid_contatori=${hive.table.mid_contatori}
