## AGG
job.params.executionid_agg=${job.params.executionid_agg}
# Abilita/disabilita inclusioni ed esclusioni (TRUE/FALSE)
job.params.inclusion_agg_enabled=${job.params.inclusion_agg_enabled}
job.params.exclusion_agg_enabled=${job.params.exclusion_agg_enabled}
# Percorso file (HDFS)
file.path.inclusioni_agg=${file.path.inclusioni_agg}
file.path.esclusioni_agg=${file.path.esclusioni_agg}

## AGG BIT
# data in formato dd/mm/yyyy
job.params.data_back_in_time=${job.params.data_back_in_time}
job.params.annomese_da=${job.params.annomese_da}
job.params.annomese_a=${job.params.annomese_a}


### Tabelle Hive
# Input
# AGG
hive.table.agg_incoerenti=${hive.table.agg_incoerenti}
hive.table.agg_esclusi=${hive.table.agg_esclusi}
hive.table.agg_daily_consumption=${hive.table.agg_daily_consumption}
# Output
hive.table.mid_contatori=${hive.table.mid_contatori}
