# Mid1
### preparazione (step 1)
# parametri
job.param.mid1_annomese_da=${job.param.mid1_annomese_da}
job.param.mid1_annomese_a=${job.param.mid1_annomese_a}
# indica il valore minimo di N per cui i PDR sono nel perimetro di calcolo (N > soglia)
job.param.mid1_soglia=${job.param.mid1_soglia}
# input
hive.table.mid_contatori=${hive.table.mid_contatori}
hive.table.agg_daily_consumption=${hive.table.agg_daily_consumption}

file.path.mid_alpha_valori=${file.path.mid_alpha_valori}

# output preparazione - input pubblicazione
hive.table.mid1_dettaglio=${hive.table.mid1_dettaglio}

# file esclusioni
file.path.mid1_esclusioni_pdr=${file.path.mid1_esclusioni_pdr}
file.path.mid1_esclusioni_distr=${file.path.mid1_esclusioni_distr}
file.path.mid1_esclusioni_tratt=${file.path.mid1_esclusioni_tratt}
file.path.mid1_esclusioni_annomese=${file.path.mid1_esclusioni_annomese}

### pubblicazione (step 2)
job.param.mid1_executionid_dett=${job.param.mid1_executionid_dett}
# nome sessione da forzare
job.param.mid1_session=${job.param.mid1_session}
job.param.mid1_split=${job.param.mid1_split}

## output pubblicazioni
# posizione file output
file.path.mid1=${file.path.mid1}
hive.table.mid_aggregatore_info=${hive.table.mid_aggregatore_info}
