agg.db=eng_test
rcugas.db=eng_test

dailyConsumption.tableName=daily_consumption_sbg2
validateFlows.tableName=validated_flows_sbg
rcugas.sospensioni.tableName=rcugas_sospensioni_p
rcugas.pdr.tableName=rcugas_pdr_p

hdfs.basePath=/user/eng_test/sbg/queries

deploy.path=/home/eng_test/sbg/query
hdfs.config.path=/user/eng_test/sbg/deploy/query_report
aggregazione.sbg.hdfs.path=/user/eng_test/sbg/deploy/deploy_aggregazione