cdp.caFinal.executionid=1631183643380
cdp.caFinal.tableName=${cdp.db}.ca_final
rcugas.dist.tableName=${rcugas.db}.v_rcugas_distributore_p
rcu.azienda.tableName=${rcu.db}.rcu_azienda_p
rcugas.udb.tableName=${rcugas.db}.rcugas_udb_p
ca.tableName=${cdp.db}.ca
caPreFinal.tableName=${cdp.db}.ca_pre_final
cpd.validatedFlows.tableName=${cdp.db}.validated_flows

rcugas.massivofreeze.tableName=${rcugasMassivo.db}.rcugas_massivo_ca_p_freeze

cdp.caFinalCodProf.executionid=1631183643380
cdp.caFinalCodProf.tableName=${cdp.db}.cod_prof_std_da_tds

isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}

hdfs.output.basepath.csv=${hdfs.output.basepath.csv}
hdfs.output.basepath.csv.export=${hdfs.output.basepath.csv.export}
hdfs.output.basepath.infoLog=${hdfs.output.basepath.infoLog}
cdpDatiPrelievoGas.tableName=${cdp.db}.cdp_dati_prelievo_gas
aggregatoreInfoLogCdp.tableName=${cdp.db}.aggregatore_info_log_cdp

csvMaxRowLength=800000
maxSizeThresholdZip=80000000
csvFileSessionName=DA_IMPOSTARE

#output.file.couples=pre->CDP1,pre->CDP2,pre->CDP3
#output.file.couples=fin->CDP1,fin->CDP2,fin->CDP3
#output.file.couples=aggds->CDP1,aggds->CDP2,aggds->CDP3
#output.file.couples=aggric->CDP1,aggric->CDP2,aggric->CDP3
#output.file.couples=dedotti->CDP1,dedotti->CDP2,dedotti->CDP3
#output.file.couples=dettaglioFlussiPre->CDP1,dettaglioFlussiPre->CDP2,dettaglioFlussiPre->CDP3
#output.file.couples=dettaglioFlussiFin->CDP1,dettaglioFlussiFin->CDP2,dettaglioFlussiFin->CDP3
#output.file.couples=dettaglioFlussiRic->CDP1,dettaglioFlussiRic->CDP2,dettaglioFlussiRic->CDP3

output.file.couples=aggds->CDP1,aggds->CDP2,aggds->CDP3