flow.dataset.rgl.basePath=${measures.rootpath}/prt_cmg_rgl_p
flow.dataset.rml.basePath=${measures.rootpath}/prt_cmg_rml_p
flow.dataset.rmv.basePath=${measures.rootpath}/prt_cmg_rmv_p
flow.dataset.rsl.basePath=${measures.rootpath}/prt_cmg_rsl_p
flow.dataset.sw1.basePath=${measures.rootpath}/prt_cmg_sw1_p
flow.dataset.tal.basePath=${measures.rootpath}/prt_cmg_tal_p
flow.dataset.tav.basePath=${measures.rootpath}/prt_cmg_tav_p
flow.dataset.tas.basePath=${measures.rootpath}/prt_cmg_tas_p
flow.dataset.tgl.basePath=${measures.rootpath}/prt_cmg_tgl_p
flow.dataset.tml.basePath=${measures.rootpath}/prt_cmg_tml_p
flow.dataset.tmv.basePath=${measures.rootpath}/prt_cmg_tmv_p
flow.dataset.im1.basePath=${measures.rootpath}/prt_cmg_im1_p
flow.dataset.a01.basePath=${measures.rootpath}/prt_cmg_A01_0150_p
flow.dataset.a40.basePath=${measures.rootpath}/prt_cmg_A40_0150_p
flow.dataset.sm1.basePath=${measures.rootpath}/prt_cmg_SM1_0150_p
flow.dataset.sm1r.basePath=${measures.rootpath}/prt_cmg_sm1r_p
flow.dataset.sm2.basePath=${measures.rootpath}/prt_cmg_sm2_p
flow.dataset.sm2r.basePath=${measures.rootpath}/prt_cmg_sm2r_p
flow.dataset.fui.basePath=${measures.rootpath}/prt_cmg_fui_p
flow.dataset.a01r.basePath=${measures.rootpath}/prt_cmg_a01r_p
flow.dataset.a02.basePath=${measures.rootpath}/prt_cmg_a02_p
flow.dataset.a02r.basePath=${measures.rootpath}/prt_cmg_a02r_p
flow.dataset.a40r.basePath=${measures.rootpath}/prt_cmg_a40r_p
flow.dataset.d01r.basePath=${measures.rootpath}/prt_cmg_d01r_p
flow.dataset.d01.basePath=${measures.rootpath}/prt_cmg_D01_0150_p
flow.dataset.d02r.basePath=${measures.rootpath}/prt_cmg_d02r_p
flow.dataset.d02.basePath=${measures.rootpath}/prt_cmg_d02_p
flow.dataset.ad2r.basePath=${measures.rootpath}/prt_cmg_ad2r_p
flow.dataset.ad2.basePath=${measures.rootpath}/prt_cmg_ad2_p
flow.dataset.ad3r.basePath=${measures.rootpath}/prt_cmg_ad3r_p
flow.dataset.ad3.basePath=${measures.rootpath}/prt_cmg_ad3_p
flow.dataset.ad4r.basePath=${measures.rootpath}/prt_cmg_ad4r_p
flow.dataset.ad4.basePath=${measures.rootpath}/prt_cmg_ad4_p
flow.dataset.ad5r.basePath=${measures.rootpath}/prt_cmg_ad5r_p
flow.dataset.ad5.basePath=${measures.rootpath}/prt_cmg_ad5_p
flow.dataset.s02r.basePath=${measures.rootpath}/prt_cmg_s02r_p
flow.dataset.s02.basePath=${measures.rootpath}/prt_cmg_s02_p
flow.dataset.s40r.basePath=${measures.rootpath}/prt_cmg_s40r_p
flow.dataset.s40.basePath=${measures.rootpath}/prt_cmg_s40_p
flow.dataset.r01r.basePath=${measures.rootpath}/prt_cmg_r01r_p
flow.dataset.r01.basePath=${measures.rootpath}/prt_cmg_r01_p
flow.dataset.r40r.basePath=${measures.rootpath}/prt_cmg_r40r_p
flow.dataset.r40.basePath=${measures.rootpath}/prt_cmg_r40_p
flow.dataset.m01r.basePath=${measures.rootpath}/prt_cmg_m01r_p
flow.dataset.m01.basePath=${measures.rootpath}/prt_cmg_m01_p
flow.dataset.v01r.basePath=${measures.rootpath}/prt_cmg_v01r_p
flow.dataset.v01.basePath=${measures.rootpath}/prt_cmg_v01_p
flow.dataset.v02r.basePath=${measures.rootpath}/prt_cmg_v02r_p
flow.dataset.v02.basePath=${measures.rootpath}/prt_cmg_v02_p
flow.dataset.igmg.basePath=${measures.rootpath}/prt_cmg_igmg_p
flow.dataset.igmr.basePath=${measures.rootpath}/prt_cmg_igmr_p
flow.dataset.def.basePath=${measures.rootpath}/prt_cmg_def_p


tab_profili_giorn_std_perc.basepath=${settlegas.rootpath}/tab_profili_giorn_std_perc
tab_profili_giorn_std_perc.tableName=atg.tab_profili_giorn_std_perc
rcugasMassivoP.basepath=${rcugasMassivoP.basepath}
rcugasConnessioniDistr2Remi.basepath=${rcugasConnessioniDistr2Remi.basepath}
rcugasPdrDatiPrelievo.basepath=${rcugasPdrDatiPrelievo.basepath}
rcugasFornituraP.basepath=${rcugasFornituraP.basepath}
rcugasSospensioniP.basepath=${rcugasSospensioniP.basepath}
rcugasBilanciamentoP.basepath=${rcugasBilanciamentoP.basepath}
rcugasUdbP.basepath=${rcugasUdbP.basepath}
rcugasRemiAnagraficaP.basepath=${rcugasRemiAnagraficaP.basepath}
rcugasRemiAggregazioneP.basepath=${rcugasRemiAggregazioneP.basepath}
rcugasItP.basepath=${rcugasItP.basepath}
rcugasGestTrasportoP.basepath=${rcugasGestTrasportoP.basepath}
rcugasDistributoreP.basepath=${rcugasDistributoreP.basepath}

rcuAziendaP.basepath=${rcuAziendaP.basepath}

rcuGasVarMisuratoreP.basepath=${rcuGasVarMisuratoreP.basepath}
rcuGasVarConvertitoreP.basepath=${rcuGasVarConvertitoreP.basepath}
rcuGasVarPrelAnnuoP.basepath=${rcuGasVarPrelAnnuoP.basepath}
rcuGasVarProfiloP.basepath=${rcuGasVarProfiloP.basepath}
rcuGasVarTrattamentoP.basepath=${rcuGasVarTrattamentoP.basepath}

tdgCoeffK.basepath=${tdgCoeffK.basepath}
tdgCoeffK.table=${tdgCoeffK.table}

monthTreatment.table=${agg.db}.monthtreatment
monthTreatment.basepath=${agg.output.rootpath}/monthtreatment
validatedFlows.table=${agg.db}.validated_flows_agg
validatedFlows.basepath=${agg.output.rootpath}/validated_flows_agg
dailyConsumption.table=${agg.db}.daily_consumption_agg
dailyConsumption.basepath=${agg.output.rootpath}/daily_consumption_agg
segment.table=${agg.db}.segment_agg
segment.basepath=${agg.output.rootpath}/segment_agg
dailyConsumptionExcl.table = ${agg.db}.daily_consumption_agg_esclusi
dailyConsumptionExcl.basepath = ${agg.output.rootpath}/daily_consumption_agg_esclusi
dailyConsumptionIncGdM.table = ${agg.db}.daily_consumption_agg_incoerenti
dailyConsumptionIncGdM.basepath = ${agg.output.rootpath}/daily_consumption_agg_incoerenti


dataset.numberPartition=${dataset.numberPartitions}

flow.read.startDate=201901
flow.read.endDate=202105
#format YYYYMMDD
flow.read.ghigliottina=20210531
#format YYYYMMDD
rcugas.sqoop.date=20210611

# strong exclusion filter
filter.strongExclusion.enabled=false
filter.strongExclusion.folder.path=${deploy.path.strong.exclusion}
filter.strongForceExclusion.enabled=false
filter.strongForceExclusion.folder.path=${deploy.path.strong.forceExclusion}
filter.strongExclusion.backupTable=${strong.exclusion.backuptable.basepath}
#the filter is active iff the value is true
filter.exclusion.enabled=false
filter.exclusion.file.path=${deploy.path.hdfs}/exclusion.csv
filter.forceExclusion.enabled=false
filter.forceExclusion.file.path=${deploy.path.hdfs}/force_exclusion.csv
#File Size (MB) threshold to use bc join
broadcast.threshold=100
#the filter is active iff the value is true
#if multiple inclusion filter are active the record must satisfy all of them to be included
filter.inclusion.pdr.enabled=false
filter.inclusion.id_distr.enabled=false
filter.inclusion.id_distr_piva_udd.enabled=false
filter.inclusion.file.path=${deploy.path}/inclusion.csv
carriBombolai.basepath=${deploy.path.hdfs}/carri_bombolai.csv

#filter duplicate measures
filter.duplicateMeasures.enable=true
filter.duplicateMeasures.groupByFilePath.enable=true
filter.duplicateMeasures.groupByTimestamp.enable=true
filter.duplicateMeasures.groupByFileName.enable=true

period.read.startDate=202001
period.read.endDate=202012

session=AGG_S1_PRE

ca.annotermico=2020

#values: infered or rcugas
treatment.calcMode=infered

#moltiplicatori consumi incoerenti
#format double ex. 0.5, 1.4, 2.8, 15.28, etc...
sterilize.measure.enable = true
multiplier.max.range.x = 1.0
multiplier.consumption.sterilize.y = 1.0
class.group.measure.range.max.path=${deploy.path}/gruppo_mis_limit.csv

#set dynamic properties
period.read.startDate.time.back = 5y
period.read.endDate.time.back = 1m
flow.read.startDate.time.back.wrt.period.read.startDate = 1y
flow.read.endDate.time.back = 0d
flow.read.ghigliottina.time.back = 2d
rcugas.sqoop.date.time.back = 2d

#period.read.startDate.numero.anni.indietro = 5
#period.read.endDate.numero.mesi.indietro = 1
#flow.read.startDate.numero.anni.indietro.rispetto.period.read.startDate = 1
#flow.read.endDate.numero.giorni.indietro.rispetto.sys.date = 0
#flow.read.ghigliottina.numero.giorni.indietro.rispetto.sys.date = 2
#rcugas.sqoop.date.numero.giorni.indietro.rispetto.sys.date = 2

incoerenzaGDM.numberOfDays.threshold = 5