output.db=eng_test
rcuGasMassivo.tableName=rcugas_massivo_p
rcuGasConnessioniDistr2.tableName=rcugas_connessioni_distr2_p
rcuGasVarMisuratore.tableName=rcugas_var_misuratore_p
rcuGasVarConvertitore.tableName=rcugas_var_convertitore_p

rootpath=/user/hive/warehouse/acquirente_unico/sqoop_portcons

output.rootpath=/user/hive/warehouse/eng_test.db/CDP/freezer

isilon.deploy.path=/home/eng_test/cdp/freezer
hdfs.deploy.path=/user/eng_test/cdp/freezer/deploy