input.table.freezer=RCUGASMASSIVOTECH
freeze_date=2021-07-01

agg.rcuGasMassivo.parquetPath=${rootpath}/RCUGAS.RCUGAS_MASSIVO_p
agg.rcuGasConnessioniDistr2.parquetPath=${rootpath}/RCUGAS.RCUGAS_CONNESSIONI_DISTR2_p
agg.rcuGasVarMisurratore.parquetPath=${rootpath}/RCUGAS.RCUGAS_VAR_MISURATORE_p
agg.rcuGasVarConvertitore.parquetPath=${rootpath}/RCUGAS.RCUGAS_VAR_CONVERTITORE_p

hdfs.output.rcugas_massivo_freeze=${output.rootpath}/rcugas_massivo_ca_p_freeze
hdfs.output.rcugas_tech_freeze=${output.rootpath}/rcugas_tech_ca_p_freeze

rcugasMassivo.tableName=${output.db}.rcugas_massivo_ca_p_freeze
rcugasTech.tableName=${output.db}.rcugas_tech_ca_p_freeze

session=CCG_FIN