include "ammissibilita.conf"

rootPath="${root.path}"
tempRootPath ="${temp.path}"
tempRootPathOld ="${temp.path.old}"
timeZone="Europe/Rome"
hive {
  db {
    cmg_gas="${hive.cmg_gas}"
    rcu="${hive.rcu}"
    rcugas="${hive.rcugas}"
  }
  table {
    rcuAziendaP=${hive.db.rcu}".rcu_azienda_p"
    rcugasUDDP=${hive.db.rcugas}".rcugas_udd_p"
    ammissibilitaFile=${hive.db.cmg_gas}".report_ammissibilita_file_gas"
    unzipLog=${hive.db.cmg_gas}".report_decompressione"
    flowLog = ${hive.db.cmg_gas}".report_ingestion"
    ammissibilitaPdr=${hive.db.cmg_gas}".report_ammissibilita_pdr"
    rcuGasPdr=${hive.db.rcugas}".rcugas_pdr_p"
    rcuGasPdrStato=${hive.db.rcugas}".rcugas_pdr_stato_p"
    checkSqoop="${sqoop.check}"
  }
}

ammissibilita {
  fileMaxLength=5242880
  standard {
    path="${ammissibilita.standard.path}"
  }

  igmg {
    path="${ammissibilita.igmg.path}"
  }

  igmr {
    path="${ammissibilita.igmr.path}"
  }

  xsd {
    path="${xsd.path}"
    periodico=${ammissibilita.xsd.path}"/standard/FlussiDatiMisuraPrelievoGAS-Flusso1-Periodici.xsd"
    rettifica=${ammissibilita.xsd.path}"/standard/FlussiDatiMisuraPrelievoGAS-Flusso2-Rettifica.xsd"
    igmg=${ammissibilita.xsd.path}"/igmg/FlussiDatiInterventoGruppoMisGAS-IGMG.xsd"
    igmr=${ammissibilita.xsd.path}"/igmr/FlussiDatiInterventoGruppoMisGAS-IGMR.xsd"
  }
}

unzip {
  inputPath="${unzip.input.path}"
}

fileRecovery {
  path="${hdfs.recovery.path}/file_recovery_list.csv"
}