include "ammissibilita.conf"

rootPath="${root.path}"
syncRoot="${sync.root}"

hive{
  db {
    rcu="${hive.rcu}"
    au="${hive.au}"
    rcus="${hive.rcus}"
  }
  table {
    ammissibilitaFile=${hive.db.au}".${hive.table.report_ammissibilita_file}"
    ammissibilitaPod=${hive.db.au}".report_ammissibilita_pod"
    rcuAziendaP=${hive.db.rcu}".rcu_azienda_p"
    rcuUDDP=${hive.db.rcu}".RCU_UDD_P"
    reportDecompressione = ${hive.db.au}".${hive.table.report_decompressione_elt}"
    rcuPodDistrP=${hive.db.rcu}".rcu_pod_distr_p"
    rcuDistrP=${hive.db.rcu}".RCU_DISTR_P"
    rcuEmtP=${hive.db.rcu}".RCU_EMT_P"
    rcuPodP=${hive.db.rcu}".rcu_pod_p"
    rcuPodUddP=${hive.db.rcu}".rcu_pod_udd_p"
    rcusUddP=${hive.db.rcus}".rcus_udd_p"
    rcusPodUddP=${hive.db.rcus}".rcus_pod_udd_p"
    rcusPodP=${hive.db.rcus}".rcus_pod_p"
    rcusPodDistrP=${hive.db.rcus}".rcus_pod_distr_p"
  }
}


tmp{
  1GAmmissibilita=${rootPath}"${tmp1G.path}"
  2GAmmissibilita=${rootPath}"${tmp2G.path}"
}

output {
  1GAmmissibilita=${syncRoot}"${sync.1g}"
  2GAmmissibilita=${syncRoot}"${sync.2g}"
  ammissibilitaPodFileMaxLength=100000000
}

xsd {
  pathXdsEE=${rootPath}"/XSD_EE"
  periodico=${xsd.pathXdsEE}"/FlussiDatiMisuraPrelievoEE-Flusso1-Periodico.xsd"
  rettifica=${xsd.pathXdsEE}"/FlussiDatiMisuraPrelievoEE-Flusso2-Rettifica.xsd"

  pathXdsSMIS=${rootPath}"/XSD_SMIS"
  smis=${xsd.pathXdsSMIS}"/FlussiDatiMisuraPrelievoEE-Flusso1-RiprogrSostMisuratore.xsd"
}

