deploy.path.local = /home/eng_test/portale_consumi/dev/common/job
deploy.path.logs = /home/eng_test/portale_consumi/dev/common/logs

mongo.params.hdfs = /user/eng_test/portale_consumi/dev/gas/params.properties

mongo.table.audit_elettrico = AuditElettrico2
mongo.table.audit_gas = AuditGas2
