deploy.path.local = /home/eng_test/portale_consumi/prod/common/job
deploy.path.logs = /mnt/isilonshare1/Software_1/schedulazioni/GAS/logs/portale_consumi_pulizia_audit

mongo.params.hdfs = /user/eng_test/portale_consumi/prod/gas/params.properties

mongo.table.audit_elettrico = AuditElettrico
mongo.table.audit_gas = AuditGas
