# ISILON
root.path=/mnt/nfs
output.path=${root.path}/isilonshare1/ee-switching/generazione-file
logs.root.path=${root.path}/isilonshare1/ee-switching/logs

# DEPLOY HDFS
hdfs.user=development
hdfs.deploy.path=/user/${hdfs.user}/deploy
hdfs.hive.site.path=/user/${hdfs.user}/hive-site.xml

# SPARK
#deploy.mode=cluster TODO change after first tests
deploy.mode=client
spark.num.executors=2
spark.executor.cores=1
spark.executor.memory=1G
spark.driver.memory=1G

# HIVE
hive.db=flussi_switching_ee
hive.au.db=au
hive.jdbc.url=jdbc:hive2://au-m01:10000
hive.jdbc.user=development

# XML
xml.maxNPods.funzionali=3000
xml.maxNPods.storici=30
xml.xsd.path=${root.path}/isilonshare1/ee-switching/xsd

# SQOOP
sqoop.num.mappers=1
sqoop.properties.hdfs.path=/apps/deploy/sqoop.properties
sqoop.hive.db.dir=/user/hive/warehouse/flussi_switching_ee.db
sqoop.null.character=
sqoop.cat.command=hdfs dfs -cat

# OOZIE
wf.uuid=2490c39d-f6ad-a61c-2e77-5e7ea2d48cc8
coord.uuid=04b3b0d1-c532-7b3c-129a-39387f202945
parentDir.uuid=f1cd5f93-e4b5-41e6-86b7-cbda5e3537ae
