agg.dailyConsumption.tableName=${agg.db}.${dailyConsumption.tableName}
agg.dailyConsumption.executionid=1624261923745

rcugas.sospensioni.tableName=${rcugas.db}.${rcugas.sospensioni.tableName}
rcugas.pdr.tableName=${rcugas.db}.${rcugas.pdr.tableName}
rcugas.varMisuratore.tableName=${rcugas.db}.rcugas_var_misuratore_p
rcugas.remiAnagrafica.tableName=${rcugas.db}.rcugas_remi_anagrafica_p
rcugas.gestTrasporto.tableName=${rcugas.db}.rcugas_gesttrasporto_p
rcugas.vIt.tableName=${rcugas.db}.v_rcugas_it_p
rcugas.connDistr2.tableName=${rcugas.db}.rcugas_connessioni_distr2_p

agg.validateFlow.tableName=${agg.db}.${validateFlows.tableName}

hdfs.output.aggregato=${hdfs.basePath}/query_aggregato
hdfs.output.esclusi=${hdfs.basePath}/query_esclusi
hdfs.output.elencoFlussiDettaglioEsclusi=${hdfs.basePath}/query_elenco_flussi_dettaglio_esclusi
hdfs.output.incoerenti=${hdfs.basePath}/query_incoerenti
hdfs.output.pdrDettaglioIncoerenti=${hdfs.basePath}/query_pdr_dettaglio_incoerenti
hdfs.output.elencoFlussiDettaglioIncoerenti=${hdfs.basePath}/query_elenco_flussi_dettaglio_incoerenti
hdfs.output.sospesi=${hdfs.basePath}/query_sospesi
hdfs.output.pdrDettaglioUnico=${hdfs.basePath}/query_pdr_dettaglio_unico
hdfs.output.elencoFlussoDettaglioUnico=${hdfs.basePath}/query_elenco_flussi_dettaglio_unico
hdfs.output.pdrDettaglioDeltaNegativo=${hdfs.basePath}/query_pdr_dettaglio_delta_negativo
hdfs.output.elencoFlussiDettaglioDeltaNegativo=${hdfs.basePath}/query_elenco_flussi_dettaglio_delta_negativo
hdfs.output.pdrDettaglioGiroContatore=${hdfs.basePath}/query_pdr_dettaglio_giro_contatore
hdfs.output.elencoFlussiDettaglioGiroContatore=${hdfs.basePath}/query_elenco_flussi_dettaglio_giro_contatore

aggregato.tableName=${agg.db}.query_aggregato
esclusi.tableName=${agg.db}.query_esclusi
elencoFlussiDettaglioEsclusi.tableName=${agg.db}.query_elenco_flussi_dettaglio_esclusi
incoerenti.tableName=${agg.db}.query_incoerenti
pdrDettaglioIncoerenti.tableName=${agg.db}.query_pdr_dettaglio_incoerenti_sbg
elencoFlussiDettaglioIncoerenti.tableName=${agg.db}.query_elenco_flussi_dettaglio_incoerenti_sbg
sospesi.tableName=${agg.db}.query_sospesi
pdrDettaglioUnico.tableName=${agg.db}.query_pdr_dettaglio_unico
elencoFlussiDettaglioUnico.tableName=${agg.db}.query_elenco_flussi_dettaglio_unico
pdrDettaglioDeltaNegativo.tableName=${agg.db}.query_dettaglio_delta_negativo
elencoFlussiDettaglioDeltaNegativo.tableName=${agg.db}.query_elenco_flussi_dettaglio_delta_negativo
pdrDettaglioGiroContatore.tableName=${agg.db}.query_dettaglio_giro_contatore
elencoFlussiDettaglioGiroContatore.tableName=${agg.db}.query_elenco_flussi_dettaglio_giro_contatore

# Utilizzato per la sterilizzazione degli incoerenti
class.group.measure.range.max.path=${aggregazione.sbg.hdfs.path}/gruppo_mis_limit.csv
incoerenzaGDM.numberOfDays.threshold=5

properties.mode=true
query.to.run=aggregato, esclusi, incoerenti, dettaglioIncoerenti, dettaglioUnico, sospesi