# ISILON
root.path=/mnt/nfs
temp.path=${root.path}/isilonshare1/isilonshare_gas_std
temp.path.old=${root.path}/isilonshare1/isilonshare_gas
unzip.input.path=${root.path}/isilonshare_gas
xsd.path=${root.path}/xsd/gas
logs.root.path=/mnt/nfs/logs/ingestion-misure-gas-unico
ammissibilita.standard.path=${root.path}/isilonshare1/TMG_SYNC_Paral
ammissibilita.igmg.path=${root.path}/isilonshare1/TMG_SYNC_Paral
ammissibilita.igmr.path=${root.path}/isilonshare1/TMG_SYNC_Paral

# DEPLOY
deploy.path=/home/development/gas

# SPARK
deploy.mode=client
spark.num.executors=2
spark.executor.cores=2
spark.executor.memory=4G
spark.driver.memory=1G
ingestion.deploy.mode=client
ingestion.spark.num.executors=2
ingestion.spark.executor.cores=2
ingestion.spark.executor.memory=4G

# HIVE
hive.cmg_gas=cmg_gas
hive.rcu=eng_test
hive.rcugas=eng_test
hive.userneame.permission=sii_misure_gas


# LOG
decompressione.log.name=decompressione.log

# SQOOP
sqoop.num.mappers=1
sqoop.properties.hdfs.path=/apps/deploy/sqoop.properties
sqoop.export.dir=/user/hive/warehouse/prod_orig/prt_cmg_igmg_export
sqoop.export.igmr.dir=/user/hive/warehouse/prod_orig/prt_cmg_igmr_export
sqoop.export.table=flusso_misure_igmg
sqoop.staging.table=flusso_misure_igmg_staging
sqoop.null.character=
sqoop.cat.command=hdfs dfs -cat
sqoop.check=false

# MERGE REPORT
merge.report.base.path=${root.path}/isilonshare1/TMG_SYNC_Paral
merge.report.dest.path=${root.path}/TMG_SYNC_Paral
merge.report.processes=2
merge.report.tracking.folder=/tmp/report_ammissibilita_gas_tracking_folder