#sqoop tables properties
hive.sgs.db=sgs
hive.sgsPerimetroSwgSRawCPath=/user/hive/warehouse/sgs.db/sqoop/sgs_perimetro_swg_s_raw_c
hive.sgsPerimetroSwgARawCPath=/user/hive/warehouse/sgs.db/sqoop/sgs_perimetro_swg_a_raw_c
hive.sgsPerimetroUigSRawCPath=/user/hive/warehouse/sgs.db/sqoop/sgs_perimetro_uig_s_raw_c
hive.sgsPerimetroUigARawCPath=/user/hive/warehouse/sgs.db/sqoop/sgs_perimetro_uig_a_raw_c
hive.sgsPerimetroVtgSRawCPath=/user/hive/warehouse/sgs.db/sqoop/sgs_perimetro_vtg_s_raw_c

connection.string.oracle = /apps/deploy/job.properties

deploy.path.hdfs = /apps/sgs/deploy
sgs.path.hdfs = /user/hive/warehouse/sgs.db
deploy.path = /home/sii_misure_gas/sgs/deploy

xml.output.path = /mnt/Settlement/TDG
sqoop.import.path = /user/hive/warehouse/sgs.db/sqoop