db.output.path = eng_test
agg.output.rootpath=/user/eng_test/agg
deploy.path = /home/eng_test/agg/test
deploy.path.hdfs = /user/eng_test/agg/deploy
deploy.path.strong.exclusion = /user/eng_test/agg/deploy
strong.exclusion.backuptable.basepath = /user/eng_test/agg/deploy/backup_strong_exclusion_filter