# Recovery csv path containing piva_udd, piva_distr to recover
recovery.csv.path=${hdfs.deploy.path}/recovery.csv

# Integer
tgl.dayOfMonth.threshold=7

# Used for automation
monthDifference.timeBack=2m

# enable/disable rules
om1.isEnabled=true
om2.isEnabled=true
om3.isEnabled=true

# Float percentage
# OM2: lowerBound and upperBound are included (om2.lowerBound <= x <= om2.upperBound)
# OM3: lowerBound is included, upperBound is not (om3.lowerBound <= x < om3.upperBound)
om2.lowerBound=100.0
om2.upperBound=100.0
om3.lowerBound=30.0
om3.upperBound=100.0
om1.target.percent=98.0
om2.target.percent=75.0
om3.target.percent=15.0
# Float euro
om1.euro.fee=35.0
om2.euro.fee=36.0
om3.euro.fee=12.0

# Tgl table
flow.dataset.tgl.tableName=${flow.dataset.tgl.tableName}

# Rcu/Rcugas tables
rcugasMassivoP.basepath=${rcugasMassivoP.basepath}
rcugasVarMisuratoreP.baepath=${rcugasVarMisuratoreP.baepath}
rcugasFornituraP.basepath=${rcugasFornituraP.basepath}
rcugasUdd.basepath=${rcugasUdd.basepath}
rcugasConnessioniDistr2.basepath=${rcugasConnessioniDistr2.basepath}
rcugasSospensioni.basepath=${rcugasSospensioni.basepath}
rcuGasVarTrattamentoP.basepath=${rcuGasVarTrattamentoP.basepath}
rcuAzienda.basepath=${rcuAzienda.basepath}

# Output tables
aggregatoTotale.tableName=${cig.db}.${aggregatoTotale.tableName}
aggregatoTotale.basepath=${aggregatoTotale.basepath}
pdrTotale.tableName=${cig.db}.${pdrTotale.tableName}
pdrTotale.basepath=${pdrTotale.basepath}
dettaglioPdr.tableName=${cig.db}.${dettaglioPdr.tableName}
dettaglioPdr.basepath=${dettaglioPdr.basepath}
dettaglioOM1.tableName=${cig.db}.${dettaglioOM1.tableName}
dettaglioOM1.basepath=${dettaglioOM1.basepath}
dettaglioOM2.tableName=${cig.db}.${dettaglioOM2.tableName}
dettaglioOM2.basepath=${dettaglioOM2.basepath}
dettaglioOM3.tableName=${cig.db}.${dettaglioOM3.tableName}
dettaglioOM3.basepath=${dettaglioOM3.basepath}

# Filter pdr/file
filter.exclusion.enabled=false
filter.exclusion.file.path=${hdfs.deploy.path}/exclusion.csv

# Filter duplicate measures
filter.duplicateMeasures.enable=true
filter.duplicateMeasures.groupByFilePath.enable=true
filter.duplicateMeasures.groupByTimestamp.enable=true
filter.duplicateMeasures.groupByFileName.enable=true