# ISILON
root.path=/mnt
output.path=${root.path}/isilonshare1/Software/ee-switching/generazione-file
logs.root.path=${root.path}/isilonshare1/Software/ee-switching/logs

# DEPLOY HDFS
hdfs.user=sii_misure
hdfs.deploy.path=/user/${hdfs.user}/Software/ee-switching/deploy
hdfs.hive.site.path=/user/${hdfs.user}/Software/ee-switching/hive-site.xml

# SPARK
deploy.mode=cluster
spark.num.executors=40
spark.executor.cores=5
spark.executor.memory=45G
spark.driver.memory=5G

# HIVE
hive.db=flussi_switching_ee
hive.au.db=au
hive.jdbc.url=jdbc:hive2://dmphclo07:10000
hive.jdbc.user=sii_misure

# XML
xml.maxNPods.funzionali=3000
xml.maxNPods.storici=30
xml.xsd.path=${root.path}/isilonshare1/Software/ee-switching/xsd

# SQOOP
sqoop.num.mappers=15
sqoop.properties.hdfs.path=/apps/deploy/job.properties
sqoop.hive.db.dir=/user/hive/warehouse/flussi_switching_ee.db
sqoop.null.character=\\\\N
sqoop.cat.command=hdfs dfs -cat

# OOZIE
wf.uuid=2490c39d-f6ad-a61c-2e77-5e7ea2d48cd9
coord.uuid=04b3b0d1-c532-7b3c-129a-39387f202944
parentDir.uuid=25031d6f-5190-434a-927a-e7a93c154d7a
