deploy.path = /mnt/isilonshare1/Software_1/cce/deploy
logs.root.path= /mnt/isilonshare1/Software_1/cce/logs

au_db = au
rcu_db = rcu
rcus_db = rcus
cce_db = cce
ate_db = ate

# Hive tables
hive.input.flussoMisureEstensioneQuarti.path = /user/hive/warehouse/${au_db}.db/misure_ee_au/flusso_misure_estensione_quarti
hive.input.flussoMisureEstensioneQuarti.table = ${au_db}.flusso_misure_estensione_quarti
hive.input.flussoMisureQuarti.path = /user/hive/warehouse/${au_db}.db/misure_ee_au/flusso_misure_quarti
hive.input.flussoMisureQuarti.table = ${au_db}.flusso_misure_quarti
hive.input.flussoMisureEstensioneQuartiIn.path = /user/hive/warehouse/${au_db}.db/flusso_misure_estensione_quarti_in
hive.input.flussoMisureEstensioneQuartiIn.table = ${au_db}.flusso_misure_estensione_quarti_in
hive.input.flussoMisureQuartiIn.path = /user/hive/warehouse/${au_db}.db/flusso_misure_quarti_in
hive.input.flussoMisureQuartiIn.table = ${au_db}.flusso_misure_quarti_in

hive.input.reportAmmissibilitaPod.path = /user/hive/warehouse/ate.db/report_ammissibilita_pod_partbloc
hive.input.reportAmmissibilitaPod.table = ${ate_db}.report_ammissibilita_pod_partbloc
hive.input.reportAmmissibilitaFile.path = /user/hive/warehouse/ate.db/report_ammissibilita_file_ee_partbloc
hive.input.reportAmmissibilitaFile.table = ${ate_db}.report_ammissibilita_file_ee_partbloc

hive.input.rcuAziendaP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_AZIENDA_p
hive.input.rcuAziendaP.table = ${rcu_db}.rcu_azienda_p
hive.input.rcuFornituraP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_FORNITURA_p
hive.input.rcuFornituraP.table = ${rcu_db}.rcu_fornitura_p
hive.input.rcuPodDistrP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_POD_DISTR_p
hive.input.rcuPodDistrP.table = ${rcu_db}.rcu_pod_distr_p
hive.input.rcuPodMisureP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_POD_MISURE_p
hive.input.rcuPodMisureP.table = ${rcu_db}.rcu_pod_misure_p
hive.input.rcuPodP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_POD_p
hive.input.rcuPodP.table = ${rcu_db}.rcu_pod_p
hive.input.rcuPodTecnP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/${rcu_db}.rcu_pod_tecn_p
hive.input.rcuPodTecnP.table = ${rcu_db}.rcu_pod_tecn_p
hive.input.rcuPodUddP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_POD_UDD_p
hive.input.rcuPodUddP.table = ${rcu_db}.rcu_pod_udd_p
hive.input.rcuTariffaP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/rcu.rcu_tariffa_p
hive.input.rcuTariffaP.table = ${rcu_db}.rcu_tariffa_p
hive.input.rcuUddP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_UDD_p
hive.input.rcuUddP.table = ${rcu_db}.rcu_udd_p

hive.input.rcusFornituraP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUS.RCUS_FORNITURA_p
hive.input.rcusFornituraP.table = ${rcus_db}.rcus_fornitura_p
hive.input.rcusPodMisureP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUS.RCUS_PODMISURE_p
hive.input.rcusPodMisureP.table = ${rcus_db}.rcus_podmisure_p
hive.input.rcusPodP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUS.RCUS_POD_p
hive.input.rcusPodP.table = ${rcus_db}.rcus_pod_p
hive.input.rcusPodUddP.path = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUS.RCUS_POD_UDD_p
hive.input.rcusPodUddP.table = ${rcus_db}.rcus_pod_udd_p

hive.input.ghigliottina.path = /user/hive/warehouse/${au_db}.db/data_ghigliottina
hive.input.ghigliottina.table = ${au_db}.data_ghigliottina

hive.output.cceMoAnnullate1g.path = /user/hive/warehouse/${cce_db}.db/cce_mo_annullate_1g
hive.output.cceMoAnnullate1g.table = ${cce_db}.cce_mo_annullate_1g
hive.output.cceMoAnnullate2g.path = /user/hive/warehouse/${cce_db}.db/cce_mo_annullate_2g
hive.output.cceMoAnnullate2g.table = ${cce_db}.cce_mo_annullate_2g
hive.output.cceMoAnnullate1gEin.path = /user/hive/warehouse/${cce_db}.db/cce_mo_annullate_1g_ein
hive.output.cceMoAnnullate1gEin.table = ${cce_db}.cce_mo_annullate_1g_ein
hive.output.cceMoAnnullate2gEin.path = /user/hive/warehouse/${cce_db}.db/cce_mo_annullate_2g_ein
hive.output.cceMoAnnullate2gEin.table = ${cce_db}.cce_mo_annullate_2g_ein

hive.output.cceCalcoloAnagrafica.path = /user/hive/warehouse/${cce_db}.db/cce_calcolo_anag
hive.output.cceCalcoloAnagrafica.table = ${cce_db}.cce_calcolo_anag
hive.output.cceCalcoloP.path = /user/hive/warehouse/${cce_db}.db/cce_calcolo_p
hive.output.cceCalcoloP.table = ${cce_db}.cce_calcolo_p
hive.output.cceCalcoloPein.path = /user/hive/warehouse/${cce_db}.db/cce_calcolo_p_ein
hive.output.cceCalcoloPein.table = ${cce_db}.cce_calcolo_p_ein
hive.output.cceCalcoloPR.path = /user/hive/warehouse/${cce_db}.db/cce_calcolo_pr
hive.output.cceCalcoloPR.table = ${cce_db}.cce_calcolo_pr
hive.output.cceCalcoloPRein.path = /user/hive/warehouse/${cce_db}.db/cce_calcolo_pr_ein
hive.output.cceCalcoloPRein.table = ${cce_db}.cce_calcolo_pr_ein
hive.output.cceCalcoloTrattamento.path = /user/hive/warehouse/${cce_db}.db/cce_calcolo_trattamento
hive.output.cceCalcoloTrattamento.table = ${cce_db}.cce_calcolo_trattamento
hive.output.cceCalcTrack.path = /user/hive/warehouse/${cce_db}.db/cce_calc_track
hive.output.cceCalcTrack.table = ${cce_db}.cce_calc_track