gse.perimetro_er_ee.tablename=${gse.db}.gse_perimetro_er_ee
gse.richiesta_er_m.tablename=${gse.db}.gse_richiesta_er_m
dwh_consumi.mensile.tablename=${dataman.db}.dwh_consumi_ee_tb
gse.gse_aggr_m.tablename=${gse.db}.gse_aggr_m
gse.gse_aggr_m.basepath=${hdfs.output.path}/gse_aggr_m
gse.gse_aggr_m_export.tablename=${gse.db}/gse_aggr_m_export
gse.gse_aggr_m_expor.basepath=${hdfs.output.path}/gse_aggr_m_export