deploy.path.local = /home/eng_test/portale_consumi/prod/gas/job
deploy.path.logs = /mnt/isilonshare1/Software_1/schedulazioni/GAS/logs/portale_consumi
deploy.path.hdfs = /user/eng_test/portale_consumi/prod/gas

# User per lancio script hive
system.user = eng_test

params.job.days_interval_max = 1126
params.job.months_interval_max = 36
params.job.months_interval_split = 3
params.mongodb.max_doc_delta_forniture = 2000000
params.mongodb.max_doc_delta_misure = 2000000

#FORNITURE
hive.table.rcugas_clientefinale_p = rcugas.rcugas_clientefinale_p
hive.table.rcugas_connessioni_distr_p = rcugas.rcugas_connessioni_distr_p
hive.table.rcugas_fornitura_p = rcugas.rcugas_fornitura_p
hive.table.rcugas_indirizzi_p = rcugas.rcugas_indirizzi_p
hive.table.rcugas_pdr_datiprelievo_p = rcugas.rcugas_pdr_datiprelievo_p
hive.table.rcugas_pdr_misuratore_p = rcugas.rcugas_pdr_misuratore_p
hive.table.rcugas_pdr_p = rcugas.rcugas_pdr_p
hive.table.rcugas_residenza_p = rcugas.rcugas_residenza_p
hive.table.rcugas_venditore_p = rcugas.rcugas_venditore_p
hive.table.v_rcugas_distributore_p = rcugas.v_rcugas_distributore_p
hive.table.v_rcu_azienda_p = rcu.v_rcu_azienda_p
hive.table.switch_gas_prt_swg_p = switch_gas.prt_swg_p
hive.table.tdg_vuln_p = tdg.tdg_vuln_p
hive.table.rcugas_codice_offerta_p = rcugas.rcugas_codice_offerta_p
#MISURE
hive.table.cmg_gas_prt_cmg_rgl_p = cmg_gas.prt_cmg_rgl_p
hive.table.cmg_gas_prt_cmg_rml_p = cmg_gas.prt_cmg_rml_p
hive.table.cmg_gas_prt_cmg_rmv_p = cmg_gas.prt_cmg_rmv_p
hive.table.cmg_gas_prt_cmg_tal_p = cmg_gas.prt_cmg_tal_p
hive.table.cmg_gas_prt_cmg_tav_p = cmg_gas.prt_cmg_tav_p
hive.table.cmg_gas_prt_cmg_tgl_p = cmg_gas.prt_cmg_tgl_p
hive.table.cmg_gas_prt_cmg_tml_p = cmg_gas.prt_cmg_tml_p
hive.table.switch_gas_prt_vtg6_p = switch_gas.prt_vtg6_p

hive.table.forniture_processi_gas = misuregas.forniture_processi_gas
hive.table.forniture_misure_gas = misuregas.forniture_misure_gas
hive.table.misure_storic_f2 = misuregas.misure_storic_f2
hive.table.misure_data_calcolo = misuregas.misure_data_calcolo

#mongodb.client.uri = mongodb://pdc:-Zv1xWJAn6ECTJyh7H8C@172.16.16.71:27017,172.16.16.72:27017,172.16.16.73:27017
#mongodb.db.uri = mongodb://pdc:-Zv1xWJAn6ECTJyh7H8C@172.16.16.71:27017,172.16.16.72:27017,172.16.16.73:27017/Forniture.FornitureElettriche_2?replicaSet=rset&authSource=Forniture
mongodb.client.uri = mongodb://pdc:-Zv1xWJAn6ECTJyh7H8C@prodmongodb-01.siiau.local:27017,prodmongodb-02.siiau.local:27017,prodmongodb-03.siiau.local:27017
mongodb.db.uri = mongodb://pdc:-Zv1xWJAn6ECTJyh7H8C@prodmongodb-01.siiau.local:27017/Forniture.FornitureElettriche_2?replicaSet=rset&authSource=Forniture,prodmongodb-02.siiau.local:27017/Forniture.FornitureElettriche_2?replicaSet=rset&authSource=Forniture,prodmongodb-03.siiau.local:27017/Forniture.FornitureElettriche_2?replicaSet=rset&authSource=Forniture
mongodb.db.name = Forniture
mongodb.collection.fornitureGas = FornitureGas
mongodb.collection.misureGas33m = MisureGas33M
mongodb.collection.misureGas3m = MisureGas3M
mongodb.conf.readPreference = secondaryPreferred
mongodb.conf.writeConcern = majority
