package it.eng.au.portaleConsumi.model.hive.cmg_gas

import java.sql.Timestamp

case class PrtCmgTavPModel(
                            n_id_file: String = null,
                            t_name_file: String = null,
                            annomese_riferimento: String = null,
                            cod_servizio: String = null,
                            cod_flusso: String = null,
                            d_caricamento: Timestamp = null,
                            cod_pdr: String = null,
                            matr_mis: String = null,
                            matr_conv: String = null,
                            data_com_autolet_cf: Timestamp = null,
                            let_tot_prel: Integer = null,
                            let_tot_conv: String = null,
                            esito_val: String = null,
                            note: String = null,
                            anno: String = null,
                            mese: String = null,
                            piva_distr: String = null,
                            piva_utente: String = null,
                            local_file: String = null,
                            mese_comp: String = null,
                            data_prest: String = null,
                            codprat_sii: String = null,
                            trattamento: String = null,
                            n_cifre_mis: String = null,
                            n_cifre_conv: String = null,
                            coeff_corr: String = null,
                            freq_let: String = null,
                            acc_mis: String = null,
                            raccolta: String = null,
                            esito_raccolta: String = null,
                            causa_manc_raccolta: String = null,
                            mod_alt_racc: String = null,
                            dir_indennizzo: String = null,
                            pros_fin_inizio: String = null,
                            pros_fin_fine: String = null,
                            vol_annuo_sost: String = null,
                            classe_gruppo_mis: String = null,
                            pre_conv: String = null,
                            gruppo_mis_int: String = null,
                            tipo_lettura: String = null,
                            num_tentativi: String = null,
                            data_racc: String = null,
                            data_mis_eff: String = null,
                            segn_mis_eff: String = null,
                            segn_conv_eff: String = null,
                            ammissibilita: String = null,
                            annomese: String = null
                          )
