spark.app.energia_residuale_pariziale.paramentro.area=${spark.app.energia_residuale_pariziale.paramentro.area}
spark.app.energia_residuale_pariziale.paramentro.annomese=${spark.app.energia_residuale_pariziale.paramentro.annomese}
spark.app.energia_residuale_pariziale.paramentro.singola_piva_distributore=${spark.app.energia_residuale_pariziale.paramentro.singola_piva_distributore}
spark.app.energia_residuale_pariziale.paramentro.dati_output_path=${spark.app.energia_residuale_pariziale.paramentro.dati_output_path}
spark.app.energia_residuale_pariziale.paramentro.piva_esclusa=${spark.app.energia_residuale_pariziale.paramentro.piva_esclusa}
