package it.eng.au.ERP.model.erp

case class ErpAggregatoO2Model(
                            joinModel: String = null,
                            q51: Double = 0.0,
                            q52: Double = 0.0,
                            q53: Double = 0.0,
                            q54: Double = 0.0,
                            q55: Double = 0.0,
                            q56: Double = 0.0,
                            q57: Double = 0.0,
                            q58: Double = 0.0,
                            q59: Double = 0.0,
                            q60: Double = 0.0,
                            q61: Double = 0.0,
                            q62: Double = 0.0,
                            q63: Double = 0.0,
                            q64: Double = 0.0,
                            q65: Double = 0.0,
                            q66: Double = 0.0,
                            q67: Double = 0.0,
                            q68: Double = 0.0,
                            q69: Double = 0.0,
                            q70: Double = 0.0,
                            q71: Double = 0.0,
                            q72: Double = 0.0,
                            q73: Double = 0.0,
                            q74: Double = 0.0,
                            q75: Double = 0.0,
                            q76: Double = 0.0,
                            q77: Double = 0.0,
                            q78: Double = 0.0,
                            q79: Double = 0.0,
                            q80: Double = 0.0,
                            q81: Double = 0.0,
                            q82: Double = 0.0,
                            q83: Double = 0.0,
                            q84: Double = 0.0,
                            q85: Double = 0.0,
                            q86: Double = 0.0,
                            q87: Double = 0.0,
                            q88: Double = 0.0,
                            q89: Double = 0.0,
                            q90: Double = 0.0,
                            q91: Double = 0.0,
                            q92: Double = 0.0,
                            q93: Double = 0.0,
                            q94: Double = 0.0,
                            q95: Double = 0.0,
                            q96: Double = 0.0,
                            q97: Double = 0.0,
                            q98: Double = 0.0,
                            q99: Double = 0.0,
                            q100: Double = 0.0,
                            tipo_flusso: String =  null,
                            executiond: String = null

                              )
