isilon.basepath.tmp = ${isilon.basepath.tmp}
isilon.basepath.out =${isilon.basepath.out}

class.group.measure.range.max.path=${deploy.path.hdfs}/gruppo_mis_limit.csv
rcugas.varMisuratore.tableName=${rcugas.db}.rcugas_var_misuratore_p
rcugas.pdr.tableName=${rcugas.db}.rcugas_pdr_p
incoerenzaGDM.numberOfDays.threshold=5

agg.consumption.tableName = ${agg.db}.daily_consumption_agg
agg.consumption.incoerenti.tableName = ${agg.db}.daily_consumption_agg_incoerenti
agg.consumption.esclusi.tableName = ${agg.db}.daily_consumption_agg_esclusi
agg.validate.tableName = ${agg.db}.validated_flows_agg

sbg.consumption.tableName = ${sbg.db}.daily_consumption_sbg
sbg.validate.tableName = ${sbg.db}.validated_flows_sbg

cdp.consumption.tableName = ${cdp.db}.ca_final
cdp.validate.tableName = ${cdp.db}.validated_flows

request.pdr.tableName = ${ccg.db}.CCG_RICHIESTA_PDR
request.filter.tableName = ${ccg.db}.CCG_RICHIESTA_FILTRO
request.esito.tableName = ${ccg.db}.CCG_ESITO
request.esito.parquet = ${table.path.hdfs}/ccg_esito
request.esito.tableName.export = ${ccg.db}.CCG_ESITO_EXPORT
request.esito.parquet.export = ${table.path.hdfs}/ccg_esito_export

maxDimensionZipFileByte = 100000000
maxNumRowFile = 500000