package it.eng.au.queryReport.schema

import it.eng.au.aggregatoreConsumiCommon.schema.SchemaEnum

object IncoerentiQuerySchema extends SchemaEnum {
  val
  pdr,
  //data,
  piva_distr,
  piva_it,
  piva_udd,
  piva_udb,
  piva_rdb,
  dtg,
  cod_remi,
  prel_annuo_prev,
  id_reg_clim,
  cod_prof_prel_std,
  trattamento,
  tipo_cliente,
  unit_mis_prel,
  prelievo_giorn_1,
  prelievo_giorn_2,
  prelievo_giorn_3,
  prelievo_giorn_4,
  prelievo_giorn_5,
  prelievo_giorn_6,
  prelievo_giorn_7,
  prelievo_giorn_8,
  prelievo_giorn_9,
  prelievo_giorn_10,
  prelievo_giorn_11,
  prelievo_giorn_12,
  prelievo_giorn_13,
  prelievo_giorn_14,
  prelievo_giorn_15,
  prelievo_giorn_16,
  prelievo_giorn_17,
  prelievo_giorn_18,
  prelievo_giorn_19,
  prelievo_giorn_20,
  prelievo_giorn_21,
  prelievo_giorn_22,
  prelievo_giorn_23,
  prelievo_giorn_24,
  prelievo_giorn_25,
  prelievo_giorn_26,
  prelievo_giorn_27,
  prelievo_giorn_28,
  prelievo_giorn_29,
  prelievo_giorn_30,
  prelievo_giorn_31,
  dailyconsumption_executionid,
  executionid
  = Value
}
