package it.eng.au.queryReport.schema

import it.eng.au.aggregatoreConsumiCommon.schema.SchemaEnum

object PdrDettaglioIncoerentiQuerySchema extends SchemaEnum {
  val
  pdr,
  //data,
  piva_distr,
  piva_it,
  piva_udd,
  piva_udb,
  piva_rdb,
  dtg,
  cod_remi,
  prel_annuo_prev,
  id_reg_clim,
  cod_prof_prel_std,
  trattamento,
  tipo_cliente,
  unit_mis_prel,
  classe_gruppo_mis,
  prelievo_aggregato,
  giorno_sterilizzato,
  prelievo_non_sterilizzato_giorn_1,
  prelievo_non_sterilizzato_giorn_2,
  prelievo_non_sterilizzato_giorn_3,
  prelievo_non_sterilizzato_giorn_4,
  prelievo_non_sterilizzato_giorn_5,
  prelievo_non_sterilizzato_giorn_6,
  prelievo_non_sterilizzato_giorn_7,
  prelievo_non_sterilizzato_giorn_8,
  prelievo_non_sterilizzato_giorn_9,
  prelievo_non_sterilizzato_giorn_10,
  prelievo_non_sterilizzato_giorn_11,
  prelievo_non_sterilizzato_giorn_12,
  prelievo_non_sterilizzato_giorn_13,
  prelievo_non_sterilizzato_giorn_14,
  prelievo_non_sterilizzato_giorn_15,
  prelievo_non_sterilizzato_giorn_16,
  prelievo_non_sterilizzato_giorn_17,
  prelievo_non_sterilizzato_giorn_18,
  prelievo_non_sterilizzato_giorn_19,
  prelievo_non_sterilizzato_giorn_20,
  prelievo_non_sterilizzato_giorn_21,
  prelievo_non_sterilizzato_giorn_22,
  prelievo_non_sterilizzato_giorn_23,
  prelievo_non_sterilizzato_giorn_24,
  prelievo_non_sterilizzato_giorn_25,
  prelievo_non_sterilizzato_giorn_26,
  prelievo_non_sterilizzato_giorn_27,
  prelievo_non_sterilizzato_giorn_28,
  prelievo_non_sterilizzato_giorn_29,
  prelievo_non_sterilizzato_giorn_30,
  prelievo_non_sterilizzato_giorn_31,
  sessione,
  annomese,
  dailyconsumption_executionid,
  executionid
  = Value
}
