flow.dataset.rgl.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_rgl_p
flow.dataset.rml.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_rml_p
flow.dataset.rmv.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_rmv_p
flow.dataset.rsl.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_rsl_p
flow.dataset.sw1.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_sw1_p
flow.dataset.tal.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_tal_p
flow.dataset.tav.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_tav_p
flow.dataset.tas.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_tas_p
flow.dataset.tgl.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_tgl_p
flow.dataset.tml.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_tml_p
flow.dataset.tmv.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_tmv_p
flow.dataset.im1.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_im1_p
flow.dataset.a01.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_A01_0150_p
flow.dataset.a40.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_A40_0150_p
flow.dataset.sm1.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_SM1_0150_p
flow.dataset.igmg.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_igmg_p
flow.dataset.igmrpost.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_igmr_p
flow.dataset.igmrpre.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_igmr_p
flow.dataset.m01r.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_m01r_p
flow.dataset.r01r.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_r01r_p
flow.dataset.r40.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_r40_p
flow.dataset.r40r.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_r40r_p
flow.dataset.s02.basePath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_s02_p

weights.basepath=atg.tab_profili_giorn_std_perc

#rcugas_tech.basepath=/user/hive/warehouse/rcugas.db/rcugas_tech_ca_p
#rcugas.basepath=/user/hive/warehouse/rcugas.db/rcugas_massivo_ca_p
rcugas_tech.basepath=/user/hive/warehouse/rcugas.db/rcugas_tech_ca_freeze
rcugas.basepath=/user/hive/warehouse/rcugas.db/rcugas_massivo_ca_freeze
rcugas.massivo.execution_id=1634554684945
tds.basepath=/user/hive/warehouse/settle_gas.db/gas_tds_part
lookup_zonaclimatica.basepath=/user/hive/warehouse/acquirente_unico/sqoop/prt.istat_regione_climatica_p
#rcugas.basepath=/user/hive/warehouse/acquirente_unico/sqoop/RCUGAS.RCUGAS_MASSIVO_p

rcugas_connessioni_distr2_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop/RCUGAS.RCUGAS_CONNESSIONI_DISTR2_p
v_rcugas_distributore_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/rcugas.v_rcugas_distributore_p
rcugas_massivo_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop/RCUGAS.RCUGAS_MASSIVO_p

#Writable-Path
dataset.rootPath=/user/hive/warehouse
validation.dataset.basePath=/user/hive/warehouse/apps/CA/output/validation/executionid=%d
consumption.dataset.basePath=/user/hive/warehouse/apps/CA/output/consumption/executionid=%d
ca.dataset.basePath=/user/hive/warehouse/apps/CA/output/ca/executionid=%d
#DDL LOCATION PATHS PROP
ca.basePath=/user/hive/warehouse/apps/CA/output/ca
consumption.basepath=/user/hive/warehouse/apps/CA/output/consumption
validation.basepath=/user/hive/warehouse/apps/CA/output/validation

dataset.numberPartition=2500

ce.mean.range=5,6,7,9
flow.read.startDate=201810
flow.read.endDate=202005
flow.read.receive.endDate=20201225
#MUST BE OF FORMAT yyyy-MM-dd
tds.read.receive.endDate=2020-12-25
contractContinuity.upperBound.data=2020-07-01

#PDR MASSIVO CONTROLLER
rcugas_massivo__p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_MASSIVO_p
rcugas_connessioni_distr2__p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_CONNESSIONI_DISTR2_p
rcugas_bilanciamento_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_BILANCIAMENTO_p
istat_regione_climatica_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/prt.istat_regione_climatica_p
rcugas_udb_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/rcugas.rcugas_udb_p
rcu_azienda_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/rcu.rcu_azienda_p
gas_tds.basepath=/user/hive/warehouse/settle_gas.db/gas_tds_part
prt_vtg_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/switch_gas.prt_vtg_p
prt_vsg_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/PRT_RCUGAS.PRT_VSG_p
prt_vtg_agg_rcu_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/SWITCH_GAS.PRT_VTG_AGG_RCU_p
prt_vsg_agg_rcu_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/PRT_RCUGAS.PRT_VSG_AGG_RCU_p
ca_pre_final.basepath=/user/hive/warehouse/CA/output/ca_pre_final_v2
ca_final.basepath=/user/hive/warehouse/CA/output/ca_final_v2
ca_final_to_export.basepath= /user/development/test/ca_final_to_export
rcugas.var_trattamento.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_TRATTAMENTO_p
rcugas.rcugas_var_prel_annuo_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_PREL_ANNUO_p
rcugas.rcugas_var_profilo_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_PROFILO_p
rcugas_var_convertitore_p.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_CONVERTITORE_p
#cambiare da eng_test ad acquirente unico:
cod_prof_std_da_tds.basepath=/user/hive/warehouse/eng_test.db/CDP/cod_prof_std_da_dts

#Set ca_final.anno_competenza to this parameter value
pdr_massivo.anno_competenza=2021

#HIVE
hive.db=default

#HADOOP
hadoop_username=development

sqoop.config.path=/apps/deploy/sqoop.properties
sqoop.properties.user=test_user
sqoop.properties.password=test_user
sqoop.properties.jdbc=jdbc:postgresql://au-m01:5432/test_db

#Filter PDR
#Allowed filters:
# - pdr: requires filterPdr.pdr.path set and present on HDFS
# - distributore: requires filterPdr.distributore.path to be set and present on HDFS
# - distr-udd: requires filterPdr.udd.path and filterPdr.distributore.path to be set and present on HDFS
# - distr-udd-udb: requires filterPdr.udb.path, filterPdr.udd.path and filterPdr.distributore.path to be set and present on HDFS
# - oggettoVariazione
# - caricamentoTDS: requires tds.read.receive.endDate (data ghigliottina)
# - noMisure
# - forzatura
# - perimetroAggRic
filterPdr.mode=noFilter
filterPdr.pdr.path=/user/development/home/development/CA/deploy/filterPdrs/pdr.txt
filterPdr.distributore.path=/user/development/home/development/CA/deploy/filterPdrs/distributore.txt
filterPdr.udd.path=/user/development/home/development/CA/deploy/filterPdrs/udd.txt
filterPdr.udb.path=/user/development/home/development/CA/deploy/filterPdrs/udb.txt
filterPdr.forzatura.path=/user/development/home/development/CA/deploy/filterPdrs/pdr_forzatura.csv

filter.duplicateMeasures.enable=true

ignorePdrMeasure.enable=false
ignorePdrMeasure.pdrMeasureFile.path=/user/development/home/development/CA/deploy/filterPdrs/pdrAndMeasureFileToExclude.csv
# In MB
ignorePdrMeasure.broadcast.threshold=50
# Allowed values:
# - AGG_FIN
# - PRE
# - AGG_RIC
# NOTE: no check is done on this field, a value different from allowed ones is specified the tables produced from this
# job might contain inconsistencies.
tipoTrasmissione.value=PRE

#enable to forced valued: true, false
forced.enable = true
#enable to exclusion filter: true, false
exclusion.pdr.filter = true
exclusion.pdr.filter.csv.path=/user/development/home/development/CA/deploy/filterPdrs/exclusion.csv

# REQUIRED FOR DDL CREATION HIVE SCRIPT
oozie.deploy.path=/user/development/home/development/CA/deploy
hdfs.deploy.path.freezer=/user/development/home/development/CA/deploy
