DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_a01r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_a02_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_a02r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_a40r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad2_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad2r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad4r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad5_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad5r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad3_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad3r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_ad4_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_d02r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_igmg_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_m01_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_d01r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_d02_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_r01r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_r40_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_r40r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_m01r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_r01_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_s40_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_s40r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_sm1r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_s02_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_s02r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_v01_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_v01r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_v02_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_v02r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_sm2_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_sm2r_p;
DROP TABLE IF EXISTS ${hiveconf:hive_db}.prt_cmg_igmg_export;

-- DROP TABLE IF EXISTS ${hiveconf:hive_db}.report_ammissibilita_file_gas;
-- DROP TABLE IF EXISTS ${hiveconf:hive_db}.report_ammissibilita_pdr;
-- DROP TABLE IF EXISTS ${hiveconf:hive_db}.report_ingestion;