# HIVE
hive.cmg_ee=cmg_ee
hive.rcu=eng_test
hive.rcus=eng_test
hive.au=eng_test
hive.table.report_decompressione_elt=report_decompressione
hive.table.report_ammissibilita_file=report_ammissibilita_file_ee
hive.table.report_ammissibilita_file_ee_tracking=report_ammissibilita_file_ee_tracking
hive.table.report_ammissibilita_pod_tracking=report_ammissibilita_pod_tracking
hive.table.report_ammissibilita_file_ee_tracking_staging=report_ammissibilita_file_ee_tracking_staging
hive.table.report_ammissibilita_pod_tracking_staging=report_ammissibilita_pod_tracking_staging
hive.location=/user/hive/warehouse/eng_test
hive.rculocation=/user/hive/warehouse/eng_test.db

hive.sqoop.location=/user/hive/warehouse/eng_test.db

# ISILON
root.path=/mnt/nfs/isilonshare1
sync.root=/mnt/nfs
sync.1g=/TME_SYNC_Paral_TMP
sync.2g=/2G_SYNC_Paral_TMP
sync.dest.root=/mnt/nfs
sync.dest.1g=/TME_SYNC_Paral
sync.dest.2g=/2G_SYNC_Paral
tmp1G.path=/TMP_1G/isilonshare1G
tmp2G.path=/TMP_2G/isilonshare
merge.report.tracking.folder=${root.path}/report_ammissibilita_ee_tracking_folder

# DEPLOY
deploy.path=/home/development/ee
deploy.publish_report_script.path=${deploy.path}/bin/publish_reports
schedulazioni.path=/home/eng_test/schedulazioni
schedulazioni.pipeline.path=${schedulazioni.path}/pipeline

# SPARK
deploy.mode=client
spark.num.executors=2
spark.executor.cores=2
spark.executor.memory=4G
spark.driver.cores=2
spark.driver.memory=2g

