package it.au.misure.ingestionMisureGasUnico.utility

object Constants {
  val CSV_REPORT_SEPARATOR = ";"

  val BLOCCANTE = "BLOCCANTE"
  val NON_BLOCCANTE = "NON BLOCCANTE"
  val OK = "OK"

  val COD904="904"
  val COD906 ="906"
  val COD919 ="919"
  val COD10 ="010"
  val COD011 ="011"

  val PDR ="PDR"
  val FILE="File"

  val RCUGAS_PDR_STATO_DATE_TIME_PATTERN = "yyyy-MM-dd HH:mm:ss.S"
  val RCUGAS_PDR_STATO_DATE_TIME_PATTERN_OPTIONAL_MS = "yyyy-MM-dd HH:mm:ss[.S]"
  val CURRENT_TIMESTAMP_PATTERN = "yyyy-MM-dd'T'HH:mm:ss.SSSSSS"
  val CURRENT_TIMESTAMP_PATTERN_T = "T"
  val CURRENT_TIMESTAMP_PATTERN_SPACE = " "
  val JDBC_TIMESTAMP_PATTERN = "yyyy-MM-dd HH:mm:ss"
  val ITALIAN_DATE_PATTERN = "dd/MM/yyyy"
  val ANNOMESE_PATTERN = "yyyyMM"
  val ANNOMESEGIORNO_PATTERN = "yyyyMMdd"

  val ERROR_FILE_STRUCTURE = "Il file non rispetta la struttura prevista "
  val ERROR_FILE_ALREADY_TRANSMITTED ="File già trasmesso"
  val ERROR_MONTH_MISURA = "I dati del file non sono riferiti al mese di riferimento della misura"
  val ERROR_DATA_COMP = "Il valore del campo mese_comp non è coerente con il valore della data_comp"
  val ERROR_DATA_RACC = "Il valore del campo mese_comp non è coerente con il valore della data_racc"
  val ERROR_COEFF_CORR = "Il campo coeff_corr non è coerente"
  val MANDATORY_FIELDS_ERROR = "I campi obbligatori non sono stati compilati o non sono stati correttamente compilati "
  val IGMG_IGMR_MATCH_ERROR_RGL_RML = "Alla data misura è presente un precedente IGMG. Rettificare con il flusso IGMR"

  //Flusso 1
  val TML="tml"
  val TGL="tgl"
  val TMV="tmv"
  val SWG1="swg1"
  val FUI="fui"
  val FDD="fdd"
  val TAL="tal"
  val TAS="tas"
  val TAV="tav"
  val D01="d01"
  val D02="d02"
  val R01="r01"
  val A40="a40"
  val S40="s40"
  val R40="r40"
  val A01="a01"
  val A02="a02"
  val S02="s02"
  val V01="v01"
  val M01="m01"
  val V02="v02"
  val SM1="sm1"
  val SM2="sm2"
  val AD2="ad2"
  val AD3="ad3"
  val AD4="ad4"
  val AD5="ad5"
  //flusso 2
  val RML="rml"
  val RGL="rgl"
  val RMV="rmv"
  val RSL="rsl"
  val D01R="d01r"
  val D02R="d02r"
  val R01R="r01r"
  val A40R="a40r"
  val S40R="s40r"
  val R40R="r40r"
  val A01R="a01r"
  val A02R="a02r"
  val S02R="s02r"
  val V01R="v01r"
  val M01R="m01r"
  val V02R="v02r"
  val SM1R="sm1r"
  val SM2R="sm2r"
  val AD2R="ad2r"
  val AD3R="ad3r"
  val AD4R="ad4r"
  val AD5R="ad5r"
  //Flusso 1
  val flusso1List = Set(TML, TGL, TMV, SWG1, FUI, FDD, TAL, TAS, TAV, D01, D02, R01, A40, S40, R40, A01, A02, S02, V01, M01, V02, SM1, SM2, AD2, AD3, AD4, AD5)
  //Flusso 2
  val flusso2List = Set(RML, RGL, RMV, RSL, D01R, D02R, R01R, A40R, S40R, R40R, A01R, A02R, S02R, V01R, M01R, V02R, SM1R, SM2R, AD2R, AD3R, AD4R, AD5R)

  val SW1="sw1"
  val DEF="def"
  val IM1="im1"
  val flussoOldList = Set(SW1, FUI, DEF, RGL, RML, TAL, TAV, TGL, RSL, RMV, TML, TAS, TMV, A01, A40, D01, SM1, R01, A02, V01, SM2, M01, V02, IM1)

  //classe_gruppo_mis legal values (IGMG and GAS STD 1)
  val G1_6 = "g1,6"
  val G2_5 = "g2,5"
  val G4 = "g4"
  val G6 = "g6"
  val G10 = "g10"
  val G16 = "g16"
  val G25 = "g25"
  val G40 = "g40"
  val G65 = "g65"
  val G100 = "g100"
  val G160 = "g160"
  val G250 = "g250"
  val G400 = "g400"
  val G650 = "g650"
  val G1000 = "g1000"
  val G1600 = "g1600"
  val G2500 = "g2500"
  val G4000 = "g4000"
  val G6500 = "g6500"

  val classeGruppoMisLegalValues = Set(G1_6, G2_5, G4, G6, G10, G16, G25, G40, G65, G100, G160, G250, G400, G650, G1000, G1600, G2500, G4000, G6500)

  val STD = "std"
  val IGMG = "igmg"
  val IGMR = "igmr"
  val OLD = "old"
  val OLD_PRESTAZIONALE = "oldPrestazionale"
  val NAMING_UNMATCH = "namingUnmatch"

  val STD_NAMING_UNMATCH = "stdNamingUnmatch"
  val IGMG_NAMING_UNMATCH = "IGMGNamingUnmatch"
  val IGMR_NAMING_UNMATCH = "IGMRNamingUnmatch"
  val IGMR_NAMING_UNMATCH_BUT_STD_MATCH = "IGMRNamingUnmatchButStdMatch"
  val FILE_NOT_XML = "fileNotXml"
  val FILE_XML_NOT_PRESENT = "fileXmlNotPresent"
  val ZIP_XML_NAMING_UNMATCH = "zipXmlNamingUnmatch"
  val CORRUPTED_ZIP = "corruptedZip"
  val CORRUPTED_XML = "corruptedXml"
  val GENERIC_ERROR = "genericError"
  val FILE_READ_EXCEPTION = "fileReadException"

  val COEFF_CORR_MAX_VALUE = 99999.0 // Maximum value of coeff_corr field.
}
