agg.db=agg
rcugas.db=rcugas
dailyConsumption.tableName=daily_consumption_agg
dailyConsumptionIncoerenti.tableName=daily_consumption_agg_incoerenti
dailyConsumptionEsclusi.tableName=daily_consumption_agg_esclusi

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo/AGG_TMP
isilon.basepath.out=/mnt/Settlement
hdfs.tmp.basepath=/apps/AGG/tmp
hdfs.output.basepath=/user/hive/warehouse/au.db/misure_gas_au/agg/aggregatore_info_log

deploy.path=/home/sii_misure_gas/agg/agg_pub
hdfs.path=/apps/AGG/deploy_aggregazione