isilon.deploy.path=/home/sii_misure_gas/gasivori/deploy

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/Settlement

hdfs.deploy.path=/apps/gasivori/deploy

hdfs.infoLog.basepath=/user/hive/warehouse/gasivori.db/aggregatore_info_log
aggregatore.infoLog.tableName=aggregatore_info_log

sqoop.config.path=/apps/deploy/job.properties

gasivori.db=gasivori