spark.app.user=TMPOD_CLOUD
spark.app.password=TMPOD_CLOUD01
spark.app.url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = scancl01-01.siiau.local)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = SIIP)))
spark.app.jdbc.driver=oracle.jdbc.driver.OracleDriver
spark.app.time_zone=UTC
spark.app.conn.repartition=5
spark.app.controllo.flaguddpod=true
spark.app.controllo.trattamento=true
spark.app.controllo.validato=true
spark.app.controllo.flagarea=false
spark.app.controllo.stato=false
spark.app.controllo.distr_azienda=true
spark.app.controllo.estrai_area=true
spark.app.perdita.tensione.380=0.007
spark.app.perdita.tensione.220=0.011
spark.app.perdita.tensione.150=0.018
spark.app.perdita.tensione.1_35=0.038
spark.app.perdita.tensione.1=0.102
spark.app.v2_2G=_v2_2G
spark.app.regex_2G=X_R,X_NR
spark.app.directory.root.1G=isilonshare1G
spark.app.directory.root.2G=isilonshare
spark.app.directory.root.GAS=isilonshare_gas
spark.app.directory.temporanea.1G=/mnt/isilonshare1/TMP_1Gb
spark.app.directory.temporanea.2G=/mnt/isilonshare1/TMP_2Gb
spark.app.directory.temporanea.GAS=/mnt/isilonshare1/GAS_INJ
spark.app.directory.temporanea.GAS_Recupero_Puntuale=/mnt/isilonshare1/GAS_INJ_RECUPERO
spark.app.aggregazioni.file.esclusi=/apps/xml_esclusi/file_da_escludere_202104.txt
spark.app.printdataframe=false
spark.app.testlevel=0
spark.app.verbose=false
spark.app.dbdest=au
spark.app.basepath=/user/hive/warehouse/au.db/misure_ee_au

spark.app.controllo.flaguddpod.sem=true
spark.app.controllo.trattamento.sem=true
spark.app.controllo.validato.sem=true
spark.app.controllo.flagarea.sem=false
spark.app.controllo.stato.sem=false
spark.app.controllo.distr_azienda.sem=true
spark.app.controllo.estrai_area.sem=true
spark.app.verbose.sem=true

spark.app.controllo.flaguddpod.sem.oracle=true
spark.app.controllo.trattamento.sem.oracle=false
spark.app.controllo.validato.sem.oracle=true
spark.app.controllo.flagarea.sem.oracle=false
spark.app.controllo.stato.sem.oracle=false
spark.app.controllo.distr_azienda.sem.oracle=true
spark.app.controllo.estrai_area.sem.oracle=true

spark.app.mot3_table=import_ora_clou_[ANNOMESE]_mot3
spark.app.flussoquarti_table=flusso_misure_quarti
spark.app.flussoquarti_table.oracle=flusso_misure_quarti_201701_201807_vs
spark.app.sem.oracle.praticheR_TBL=IMPORT_CLOUD_SEM_2017_2018_view_vs 

spark.app.impala.url=jdbc:impala://dmphclo14.siiau.local:21050/au
spark.app.impala.jdbc.driver=com.cloudera.impala.jdbc41.Driver
spark.app.aggregazioni.file.sem.esclusi=/apps/deploy/sem/file_esclusi/
spark.app.join.ternecommitted.sem.custom=/apps/deploy/sem/join_terne_committed_periodica/

spark.app.portale.usa_misure_noaggr1G=true
spark.app.portale.path.base.misureEE=/user/hive/warehouse/acquirente_unico/misure.db/
spark.app.portale.path.base.storic.misure.tmp=/user/hive/warehouse/acquirente_unico/misure.db/misure_storiche/
spark.app.mongodb.usecollaudo=false
spark.app.mongodb.connstr.produzione=mongodb://pdc:AueMongo123@172.16.16.71:27017,172.16.16.72:27017,172.16.16.73:27017
spark.app.mongodb.connstr.collaudo=mongodb://pdc:AueMongo123@172.16.16.70:27019,172.16.16.159:27019
spark.app.mongodb.suffix.collection=_2
spark.app.mongodb.writeconcern_write.produzione=3
spark.app.mongodb.writeconcern_journal.produzione=true
spark.app.mongodb.dbgas.input=misuregas


spark.app.dettpod.aggregato.path=/mnt/isilonshare1/AGGR_ORARIO_DETT_POD_A
spark.app.dettpod.aggregato.sem.path=/mnt/isilonshare1/AGGR_ORARIO_DETT_POD_SEM_A
spark.app.ammissibilita.1G.path=/mnt/isilonshare1/1G_AMMISS
spark.app.ammissibilita.2G.path=/mnt/isilonshare1/2G_AMMISS

spark.app.ammissibilita.checkAmmiOn=false