sbg.db=eng_test
rcugas.db=rcugas
dailyConsumption.tableName=daily_consumption_sbg

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/settlementSYN_parallelo
hdfs.tmp.basepath=/user/eng_test/tmp
hdfs.output.basepath=/user/hive/warehouse/eng_test.db/aggregatore_info_log

pdrAnomali.listaC.csvPath=/user/eng_test/sbg/deploy/deploy_aggregazione/csv_pdr_anomali/PDR_ANOMALI_LISTA_C.csv
pdrAnomali.listaD.csvPath=/user/eng_test/sbg/deploy/deploy_aggregazione/csv_pdr_anomali/PDR_ANOMALI_LISTA_D.csv

deploy.path=/home/eng_test/sbg/aggregato
hdfs.path=/user/eng_test/sbg/deploy/deploy_aggregazione