<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<!-- Codice pratica di switching rilasciato dal SII ai sensi del comma 8.2 della deliberazione 487/2015/R/EEL (15 caratteri)--> 
  <xs:simpleType name="CodPratAttType">
    <xs:restriction base="xs:string">
    <xs:pattern value="[a-zA-Z0-9]{15}"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Codice Contratto Dispacciamento come definito da Terna -->
  <xs:simpleType name="CodContrDispType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="6"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- CodFlusso per parametrizzare il codice RNO e gestire anche RSN per le rettifiche delle letture di switching-->
  <xs:simpleType name="CodFlusso">
		<xs:restriction base="xs:string">
       <xs:enumeration value="RNO"/>
       <xs:enumeration value="RSN"/>
       <xs:minLength value="3"/>
       <xs:maxLength value="3"/>
    </xs:restriction>
	</xs:simpleType>
  <!-- Codice POD per esempio IT 123 E 12345678 -->
  <xs:simpleType name="CodicePodType">
    <xs:restriction base="xs:string">
      <xs:minLength value="14"/>
      <xs:maxLength value="15"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Codice Tariffa -->
  <xs:simpleType name="CodiceTariffaType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="30"/>
    </xs:restriction>
  </xs:simpleType>

  <!-- Codice Tariffa -->
  <xs:simpleType name="CodiceTariffaFType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="10"/>
    </xs:restriction>
  </xs:simpleType>
  
  <!-- Data (Formato italiano dd/MM/yyyy) -->
  <xs:simpleType name="DataItaType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(0[1-9]|[12][0-9]|3[01])[//](0[1-9]|1[012])[//](19|20)\d\d"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Dst: 0=no DST     - potenziali 96 quarti d'ora;
            1=Inizio DST - potenziali 92 quarti d'ora;
            2=Fine DST   - Prima parte curva;
            3=Fine DST   - Seconda parte curva -->
  <xs:simpleType name="DstType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="0"/>
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Giorno (Formato dd) -->
  <xs:simpleType name="GiornoType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(0[1-9]|[12][0-9]|3[01])"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  Alfanumerico 3. Formato: 3 cifre (massimo) -->
  <xs:simpleType name="Intero3Type">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[1-9]\d{0,2}|[0]{1}"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  Alfanumerico 10. Formato: 10 cifre (massimo) -->
  <xs:simpleType name="Intero10Type">
    <xs:restriction base="xs:integer">
      <xs:pattern value="[1-9]\d{0,9}|[0]{1}"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Matricola Misuratore -->
  <xs:simpleType name="MatrMisType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="17"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Mese Anno (Formato italiano MM/yyyy) -->
  <xs:simpleType name="MeseAnnoItaType">
    <xs:restriction base="xs:string">
      <xs:pattern value="(0[1-9]|1[012])[//](19|20)\d\d"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Motivazione rettifica -->
  <xs:simpleType name="MotivazioneType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="1"/>
      <xs:enumeration value="2"/>
      <xs:enumeration value="3"/>
      <xs:enumeration value="4"/>
      <xs:enumeration value="5"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  Alfanumerico 10. Formato: 6 cifre (massimo), Virgola, 3 cifre -->
  <xs:simpleType name="Numerico6v3Type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[1-9]\d{0,5}[,][0-9]{3}|[0][,][0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  Alfanumerico 11. Formato: 7 cifre (massimo), Virgola, 3 cifre -->
  <xs:simpleType name="Numerico7v3Type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[1-9]\d{0,6}[,][0-9]{3}|[0][,][0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>
  <!--  Alfanumerico 16. Formato: 12 cifre (massimo), Virgola, 3 cifre -->
  <xs:simpleType name="Numerico12v3Type">
    <xs:restriction base="xs:string">
      <xs:pattern value="[1-9]\d{0,11}[,][0-9]{3}|[0][,][0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>

  <!--  Alfanumerico 16. Formato: 12 cifre (massimo), Virgola, 3 cifre e null -->
  <xs:simpleType name="Numerico12v3TypeV2">
    <xs:restriction base="xs:string">
      <xs:pattern value="\s*|[1-9]\d{0,11}[,][0-9]{3}|[0][,][0-9]{3}"/>
    </xs:restriction>
  </xs:simpleType>


  <!-- Tipo Semplice con scelta SI/NO -->
  <xs:simpleType name="OnOffType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SI"/>
      <xs:enumeration value="NO"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Partita IVA -->
  <!-- Validato solo sulla lunghezza (11) e il tipo dato (numerico) -->
  <xs:simpleType name="PIVAType">
    <xs:restriction base="xs:string">
      <xs:pattern value="\d{11}"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- PIVA ALFANUMERICA -->
  <xs:simpleType name="PIVAType_AlfNmr">
    <xs:restriction base="xs:string">
      <xs:maxLength value="16"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Punto Dispacciamento -->
  <xs:simpleType name="PuntoDispacciamentoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="NORD"/>
      <xs:enumeration value="CNOR"/>
      <xs:enumeration value="CSUD"/>
      <xs:enumeration value="SUD"/>
      <xs:enumeration value="SICI"/>
      <xs:enumeration value="SARD"/>
      <xs:enumeration value="NORE"/>
	  <xs:enumeration value="CALA"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Raccolta -->
  <xs:simpleType name="RaccoltaType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="P"/>
      <xs:enumeration value="T"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Servizio Tutela -->
  <xs:simpleType name="ServizioTutelaType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="MT"/>
      <xs:enumeration value="S"/>
	  <xs:enumeration value="TG"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Tipo Dato -->
  <xs:simpleType name="TipoDatoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="E"/>
      <xs:enumeration value="S"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Trattamento -->
  <xs:simpleType name="TrattamentoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="M"/>
      <xs:enumeration value="F"/>
      <xs:enumeration value="O"/>
      <xs:enumeration value="C"/>
    </xs:restriction>
  </xs:simpleType>
  <!-- Validato -->
  <xs:simpleType name="ValidatoType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="S"/>
      <xs:enumeration value="N"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoCodFlussoSType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SOS"/>
      <xs:enumeration value="S2G"/>
      <xs:enumeration value="SNS"/>   
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoCodFlussoFType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="SOF"/>
      <xs:enumeration value="SNF"/>
      <xs:enumeration value="F2G"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="TipoMisuratoreType">
    <xs:restriction base="xs:string">
      <xs:enumeration value="E"/>
      <xs:enumeration value="T"/>
      <xs:enumeration value="G"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:simpleType name="RegimeCompType">
    <xs:restriction base="xs:string">
      <xs:maxLength value="4"/>
    </xs:restriction>
  </xs:simpleType>


</xs:schema>
