deploy.path.local = ${deploy.path.local}
deploy.path.logs = ${deploy.path.logs}
deploy.path.hdfs = ${deploy.path.hdfs}

# PARAMETRI FORNITURE
params.job.days_interval_max = ${params.job.days_interval_max}
# PARAMETRI MISURE
params.job.months_interval_max = ${params.job.months_interval_max}
params.job.months_interval_split = ${params.job.months_interval_split}
# forza soglia a -1 per forzare calcolo completo
params.mongodb.max_doc_delta_forniture = -1
params.mongodb.max_doc_delta_misure = -1

#FORNITURE
hive.table.rcugas_clientefinale_p = ${hive.table.rcugas_clientefinale_p}
hive.table.rcugas_connessioni_distr_p = ${hive.table.rcugas_connessioni_distr_p}
hive.table.rcugas_fornitura_p = ${hive.table.rcugas_fornitura_p}
hive.table.rcugas_indirizzi_p = ${hive.table.rcugas_indirizzi_p}
hive.table.rcugas_pdr_datiprelievo_p = ${hive.table.rcugas_pdr_datiprelievo_p}
hive.table.rcugas_pdr_misuratore_p = ${hive.table.rcugas_pdr_misuratore_p}
hive.table.rcugas_pdr_p = ${hive.table.rcugas_pdr_p}
hive.table.rcugas_residenza_p = ${hive.table.rcugas_residenza_p}
hive.table.rcugas_venditore_p = ${hive.table.rcugas_venditore_p}
hive.table.v_rcugas_distributore_p = ${hive.table.v_rcugas_distributore_p}
hive.table.v_rcu_azienda_p = ${hive.table.v_rcu_azienda_p}
hive.table.switch_gas_prt_swg_p = ${hive.table.switch_gas_prt_swg_p}
hive.table.tdg_vuln_p = ${hive.table.tdg_vuln_p}
hive.table.rcugas_codice_offerta_p = ${hive.table.rcugas_codice_offerta_p}
#MISURE
hive.table.cmg_gas_prt_cmg_rgl_p = ${hive.table.cmg_gas_prt_cmg_rgl_p}
hive.table.cmg_gas_prt_cmg_rml_p = ${hive.table.cmg_gas_prt_cmg_rml_p}
hive.table.cmg_gas_prt_cmg_rmv_p = ${hive.table.cmg_gas_prt_cmg_rmv_p}
hive.table.cmg_gas_prt_cmg_tal_p = ${hive.table.cmg_gas_prt_cmg_tal_p}
hive.table.cmg_gas_prt_cmg_tav_p = ${hive.table.cmg_gas_prt_cmg_tav_p}
hive.table.cmg_gas_prt_cmg_tgl_p = ${hive.table.cmg_gas_prt_cmg_tgl_p}
hive.table.cmg_gas_prt_cmg_tml_p = ${hive.table.cmg_gas_prt_cmg_tml_p}
hive.table.switch_gas_prt_vtg6_p = ${hive.table.switch_gas_prt_vtg6_p}

#TABELLE HIVE DI OUTPUT
hive.table.forniture_processi_gas = ${hive.table.forniture_processi_gas}
hive.table.forniture_misure_gas = ${hive.table.forniture_misure_gas}
hive.table.misure_storic_f2 = ${hive.table.misure_storic_f2}
hive.table.misure_data_calcolo = ${hive.table.misure_data_calcolo}

#PUNTAMENTI MONGODB
mongodb.db.uri = ${mongodb.db.uri}
mongodb.client.uri = ${mongodb.client.uri}
mongodb.db.name = ${mongodb.db.name}
mongodb.collection.fornitureGas = ${mongodb.collection.fornitureGas}
mongodb.collection.misureGas33m = ${mongodb.collection.misureGas33m}
mongodb.collection.misureGas3m = ${mongodb.collection.misureGas3m}
mongodb.conf.readPreference = ${mongodb.conf.readPreference}
mongodb.conf.writeConcern = ${mongodb.conf.writeConcern}
