
running {
parallelism=${spark.parallelism}
shuffle=${spark.shuffle}
memoryoverhead=${spark.memoryoverhead}
}
application {
date {
    format=${application.spark.date.format}
    format_to_export=${hive.date.format.to_export}
}
}
hive {
  table {
    sbgmisure {
         name=${hive.table.sbgmisure.name}
         db=${hive.table.sbgmisure.db}
     }
    rcugasmassivop
    {
        name=${hive.table.rcugasmassivop.name}
        db=${hive.table.rcugasmassivop.db}
    }
    perimetropdr
     {
        name=${hive.table.perimetropdr.name}
        db=${hive.table.perimetropdr.db}
     }
    anagrafica
    {
        name=${hive.table.anagrafica.name}
        db=${hive.table.anagrafica.db}

    }
    result{
        name=${hive.table.result.name}
        db=${hive.table.result.db}
    }
  }
}
