hadoop.username=sii_misure
sqoop.config.path=/apps/deploy/job.properties
gse.db=gse
dataman.db=dataman_bi
hdfs.output.path=/user/hive/warehouse/gse.db
hdfs.deploy.path=/apps/GSE/deploy/calcolo_mensile
isilon.deploy.path=/home/sii_misure/GSE/deploy/calcolo_mensile