output.db=cdp
rcuGasMassivo.tableName=rcugas_massivo_p
rcuGasConnessioniDistr2.tableName=rcugas_connessioni_distr2_p
rcuGasVarMisuratore.tableName=rcugas_var_misuratore_p
rcuGasVarConvertitore.tableName=rcugas_var_convertitore_p

rootpath=/user/hive/warehouse/acquirente_unico/sqoop_portcons

output.rootpath=/user/hive/warehouse/cdp.db

isilon.deploy.path=/home/sii_misure_gas/CDP/freezer
hdfs.deploy.path=/apps/CDP/freezer/deploy