gse.perimetro_er_ee.tablename=${gse.db}.gse_perimetro_er_ee
gse.richiesta_er_a.tablename=${gse.db}.gse_richiesta_er_a
dwh_consumi.annuale.tablename=${dataman.db}.dwh_consumi_ee_tb
gse.gse_aggr_a.tablename=${gse.db}.gse_aggr_a
gse.gse_aggr_a.basepath=${hdfs.output.path}/gse_aggr_a
gse.gse_aggr_a_export.tablename=${gse.db}.gse_aggr_a_export
gse.gse_aggr_a_expor.basepath=${hdfs.output.path}/gse_aggr_a_export
sh.mainone.script=${sh.mainone.path}/run_mainone.sh
