package it.eng.au.ERP.model.au

case class flussoMisureInterconnessione2Model(

                                               ea_e47: String = null,
                                               ea_e48: String = null,
                                               ea_e49: String = null,
                                               ea_e50: String = null,
                                               ea_e51: String = null,
                                               ea_e52: String = null,
                                               ea_e53: String = null,
                                               ea_e54: String = null,
                                               ea_e55: String = null,
                                               ea_e56: String = null,
                                               ea_e57: String = null,
                                               ea_e58: String = null,
                                               ea_e59: String = null,
                                               ea_e60: String = null,
                                               ea_e61: String = null,
                                               ea_e62: String = null,
                                               ea_e63: String = null,
                                               ea_e64: String = null,
                                               ea_e65: String = null,
                                               ea_e66: String = null,
                                               ea_e67: String = null,
                                               ea_e68: String = null,
                                               ea_e69: String = null,
                                               ea_e70: String = null,
                                               ea_e71: String = null,
                                               ea_e72: String = null,
                                               ea_e73: String = null,
                                               ea_e74: String = null,
                                               ea_e75: String = null,
                                               ea_e76: String = null,
                                               ea_e77: String = null,
                                               ea_e78: String = null,
                                               ea_e79: String = null,
                                               ea_e80: String = null,
                                               ea_e81: String = null,
                                               ea_e82: String = null,
                                               ea_e83: String = null,
                                               ea_e84: String = null,
                                               ea_e85: String = null,
                                               ea_e86: String = null,
                                               ea_e87: String = null,
                                               ea_e88: String = null,
                                               ea_e89: String = null,
                                               ea_e90: String = null,
                                               ea_e91: String = null,
                                               ea_e92: String = null,
                                               ea_e93: String = null,
                                               ea_e94: String = null,
                                               ea_e95: String = null,
                                               ea_e96: String = null,
                                               ea_e97: String = null,
                                               ea_e98: String = null,
                                               ea_e99: String = null,
                                               ea_e100: String = null,
                                               eaint_e1: String = null,
                                               eaint_e2: String = null,
                                               eaint_e3: String = null,
                                               eaint_e4: String = null,
                                               eaint_e5: String = null,
                                               eaint_e6: String = null,
                                               eaint_e7: String = null,
                                               eaint_e8: String = null,
                                               eaint_e9: String = null,
                                               eaint_e10: String = null,
                                               eaint_e11: String = null,
                                               eaint_e12: String = null,
                                               eaint_e13: String = null,
                                               eaint_e14: String = null,
                                               eaint_e15: String = null,
                                               eaint_e16: String = null,
                                               eaint_e17: String = null,
                                               // able to join models in junit test

                                               joinMod : String = null

                                            )
