agg.db = eng_test
sbg.db = eng_test
cdp.db = eng_test
ccg.db = eng_test
rcugas.db=rcugas

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/settlementSYN_parallelo

table.path.hdfs = /user/hive/warehouse/eng_test.db/

deploy.path = /home/eng_test/ccg/deploy
deploy.path.hdfs = /user/eng_test/ccg/deploy

hadoop.username = eng_test
sqoop.config.path = /user/eng_test/ccg/deploy/sqoop.properties