spark.validazione.xsd.defdomplextypes=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-DefComplexTypes.xsd
spark.validazione.xsd.defsimpletypes=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-DefSimpleTypes.xsd
spark.validazione.xsd.flusso1_pdo=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso1-PDO.xsd
spark.validazione.xsd.flusso1_rfo=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso3-RFO.xsd
spark.validazione.xsd.flusso1_pdo_v2=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso1-Periodico_v2.xsd
spark.validazione.xsd.flusso1_rfo_v2=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso2-Rettifica_v2.xsd

spark.validazione.xsd.defdomplextypes.straniere=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-DefComplexTypes_straniere.xsd
spark.validazione.xsd.defsimpletypes.straniere=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-DefSimpleTypes_straniere.xsd
spark.validazione.xsd.flusso1_pdo.straniere=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso1-PDO_straniere.xsd
spark.validazione.xsd.flusso1_rfo.straniere=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso3-RFO_straniere.xsd
spark.validazione.xsd.flusso1_pdo_v2.straniere=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso1-Periodico_v2_straniere.xsd
spark.validazione.xsd.flusso1_rfo_v2.straniere=/mnt/isilonshare1/XSD/FlussiDatiMisuraPrelievoEE-Flusso2-Rettifica_v2_straniere.xsd

spark.validazione.xsd.flusso_vno=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_volturate/FlussiDatiMisuraVolturaEE-Flusso1-VNO.xsd
spark.validazione.xsd.flusso_rnv=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_volturate/FlussiDatiMisuraVolturaEE-Flusso2-RNV.xsd
spark.validazione.xsd.flusso_pno=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_NON_Orarie/FlussiDatiMisuraPrelievoEE-Flusso2-PNO_allinone.xsd
spark.validazione.xsd.flusso_rno=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_NON_Orarie/FlussiDatiMisuraPrelievoEE-Flusso4-RNO_allinone.xsd
spark.validazione.xsd.flusso_snm=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_di_Switching/FlussiDatiMisuraPrelievoEE-Flusso5-SNM.xsd
spark.validazione.xsd.flusso_sof=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_di_Switching/FlussiDatiMisuraPrelievoEE-Flusso6-SOF.xsd
spark.validazione.xsd.flusso_sos=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_di_Switching/FlussiDatiMisuraPrelievoEE-Flusso7-SOS.xsd
spark.validazione.xsd.flusso_snf=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_di_Switching/FlussiDatiMisuraPrelievoEE-Flusso8-SNF.xsd
spark.validazione.xsd.flusso_sns=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_di_Switching/FlussiDatiMisuraPrelievoEE-Flusso9-SNS.xsd
spark.validazione.xsd.flusso_rsn=/mnt/isilonshare1/XSD_OTHER_OLD/Misure_di_Switching/FlussiDatiMisuraPrelievoEE-Flusso10-RSN.xsd

spark.validazione.xsd.defdomplextypes_2G=/mnt/isilonshare1/XSD_NEW/FlussiDatiMisuraPrelievoEE-DefComplexTypes.xsd
spark.validazione.xsd.defsimpletypes_2G=/mnt/isilonshare1/XSD_NEW/FlussiDatiMisuraPrelievoEE-DefSimpleTypes.xsd
spark.validazione.xsd.flusso_new_pdo=/mnt/isilonshare1/XSD_NEW/FlussiDatiMisuraPrelievoEE-Flusso1-Periodico.xsd
spark.validazione.xsd.flusso_new_rfo=/mnt/isilonshare1/XSD_NEW/FlussiDatiMisuraPrelievoEE-Flusso2-Rettifica.xsd

spark.validazione.xsd.defdomplextypes_2G.straniere=/mnt/isilonshare1/XSD_NEW/straniere/FlussiDatiMisuraPrelievoEE-DefComplexTypes.xsd
spark.validazione.xsd.defsimpletypes_2G.straniere=/mnt/isilonshare1/XSD_NEW/straniere/FlussiDatiMisuraPrelievoEE-DefSimpleTypes.xsd
spark.validazione.xsd.flusso_new_pdo.straniere=/mnt/isilonshare1/XSD_NEW/straniere/FlussiDatiMisuraPrelievoEE-Flusso1-Periodico.xsd
spark.validazione.xsd.flusso_new_rfo.straniere=/mnt/isilonshare1/XSD_NEW/straniere/FlussiDatiMisuraPrelievoEE-Flusso2-Rettifica.xsd

spark.validazione.xsd.flusso_smis=/mnt/isilonshare1/XSD_NEW/SMIS/FlussiDatiMisuraPrelievoEE-Flusso1-RiprogrSostMisuratore.xsd