agg.dailyConsumption.tableName=${agg.db}.${dailyConsumption.tableName}
agg.dailyConsumption.executionid=1624261923745
#agg.dailyConsumption.infodb=${sbg.db}

agg.validateFlow.tableName=${agg.db}.validated_flows_sbg
rcugas.varMisuratore.tableName=${rcugas.db}.rcugas_var_misuratore_p
rcugas.pdr.tableName=${rcugas.db}.rcugas_pdr_p
rcugas.remiAnagrafica.tableName=${rcugas.db}.rcugas_remi_anagrafica_p
rcugas.gestTrasporto.tableName=${rcugas.db}.rcugas_gesttrasporto_p
rcugas.vIt.tableName=${rcugas.db}.v_rcugas_it_p
rcugas.connDistr2.tableName=${rcugas.db}.rcugas_connessioni_distr2_p

isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}
hdfs.tmp.basepath=${hdfs.tmp.basepath}
hdfs.output.basepath=${hdfs.output.basepath}
hdfs.infoLog.tableName=${agg.db}.aggregatore_info_log

#da nuovo sw con le perfomance
hdfs.output.basepath.infoLog=${hdfs.output.basepath}


zip.session.name=SBG
year=202201

maxDimensionZipFileByte=100000000
maxNumRowFile=80000
maxSizeThresholdZip=80000000

#da nuovo sw con le perfomance
csvMaxRowLength=600000


pdr.anomali.listaC.enabled=true
pdr.anomali.listaD.enabled=true
pdr.anomali.listaC.csvPath=${pdrAnomali.listaC.csvPath}
pdr.anomali.listaD.csvPath=${pdrAnomali.listaD.csvPath}

# Utilizzato per la sterilizzazione degli incoerenti
class.group.measure.range.max.path=${hdfs.path}/gruppo_mis_limit.csv
incoerenzaGDM.numberOfDays.threshold=5

# Lista csv di coppie. Una coppia ha la seguente sintassi: left_value->right_value.
# Valori consentiti per left_value: aggregato, dettaglioUnico, esclusi, dettaglio, dtg, incoerenti, incoerentidettaglio
# Valori consentiti per right_value: SBG1, SBG2, SBG3, SBG4, SBG5
# Esempio: genera aggregato.zip per SBG1 e SBG5 e Esclusi.zip per SBG2
#          file.couples.type=aggregato->SBG1,aggregato->SBG5,esclusi->SBG2

#output.file.couples=esclusi->SBG1,esclusi->SBG2,esclusi->SBG4,esclusi->SBG5,dettaglio->SBG1,dettaglio->SBG4,dettaglio->SBG5,dtg->SBG5

#Solo INCOERENTI/ANOMALI
#output.file.couples=incoerenti->SBG1,incoerenti->SBG2,incoerenti->SBG3,incoerenti->SBG4,incoerenti->SBG5

#Solo ESCLUSI
#output.file.couples=esclusi->SBG1,esclusi->SBG2,esclusi->SBG4,esclusi->SBG5

#SOLO DETTAGLI PDR_G/DTG
#output.file.couples=dettaglio->SBG1,dettaglio->SBG4,dettaglio->SBG5,dtg->SBG5

#SOLO DTG
#output.file.couples=dtg->SBG5

# SBG1 escluso (M.A.)
#output.file.couples=esclusi->SBG2,esclusi->SBG4,esclusi->SBG5,dettaglio->SBG4,dettaglio->SBG5,dtg->SBG5

#output.file.couples=aggregato->SBG1,aggregato->SBG2,aggregato->SBG3,aggregato->SBG4,aggregato->SBG5

#output.file.couples=aggregato->SBG1,aggregato->SBG2,aggregato->SBG3,aggregato->SBG4,aggregato->SBG5,esclusi->SBG1,esclusi->SBG2,esclusi->SBG4,esclusi->SBG5,dettaglioUnico->SBG1,dettaglioUnico->SBG4,dettaglioUnico->SBG5,dettaglio->SBG1,dettaglio->SBG4,dettaglio->SBG5,dtg->SBG5

output.file.couples=aggregato->SBG1,aggregato->SBG2,aggregato->SBG3,aggregato->SBG4,aggregato->SBG5

publication.type=SBG