# proprieta' processo
output.file.csv_max_row=${output.file.csv_max_row}
# 25MB
output.file.zip_max_byte_size=${output.file.zip_max_byte_size}
output.file.temporary_path=${output.file.temporary_path}
output.file.path=${output.file.path}

# tabelle hive
# output
hive.table.cceRichiestaPod=${hive.table.cceRichiestaPod}
hive.table.cceRichiestaFiltro=${hive.table.cceRichiestaFiltro}
hive.table.cceEsito=${hive.table.cceEsito}
hive.table.cceEsitoExport=${hive.table.cceEsitoExport}
hive.table.cceCalcoloCa=${hive.table.cceCalcoloCa}
hive.table.cceCalcoloCaFlussi=${hive.table.cceCalcoloCaFlussi}
# input
hive.table.cceCalcoloAnagrafica=${hive.table.cceCalcoloAnagrafica}
hive.table.cceCalcoloP=${hive.table.cceCalcoloP}
hive.table.cceCalcoloPein=${hive.table.cceCalcoloPein}
hive.table.cceCalcoloPR=${hive.table.cceCalcoloPR}
hive.table.cceCalcoloPRein=${hive.table.cceCalcoloPRein}
hive.table.cceCalcoloTrattamento=${hive.table.cceCalcoloTrattamento}
hive.table.cceCalcTrack=${hive.table.cceCalcTrack}
