DROP TABLE misuregas.RCUGAS_PDR_MISURATORE;
CREATE TABLE misuregas.RCUGAS_PDR_MISURATORE stored as parquet as 
select
   RCUGAS_PDR_MISURATORE.N_ID_PDR,
   RCUGAS_PDR_MISURATORE.T_MATRICOLA_MISURATORE,
   RCUGAS_PDR_MISURATORE.T_CLASSE_MISURATORE,
   RCUGAS_PDR_MISURATORE.N_COEFF_CORREZIONE,
   MAX(RCUGAS_PDR_MISURATORE.T_DATA_INST_MISURATORE) T_DATA_INST_MISURATORE
   FROM RCUGAS.RCUGAS_PDR_MISURATORE_p AS RCUGAS_PDR_MISURATORE
   LEFT JOIN (
      SELECT
      RCUGAS_PDR_MISURATORE.N_ID_PDR
      FROM RCUGAS.RCUGAS_PDR_MISURATORE_p as RCUGAS_PDR_MISURATORE
      where cast(date_format(from_unixtime(unix_timestamp(RCUGAS_PDR_MISURATORE.T_DATA_INST_MISURATORE , 'dd/MM/yyyy')),'yyyyMMdd') as int)  >= cast(date_format(date_sub(current_date,396),'yyyyMMdd') as int)
   ) AS cnt
   ON cnt.N_ID_PDR=RCUGAS_PDR_MISURATORE.N_ID_PDR
   GROUP BY
      RCUGAS_PDR_MISURATORE.N_ID_PDR,
      RCUGAS_PDR_MISURATORE.T_MATRICOLA_MISURATORE,
      RCUGAS_PDR_MISURATORE.T_CLASSE_MISURATORE,
      RCUGAS_PDR_MISURATORE.N_COEFF_CORREZIONE,
      RCUGAS_PDR_MISURATORE.T_DATA_INST_MISURATORE;
