cig.db=cig
cig.indennizziRzg2.tableName=cig_indennizzi_rzg2
cig.indennizziRzg2.basepath=/user/hive/warehouse/cig.db/cig_indennizzi_rzg2
cig.reportPubblicazioneRzg2.tableName=cig_report_pubblicazione_rzg2
cig.reportPubblicazioneRzg2.basepath=/user/hive/warehouse/cig.db/cig_report_pubblicazione_rzg2

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/Settlement

isilon.deploy.path=/home/sii_misure_gas/CIG/pubblicazione_rendiconti/deploy
hdfs.deploy.path=/apps/CIG/pubblicazione_rendiconti/deploy