isilon.csv.inputPath  = /mnt/Settlement/TSG/TSG2
isilon.csv.ammissibilitaOutputPath = /mnt/Settlement/TSG/TSG2
isilon.deploy.path=/home/sii_misure_gas/TSG/ammissibilita
hdfs.deploy.path=/apps/TSG/ammissibilita
rcugas.db = rcugas
tsg.db = tsg
tsg.TFCFile.tableName=tsg2_tfc_file
tsg.TFCFile.basepath=/user/hive/warehouse/tsg.db/TSG/tsg2_tfc_file
tsg.VPGFile.tableName=tsg2_vpg_file
tsg.VPGFile.basepath=/user/hive/warehouse/tsg.db/TSG/tsg2_vpg_file

tsg.ReportAmmissibilitaTFC.tableName= tsg2_report_ammissibilita_tfc
tsg.ReportAmmissibilitaTFC.basepath= /user/hive/warehouse/tsg.db/TSG/tsg2_report_ammissibilita_tfc
tsg.ReportAmmissibilitaVPG.tableName= tsg2_report_ammissibilita_vpg
tsg.ReportAmmissibilitaVPG.basepath  = /user/hive/warehouse/tsg.db/TSG/tsg2_report_ammissibilita_vpg

tsg.PubblicazioneAmmissibilitaTFC.tableName = tsg2_pubblicazione_ammissibilita_tfc
tsg.PubblicazioneAmmissibilitaTFC.basepath  = /user/hive/warehouse/tsg.db/TSG/tsg2_pubblicazione_ammissibilita_tfc
tsg.PubblicazioneAmmissibilitaVPG.tableName = tsg2_pubblicazione_ammissibilita_vpg
tsg.PubblicazioneAmmissibilitaVPG.basepath  = /user/hive/warehouse/tsg.db/TSG/tsg2_pubblicazione_ammissibilita_vpg

tsg.TSGTFC.tableName = tsg_tfc
tsg.TSGTFC.basepath  = /user/hive/warehouse/tsg.db/TSG/tsg_tfc
tsg.TSGVPG.tableName = tsg_vpg
tsg.TSGVPG.basepath  = /user/hive/warehouse/tsg.db/TSG/tsg_vpg

rcugas.remiStato.tableName=rcugas_remi_stato_p
rcugas.remi.tableName=rcugas_remi_p

