DROP TABLE IF EXISTS ${hive.table.forniture_processi_gas};
CREATE TABLE ${hive.table.forniture_processi_gas} (
    hashcode STRING,
    codice_fiscale STRING,
    codice_pdr STRING,
    nome STRING,
    cognome STRING,
    p_iva STRING,
    ragione_sociale STRING,
    cap STRING,
    categoria_uso STRING,
    civico STRING,
    classe_misuratore STRING,
    codice_fornitura STRING,
    coefficiente_conversione STRING,
    comune STRING,
    data_inizio_fornitura TIMESTAMP,
    data_fine_fornitura TIMESTAMP,
    data_aggiornamento TIMESTAMP,
    matricola_misuratore STRING,
    nazione STRING,
    nome_strada STRING,
    p_iva_cc STRING,
    provincia STRING,
    ragione_sociale_cc STRING,
    ragione_sociale_distributore STRING,
    residente STRING,
    tipo_fornitura STRING,
    tipo_pdr STRING,
    toponimo_Indirizzo STRING,
    data_inizio_processo_gdm TIMESTAMP,
    data_fine_processo_gdm TIMESTAMP,
    data_di_decorrenza_gdm TIMESTAMP,
    id_processo_gdm STRING,
    in_corso_gdm STRING,
    note_gdm STRING,
    tipo_processo_gdm STRING,
    data_inizio_processo_switch TIMESTAMP,
    data_fine_processo_switch TIMESTAMP,
    data_di_decorrenza_switch TIMESTAMP,
    id_processo_switch STRING,
    in_corso_switch STRING,
    note_switch STRING,
    tipo_processo_switch STRING
)
PARTITIONED BY (data_calcolo STRING)
STORED AS PARQUET;
