# ISILON
root.path=/mnt
temp.path=${root.path}/isilonshare1/GAS_INJ_STD/isilonshare_gas
temp.path.old=${root.path}/isilonshare1/GAS_INJ/isilonshare_gas
unzip.input.path=${root.path}/isilonshare_gas
xsd.path=/mnt/isilonshare1/XSD_GAS_STANDARD
logs.root.path=${root.path}/isilonshare1/Software/schedulazioni/GAS/log_crontab/unzip-ingestion-misure-gas-unico
schedulation.log.path=${root.path}/isilonshare1/Software/schedulazioni/GAS/log_crontab/schedulations
report.log.path=${root.path}/isilonshare1/Software/schedulazioni/GAS/log_crontab/reports
ammissibilita.standard.path=${root.path}/isilonshare1/TMG_SYNC_TMP1
ammissibilita.igmg.path=${root.path}/isilonshare1/TMG_SYNC_TMP1
ammissibilita.igmr.path=${root.path}/isilonshare1/TMG_SYNC_TMP1

# DEPLOY
deploy.path=${root.path}/isilonshare1/Software/GAS/STANDARD

#RECUPERO PUNTUALE
hdfs.recovery.path=/apps/recupero_puntuale_gas

# SPARK
deploy.mode=client
spark.num.executors=15
spark.executor.cores=15
spark.executor.memory=60G
spark.driver.memory=5G
ingestion.deploy.mode=cluster
ingestion.spark.num.executors=15
ingestion.spark.executor.cores=15
ingestion.spark.executor.memory=60G
ingestion.spark.driver.memory=10G
spark.executor.memoryOverhead=4096

# HIVE
hive.cmg_gas=cmg_gas
hive.rcu=rcu
hive.rcugas=rcugas
hive.userneame.permission=sii_misure_gas


# LOG
decompressione.log.name=decompressione.log

# SQOOP
sqoop.num.mappers=8
sqoop.properties.hdfs.path=/apps/deploy/job.properties
sqoop.export.dir=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_igmg_export
sqoop.export.igmr.dir=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas/prt_cmg_igmr_export
sqoop.export.table=TMPOD_CLOUD.flusso_misure_igmg
sqoop.staging.table=TMPOD_CLOUD.flusso_misure_igmg_staging
sqoop.null.character=\\\\N
sqoop.cat.command=hdfs dfs -cat
sqoop.check=true

# MERGE REPORT
merge.report.base.path=${root.path}/isilonshare1/TMG_SYNC_TMP1
merge.report.dest.path=${root.path}/TMG_SYNC_Produzione
merge.report.processes=6
#merge.report.tracking.folder=/tmp/report_ammissibilita_gas_tracking_folder
merge.report.tracking.folder=${root.path}/isilonshare1/report_ammissibilita_gas_tracking_folder