cig.indennizziRzg2.tableName=${cig.db}.${cig.indennizziRzg2.tableName}

cig.reportPubblicazioneRzg2.basepath=${cig.reportPubblicazioneRzg2.basepath}
cig.reportPubblicazioneRzg2.tableName=${cig.db}.${cig.reportPubblicazioneRzg2.tableName}

isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}

maxNumRowFile=25000
maxSizeThresholdZip=25000000
