flow.dataset.tgl.tableName=prova.prt_cmg_tgl_p

rcugasMassivoP.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_MASSIVO_p
rcugasVarMisuratoreP.baepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_MISURATORE_p
rcugasFornituraP.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_FORNITURA_p
rcugasUdd.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_UDD_p
rcugasConnessioniDistr2.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_CONNESSIONI_DISTR2_p
rcugasSospensioni.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_SOSPENSIONI_p
rcuGasVarTrattamentoP.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_TRATTAMENTO_p
rcuAzienda.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCU.RCU_AZIENDA_p

hdfs.deploy.path=/apps/CIG/calcolo_indennizzi/deploy
isilon.deploy.path=/home/sii_misure_gas/CIG/calcolo_indennizzi/deploy

cig.db=cig
aggregatoTotale.tableName=cig_aggregato_totale
aggregatoTotale.basepath=/user/hive/warehouse/cig.db/cig_aggregato_totale
pdrTotale.tableName=cig_pdr_totale
pdrTotale.basepath=/user/hive/warehouse/cig.db/cig_pdr_totale
dettaglioPdr.tableName=cig_dettaglio_pdr
dettaglioPdr.basepath=/user/hive/warehouse/cig.db/cig_dettaglio_pdr
dettaglioOM1.tableName=cig_dettaglio_om1
dettaglioOM1.basepath=/user/hive/warehouse/cig.db/cig_dettaglio_om1
dettaglioOM2.tableName=cig_dettaglio_om2
dettaglioOM2.basepath=/user/hive/warehouse/cig.db/cig_dettaglio_om2
dettaglioOM3.tableName=cig_dettaglio_om3
dettaglioOM3.basepath=/user/hive/warehouse/cig.db/cig_dettaglio_om3