agg.db=eng_test
rcugas.db=rcugas
dailyConsumption.tableName=daily_consumption_agg_v2

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/settlementSYN_parallelo
hdfs.tmp.basepath=/user/eng_test/tmp
hdfs.output.basepath=/user/hive/warehouse/eng_test.db/aggregatore_info_log