isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}

hdfs.infoLog.basepath=${hdfs.infoLog.basepath}
hdfs.infoLog.tableName=${gasivori.db}.${aggregatore.infoLog.tableName}

gasivoriFiliera.cc.tableName=${gasivori.db}.gasivori_filiera_cc_c
gasivoriFiliera.csea.tableName=${gasivori.db}.gasivori_filiera_csea_c
gasivoriFiliera.id.tableName=${gasivori.db}.gasivori_filiera_id_c
gasivoriFiliera.udb.tableName=${gasivori.db}.gasivori_filiera_udb_c
gasivoriFiliera.udd.tableName=${gasivori.db}.gasivori_filiera_udd_c

gasivoriPerimetro.amm.tableName=${gasivori.db}.gasivori_perimetro_amm_c

publication.type=TDG

year.month=202302

maxNumRowFile=600000
maxSizeThresholdZip=60000000

gasivoriFiliera.cc.executionId=
gasivoriFiliera.csea.executionId=
gasivoriFiliera.id.executionId=
gasivoriFiliera.udd.executionId=
gasivoriFiliera.udb.executionId=

amm.nIdGasivoriFile=