spark.app.user=${spark.app.user}
spark.app.password=${spark.app.password}
spark.app.url=${spark.app.url}
spark.app.jdbc.driver=${spark.app.jdbc.driver}
spark.app.time_zone=${spark.app.time_zone}
spark.app.conn.repartition=${spark.app.conn.repartition}
spark.app.controllo.flaguddpod=${spark.app.controllo.flaguddpod}
spark.app.controllo.trattamento=${spark.app.controllo.trattamento}
spark.app.controllo.validato=${spark.app.controllo.validato}
spark.app.controllo.flagarea=${spark.app.controllo.flagarea}
spark.app.controllo.stato=${spark.app.controllo.stato}
spark.app.controllo.distr_azienda=${spark.app.controllo.distr_azienda}
spark.app.controllo.estrai_area=${spark.app.controllo.estrai_area}
spark.app.perdita.tensione.380=${spark.app.perdita.tensione.380}
spark.app.perdita.tensione.220=${spark.app.perdita.tensione.220}
spark.app.perdita.tensione.150=${spark.app.perdita.tensione.150}
spark.app.perdita.tensione.1_35=${spark.app.perdita.tensione.1_35}
spark.app.perdita.tensione.1=${spark.app.perdita.tensione.1}
spark.app.v2_2G=${spark.app.v2_2G}
spark.app.regex_2G=${spark.app.regex_2G}
spark.app.directory.root.1G=${spark.app.directory.root.1G}
spark.app.directory.root.2G=${spark.app.directory.root.2G}
spark.app.directory.root.GAS=${spark.app.directory.root.GAS}
spark.app.directory.temporanea.1G=${spark.app.directory.temporanea.1G}
spark.app.directory.temporanea.2G=${spark.app.directory.temporanea.2G}
spark.app.directory.temporanea.GAS=${spark.app.directory.temporanea.GAS}
spark.app.directory.temporanea.GAS_Recupero_Puntuale=${spark.app.directory.temporanea.GAS_Recupero_Puntuale}
spark.app.aggregazioni.file.esclusi=${spark.app.aggregazioni.file.esclusi}
spark.app.printdataframe=${spark.app.printdataframe}
spark.app.testlevel=${spark.app.testlevel}
spark.app.verbose=${spark.app.verbose}
spark.app.dbdest=${spark.app.dbdest}
spark.app.basepath=${spark.app.basepath}

spark.app.controllo.flaguddpod.sem=${spark.app.controllo.flaguddpod.sem}
spark.app.controllo.trattamento.sem=${spark.app.controllo.trattamento.sem}
spark.app.controllo.validato.sem=${spark.app.controllo.validato.sem}
spark.app.controllo.flagarea.sem=${spark.app.controllo.flagarea.sem}
spark.app.controllo.stato.sem=${spark.app.controllo.stato.sem}
spark.app.controllo.distr_azienda.sem=${spark.app.controllo.distr_azienda.sem}
spark.app.controllo.estrai_area.sem=${spark.app.controllo.estrai_area.sem}
spark.app.verbose.sem=${spark.app.verbose.sem}

spark.app.controllo.flaguddpod.sem.oracle=${spark.app.controllo.flaguddpod.sem.oracle}
spark.app.controllo.trattamento.sem.oracle=${spark.app.controllo.trattamento.sem.oracle}
spark.app.controllo.validato.sem.oracle=${spark.app.controllo.validato.sem.oracle}
spark.app.controllo.flagarea.sem.oracle=${spark.app.controllo.flagarea.sem.oracle}
spark.app.controllo.stato.sem.oracle=${spark.app.controllo.stato.sem.oracle}
spark.app.controllo.distr_azienda.sem.oracle=${spark.app.controllo.distr_azienda.sem.oracle}
spark.app.controllo.estrai_area.sem.oracle=${spark.app.controllo.estrai_area.sem.oracle}

spark.app.mot3_table=${spark.app.mot3_table}
spark.app.flussoquarti_table=${spark.app.flussoquarti_table}
spark.app.flussoquarti_table.oracle=${spark.app.flussoquarti_table.oracle}
spark.app.sem.oracle.praticheR_TBL=${spark.app.sem.oracle.praticheR_TBL}

spark.app.impala.url=${spark.app.impala.url}
spark.app.impala.jdbc.driver=${spark.app.impala.jdbc.driver}
spark.app.aggregazioni.file.sem.esclusi=${spark.app.aggregazioni.file.sem.esclusi}
spark.app.join.ternecommitted.sem.custom=${spark.app.join.ternecommitted.sem.custom}

spark.app.portale.usa_misure_noaggr1G=${spark.app.portale.usa_misure_noaggr1G}
spark.app.portale.path.base.misureEE=${spark.app.portale.path.base.misureEE}
spark.app.portale.path.base.storic.misure.tmp=${spark.app.portale.path.base.storic.misure.tmp}
spark.app.mongodb.usecollaudo=${spark.app.mongodb.usecollaudo}
spark.app.mongodb.connstr.produzione=${spark.app.mongodb.connstr.produzione}
spark.app.mongodb.connstr.collaudo=${spark.app.mongodb.connstr.collaudo}
spark.app.mongodb.suffix.collection=${spark.app.mongodb.suffix.collection}
spark.app.mongodb.writeconcern_write.produzione=${spark.app.mongodb.writeconcern_write.produzione}
spark.app.mongodb.writeconcern_journal.produzione=${spark.app.mongodb.writeconcern_journal.produzione}
spark.app.mongodb.dbgas.input=${spark.app.mongodb.dbgas.input}
spark.app.dettpod.aggregato.path=${spark.app.dettpod.aggregato.path}
spark.app.dettpod.aggregato.sem.path=${spark.app.dettpod.aggregato.sem.path}
spark.app.ammissibilita.1G.path=${spark.app.ammissibilita.1G.path}
spark.app.ammissibilita.2G.path=${spark.app.ammissibilita.2G.path}
spark.app.ammissibilita.checkAmmiOn=${spark.app.ammissibilita.checkAmmiOn}
spark.app.mongodb.delay=${spark.app.mongodb.delay}
spark.app.mongodb.mesiTracciaturaSpid=${spark.app.mongodb.mesiTracciaturaSpid}

spark.app.ingestione.flussoQuartiErcEri =${spark.app.ingestione.flussoQuartiErcEri }
spark.app.ingestione.flussoNoAgrrErcEri =${spark.app.ingestione.flussoNoAgrrErcEri }
spark.app.ingestione.flussoSmisErcEri =${spark.app.ingestione.flussoSmisErcEri }

#mev22_001
spark.aggregazioni.misure.orarie=${spark.aggregazioni.misure.orarie}
aggregazioni_misure_orarie_table=${aggregazioni_misure_orarie_table}
spark.controllo.queryPs1=${spark.controllo.queryPs1}
spark.controllo.queryPs11=${spark.controllo.queryPs11}
spark.controllo.queryPs2=${spark.controllo.queryPs2}
spark.controllo.queryPs3=${spark.controllo.queryPs3}
spark.controllo.queryPs4=${spark.controllo.queryPs4}
spark.controllo.queryDistrAziendaALL=${spark.controllo.queryDistrAziendaALL}
spark.controllo.queryDistrAziendaAll=${spark.controllo.queryDistrAziendaAll}
spark.app.mongodb.timeOut=${spark.app.mongodb.timeOut}
replycaName=${replycaName}
spark.app.dbMisure=${spark.app.dbMisure}
spark.app.ingestione.flagMSCK=${spark.app.ingestione.flagMSCK}

#MEV22-008
#puntamenti ai db di Cloudera per reperimento dati EE etl Mongo
#spark.app.mongodb.dbmisure =${#spark.app.mongodb.dbmisure }
spark.app.mongodb.dbmisure =${spark.app.mongodb.dbmisure }
spark.app.mongodb.dbforniture =${spark.app.mongodb.dbforniture }

#questi attributi permettono di definire un'altro enviroment to mongoo db nella cli utilizzare -ENV
# Collaudo
spark.app.mongodb.rsetenv =${spark.app.mongodb.rsetenv }
replicaname_env =${replicaname_env }
# Produzione
#spark.app.mongodb.rsetenv =${#spark.app.mongodb.rsetenv }
#replicaname_env =${#replicaname_env }
spark.app.mongodb.collection.misure_env=${spark.app.mongodb.collection.misure_env}
spark.app.mongodb.collection.forniture_env=${spark.app.mongodb.collection.forniture_env}

#SEMSPARK2
spark.app.sem_envPs1  =${spark.app.sem_envPs1  }
spark.app.sem_envPs11  =${spark.app.sem_envPs11  }
spark.app.sem_envPs2  =${spark.app.sem_envPs2  }
spark.app.sem_envPs3  =${spark.app.sem_envPs3  }
spark.app.sem_envPs4  =${spark.app.sem_envPs4  }
spark.app.env_creatViewTratt=${spark.app.env_creatViewTratt}
spark.app.sem_envQueryDistrAzienda =${spark.app.sem_envQueryDistrAzienda }
spark.app.sem_envQueryFlussoMisureQuartiTimeStampMaxC =${spark.app.sem_envQueryFlussoMisureQuartiTimeStampMaxC }
spark.app.controllo.n_intervalli=${spark.app.controllo.n_intervalli}



#nuovo ETL
spark.app.etl.mongodb.path.stage=${spark.app.etl.mongodb.path.stage}
spark.app.etl.mongodb.db.stage=${spark.app.etl.mongodb.db.stage}
spark.app.etl.mongodb.table.stage=${spark.app.etl.mongodb.table.stage}

spark.app.etl.mongodb.path.registro.load=${spark.app.etl.mongodb.path.registro.load}
spark.app.etl.mongodb.db.registro.load=${spark.app.etl.mongodb.db.registro.load}
spark.app.etl.mongodb.table.registro.load=${spark.app.etl.mongodb.table.registro.load}

#ingestione flussi EIN
spark.flusso.misure.quarti.flussi_in=${spark.flusso.misure.quarti.flussi_in}
spark.flusso.misure.report.flussi_in=${spark.flusso.misure.report.flussi_in}
spark.flusso.misure.reportdecompressione_in=${spark.flusso.misure.reportdecompressione_in}
spark.flusso.misure.ext.flussi_in=${spark.flusso.misure.ext.flussi_in}
spark.app.dbdest_in=${spark.app.dbdest_in}
spark.flusso.misure.quarti.flussi_in_table=${spark.flusso.misure.quarti.flussi_in_table}
spark.flusso.misure.report.flussi_in_table=${spark.flusso.misure.report.flussi_in_table}
spark.flusso.misure.ext.flussi_in_table =${spark.flusso.misure.ext.flussi_in_table }
spark.flusso.misure.reportdecompressione_in_table=${spark.flusso.misure.reportdecompressione_in_table}
spark.app.directory.root.2G.in=${spark.app.directory.root.2G.in}
spark.app.directory.root.1G.in=${spark.app.directory.root.1G.in}
spark.app.directory.tmp.2G.in=${spark.app.directory.tmp.2G.in}
spark.app.directory.tmp.1G.in=${spark.app.directory.tmp.1G.in}
spark.app.abilita.estensione=${spark.app.abilita.estensione}
spark.app.abilita.erceri=${spark.app.abilita.erceri}
#insert su ricalcolo
spark.app.aggregazioni.lista.terne=${spark.app.aggregazioni.lista.terne}
spark.app.aggregazioni.terne.escluse=${spark.app.aggregazioni.terne.escluse}
#FLUSSITECNICI
spark.app.dbdest_ft=${spark.app.dbdest_ft}
spark.flusso.misure.report.flussi_tecnici=${spark.flusso.misure.report.flussi_tecnici}
spark.flusso.misure.noaggr=${spark.flusso.misure.noaggr}
spark.flusso.misure.reportDecompressione_ft=${spark.flusso.misure.reportDecompressione_ft}
spark.flusso.misure.noaggr_table=${spark.flusso.misure.noaggr_table}
spark.flusso.misure.report_tecnici_table=${spark.flusso.misure.report_tecnici_table}
spark.flusso.misure.reportDecompressione_ft_table=${spark.flusso.misure.reportDecompressione_ft_table}
#directory cartelle flussi tecnici ingestione
spark.app.directory.tmp.2G.sm=${spark.app.directory.tmp.2G.sm}
spark.app.directory.tmp.2G.rt=${spark.app.directory.tmp.2G.rt}
spark.app.directory.tmp.1G.sm=${spark.app.directory.tmp.1G.sm}
spark.app.directory.tmp.1G.rt=${spark.app.directory.tmp.1G.rt}

#direcotry cartelle flussi tecnici decompressione
spark.app.directory.root.2G.sm=${spark.app.directory.root.2G.sm}
spark.app.directory.root.2G.rt=${spark.app.directory.root.2G.rt}
spark.app.directory.root.1G.sm=${spark.app.directory.root.1G.sm}
spark.app.directory.root.1G.rt=${spark.app.directory.root.1G.rt}

#AGGREGATOEIN
spark.app.controllo.flaguddpod.ein=${spark.app.controllo.flaguddpod.ein}
spark.app.controllo.trattamento.ein=${spark.app.controllo.trattamento.ein}
spark.app.controllo.stato.ein=${spark.app.controllo.stato.ein}
spark.app.controllo.validato.ein=${spark.app.controllo.validato.ein}
spark.app.controllo.flagarea.ein=${spark.app.controllo.flagarea.ein}
spark.app.controllo.distr_azienda.ein=${spark.app.controllo.distr_azienda.ein}
spark.app.dbdest_ein=${spark.app.dbdest_ein}
aggregazioni_misure_orarie_table_ein=${aggregazioni_misure_orarie_table_ein}
spark.aggregazioni.misure.orarie_ein=${spark.aggregazioni.misure.orarie_ein}
spark.app.perdita.tensione.ein.380=${spark.app.perdita.tensione.ein.380}
spark.app.perdita.tensione.ein.220=${spark.app.perdita.tensione.ein.220}
spark.app.perdita.tensione.ein.150=${spark.app.perdita.tensione.ein.150}
spark.app.perdita.tensione.ein.1_35=${spark.app.perdita.tensione.ein.1_35}
spark.app.perdita.tensione.ein.1=${spark.app.perdita.tensione.ein.1}
spark.app.basepath.ein=${spark.app.basepath.ein}
spark.app.dettpod.aggregato.ein.path=${spark.app.dettpod.aggregato.ein.path}
spark.app.elenco.pod.aggregato.ein.path=${spark.app.elenco.pod.aggregato.ein.path}
spark.app.dett.NET.aggregato.ein.path=${spark.app.dett.NET.aggregato.ein.path}
spark.aggregazioni.misure.orarie.dettagliopod_ein=${spark.aggregazioni.misure.orarie.dettagliopod_ein}
spark.aggregazioni.misure.orarie.dettagliopod_ein_table=${spark.aggregazioni.misure.orarie.dettagliopod_ein_table}
spark.aggregazioni.misure.orarie.ver_ein_table=${spark.aggregazioni.misure.orarie.ver_ein_table}
spark.app.aggregazioni.file.esclusi.ein=${spark.app.aggregazioni.file.esclusi.ein}
spark.app.aggregazioni.lista.terne.ein=${spark.app.aggregazioni.lista.terne.ein}
spark.aggregazioni.misure.am.ein=${spark.aggregazioni.misure.am.ein}
spark.aggregazioni.misure.am.ein.table=${spark.aggregazioni.misure.am.ein.table}

#MEV23-028SEMEIN
spark.app.aggregazioni.file.sem.esclusi_ein=${spark.app.aggregazioni.file.sem.esclusi_ein}
spark.app.join.ternecommitted.sem.custom_ein=${spark.app.join.ternecommitted.sem.custom_ein}
spark.app.controllo.flaguddpod.sem_ein=${spark.app.controllo.flaguddpod.sem_ein}
spark.app.controllo.trattamento.sem_ein=${spark.app.controllo.trattamento.sem_ein}
spark.app.controllo.validato.sem_ein=${spark.app.controllo.validato.sem_ein}
spark.app.controllo.flagarea.sem_ein=${spark.app.controllo.flagarea.sem_ein}
spark.app.controllo.stato.sem_ein=${spark.app.controllo.stato.sem_ein}
spark.app.controllo.distr_azienda.sem_ein=${spark.app.controllo.distr_azienda.sem_ein}
spark.app.controllo.estrai_area.sem_ein=${spark.app.controllo.estrai_area.sem_ein}
spark.app.verbose.sem_ein=${spark.app.verbose.sem_ein}
spark.app.basepath_ein=${spark.app.basepath_ein}
spark.app.dettpod.aggregato.sem.path_ein=${spark.app.dettpod.aggregato.sem.path_ein}
spark.app.elenco.pod.aggregato.path_ein=${spark.app.elenco.pod.aggregato.path_ein}
spark.app.dett.NET.aggregato.path_ein=${spark.app.dett.NET.aggregato.path_ein}
spark.aggregazioni.misure.orarie.dettpod_ein=${spark.aggregazioni.misure.orarie.dettpod_ein}
spark.aggregazioni.misure.orarie.dettpod_ein_table=${spark.aggregazioni.misure.orarie.dettpod_ein_table}
spark.app.sem_envPs1_ein =${spark.app.sem_envPs1_ein }
spark.app.sem_envPs11_ein =${spark.app.sem_envPs11_ein }
spark.app.sem_envPs2_ein =${spark.app.sem_envPs2_ein }
spark.app.sem_envPs3_ein =${spark.app.sem_envPs3_ein }
spark.app.sem_envPs4_ein =${spark.app.sem_envPs4_ein }
spark.app.env_creatViewTratt_ein =${spark.app.env_creatViewTratt_ein }
spark.app.sem_envQueryDistrAzienda_ein =${spark.app.sem_envQueryDistrAzienda_ein }
spark.app.sem_envQueryFlussoMisureQuartiTimeStampMaxC_ein =${spark.app.sem_envQueryFlussoMisureQuartiTimeStampMaxC_ein }
spark.app.mot3_table=${spark.app.mot3_table}
spark.aggregazioni.pod_cons.am.sem.commit_ein =${spark.aggregazioni.pod_cons.am.sem.commit_ein }
spark.aggregazioni.misure.orarie.ver_ein_p =${spark.aggregazioni.misure.orarie.ver_ein_p }
spark.app.verbose.tabelle =${spark.app.verbose.tabelle }

#MEV24-035
spark.aggregazioni.misure.quartorarie=${spark.aggregazioni.misure.quartorarie}
aggregazioni_misure_quartorarie_table=${aggregazioni_misure_quartorarie_table}
#spark.app.dettpod.aggregato.path=${#spark.app.dettpod.aggregato.path}
#spark.aggregazioni.misure.quartorarie.dettagliopod=${#spark.aggregazioni.misure.quartorarie.dettagliopod}
#spark.aggregazioni.misure.quartorarie.dettagliopod_table=${#spark.aggregazioni.misure.quartorarie.dettagliopod_table}
spark.aggregazioni.misure.am=${spark.aggregazioni.misure.am}
spark.aggregazioni.misure.am.table=${spark.aggregazioni.misure.am.table}
#aggregazioni_misure_quartorarie_table_ein=${#aggregazioni_misure_quartorarie_table_ein}
#spark.aggregazioni.misure.quartorarie_ein=${#spark.aggregazioni.misure.quartorarie_ein}
#spark.aggregazioni.misure.am.ein=${#spark.aggregazioni.misure.am.ein}
#spark.aggregazioni.misure.am.ein.table=${#spark.aggregazioni.misure.am.ein.table}
#spark.aggregazioni.misure.quartorarie.ver_ein_table=${#spark.aggregazioni.misure.quartorarie.ver_ein_table}
#spark.app.dettpod.aggregato.ein.path=${#spark.app.dettpod.aggregato.ein.path}
#spark.app.elenco.pod.aggregato.ein.path=${#spark.app.elenco.pod.aggregato.ein.path}
#spark.app.dett.NET.aggregato.ein.path=${#spark.app.dett.NET.aggregato.ein.path}


hive.db.mongodbs=${hive.db.mongodbs}
hive.table.rcu.rcu_azienda_p=${hive.table.rcu.rcu_azienda_p}
hive.table.rcu.rcu_fornitura_p=${hive.table.rcu.rcu_fornitura_p}
hive.table.rcu.rcu_pod_p=${hive.table.rcu.rcu_pod_p}
hive.table.rcu.rcu_pod_stato_p=${hive.table.rcu.rcu_pod_stato_p}
hive.table.rcu.rcu_residenza_p=${hive.table.rcu.rcu_residenza_p}
hive.table.rcu.rcu_tariffa_p=${hive.table.rcu.rcu_tariffa_p}
hive.table.rcus.rcus_fornitura_p=${hive.table.rcus.rcus_fornitura_p}
hive.table.rcus.rcus_podstato_p=${hive.table.rcus.rcus_podstato_p}
hive.table.mongodbs.forniture=${hive.table.mongodbs.forniture}
hive.table.mongodbs.forniture_info=${hive.table.mongodbs.forniture_info}
hive.table.swtch.prt_se_p=${hive.table.swtch.prt_se_p}
hive.table.userappl.t001_app_prt_pratiche_p=${hive.table.userappl.t001_app_prt_pratiche_p}
hive.table.mongodbs.switch=${hive.table.mongodbs.switch}
hive.table.rcu.rcu_pod_misure_p=${hive.table.rcu.rcu_pod_misure_p}
hive.table.rcu.rcu_pod_tecn_p=${hive.table.rcu.rcu_pod_tecn_p}
hive.table.rcus.rcus_podtecn_p=${hive.table.rcus.rcus_podtecn_p}
hive.table.mongodbs.gdm=${hive.table.mongodbs.gdm}
hive.table.rcu.rcu_pod_distr_p=${hive.table.rcu.rcu_pod_distr_p}
hive.table.mongodbs.rcu_pod_distr=${hive.table.mongodbs.rcu_pod_distr}
hive.table.rcu.rcu_fasce_misuratore_2g_p=${hive.table.rcu.rcu_fasce_misuratore_2g_p}
hive.table.rcu.rcu_misuratore_2g_p=${hive.table.rcu.rcu_misuratore_2g_p}
hive.table.mongodbs.fasce=${hive.table.mongodbs.fasce}
hive.table.rcu.rcu_indirizzo_p=${hive.table.rcu.rcu_indirizzo_p}
hive.table.mongodbs.pod=${hive.table.mongodbs.pod}
hive.table.mongodbs.forniture_elettriche=${hive.table.mongodbs.forniture_elettriche}
hive.table.rcu.rcu_clientefinale_p=${hive.table.rcu.rcu_clientefinale_p}
hive.table.tde.tde_vuln_p=${hive.table.tde.tde_vuln_p}
hive.table.rcu.rcu_codice_offerta_p=${hive.table.rcu.rcu_codice_offerta_p}
hive.table.forniture=${hive.table.forniture}
hive.table.forniture_info=${hive.table.forniture_info}
hive.table.pod=${hive.table.pod}
hive.table.forniture_elettriche=${hive.table.forniture_elettriche}
hive.table.fasce=${hive.table.fasce}
hive.table.rcu_pod_distr=${hive.table.rcu_pod_distr}
hive.table.gdm=${hive.table.gdm}
hive.table.switch=${hive.table.switch}

mongodb.conf.readPreference=${mongodb.conf.readPreference}
mongodb.conf.writeConcern=${mongodb.conf.writeConcern}
mongodb.conf.replaceDocument=${mongodb.conf.replaceDocument}
mongodb.collection.misureGas3m=${mongodb.collection.misureGas3m}
mongodb.db.name=${mongodb.db.name}
mongodb.db.uri=${mongodb.db.uri}
mongodb.collection.prova.uno=${prova.uno}
mongodb.collection.misureElettriche3MNewSchema=${mongodb.collection.misureElettriche3MNewSchema}
mongodb.collection.misureElettriche33MNewSchema=${mongodb.collection.misureElettriche33MNewSchema}