agg.db=agg
rcugas.db=rcugas
dailyConsumption.tableName=daily_consumption_agg

isilon.basepath.tmp=/mnt/isilonshare1_Parallelo/AGG_TMP
isilon.basepath.out=/mnt/Settlement
hdfs.tmp.basepath=/apps/AGG/tmp
hdfs.output.basepath=/user/hive/warehouse/au.db/misure_gas_au/agg/aggregatore_info_log