# Root logger option
log4j.rootLogger=WARN, stdout, file
log4j.logger.mail=WARN, mailLog

log4j.additivity.mail=false

# Direct log messages to a log file
log4j.appender.file=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.file.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
log4j.appender.file.rollingPolicy.FileNamePattern=${isilon.deploy.path}/log/ammissibilita-rendiconti-%d{yyyy-MM-dd}.log
log4j.appender.file.layout=org.apache.log4j.PatternLayout
log4j.appender.file.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Direct log messages to stdout
log4j.appender.stdout=org.apache.log4j.ConsoleAppender
log4j.appender.stdout.Target=System.out
log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
log4j.appender.stdout.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} %-5p %c{1}:%L - %m%n

# Direct log messages to another log file for mail
log4j.appender.mailLog=org.apache.log4j.rolling.RollingFileAppender
log4j.appender.mailLog.rollingPolicy=org.apache.log4j.rolling.TimeBasedRollingPolicy
log4j.appender.mailLog.rollingPolicy.FileNamePattern=${isilon.mailLog.path}/ammissibilita-rendiconti-mail-%d{yyyy-MM-dd}.log
log4j.appender.mailLog.layout=org.apache.log4j.PatternLayout
log4j.appender.mailLog.layout.ConversionPattern=%d{yyyy-MM-dd HH:mm:ss} - %m%n

# Settings to quiet third party logs that are too verbose
log4j.logger.org.eclipse.jetty=WARN
log4j.logger.org.eclipse.jetty.util.component.AbstractLifeCycle=ERROR
log4j.logger.org.apache.spark.repl.SparkIMain$exprTyper=WARN
log4j.logger.org.apache.spark.repl.SparkILoop$SparkILoopInterpreter=WARN