recovery.csv.path=${hdfs.deploy.path}/recovery.csv

rzg1Zip.input.path=${isilon.rzg1Zip.inputPath}
rzg1Amm.output.path=${isilon.rzg1Amm.outputPath}

cig.aggregatoTotale.tableName=${cig.db}.${aggregatoTotale.tableName}
cig.reportAmmissibilita.rzg1.basepath=${cig.reportAmmissibilita.rzg1.basepath}
cig.reportAmmissibilita.rzg1.tableName=${cig.db}.${reportAmmissibilita.tableName}
cig.indennizziRzg2.basepath=${cig.indennizziRzg2.basepath}
cig.indennizziRzg2.tableName=${cig.db}.${indennizziRzg2.tableName}
cig.deltaEuro.basepath=${cig.deltaEuro.basepath}
cig.deltaEuro.tableName=${cig.db}.${deltaEuro.tableName}

rule.zip.alreadyComputed.enabled=true
rule.zip.alreadyTransmitted.enabled=true
rule.zip.checkZipAndCsvNames.enabled=true
rule.zip.checkPiva.enabled=true
rule.zip.checkCsvEncoding.enabled=true
rule.zip.checkNumberOfCsvFields.enabled=true

rule.csv.checkHeader.enabled=true
rule.csv.checkDate.enabled=true
rule.csv.checkIdIndennizzo.enabled=true
rule.csv.checkPivaId.enabled=true
rule.csv.checkPivaUdd.enabled=true
rule.csv.checkRagSocId.enabled=true
rule.csv.checkRagSocUdd.enabled=true
rule.csv.checkPivaIdConsistency.enabled=true
rule.csv.checkPivaUddConsistency.enabled=true

rule.validateOM1.enabled=true
rule.validateOM2.enabled=true
rule.validateOM3.enabled=true
rule.checkAtLeastOneOMIsValued.enabled=true
rule.validateIdIndennizzo.enabled=true