#Attivazione perimetro
perimetroSwgS.bool=false
perimetroSwgA.bool=false
perimetroUigS.bool=false
perimetroUigA.bool=false
perimetroVtgS.bool=false

#Attivazione aggregazione
aggregazioneUdbSwgS.bool=false
aggregazioneUdbSwgA.bool=false
aggregazioneUdbUigS.bool=false
aggregazioneUdbUigA.bool=false
aggregazioneUdbVtgS.bool=false
aggregazioneUdbVtgA.bool=false

aggregazioneUddSwgS.bool=false
aggregazioneUddSwgA.bool=false
aggregazioneUddUigS.bool=false
aggregazioneUddUigA.bool=false
aggregazioneUddVtgS.bool=false
aggregazioneUddVtgA.bool=false

#Attivazione pubblicazione
pubblicazioneUdbSwgS.bool=false
pubblicazioneUdbSwgA.bool=false
pubblicazioneUdbUigS.bool=false
pubblicazioneUdbUigA.bool=false
pubblicazioneUdbVtgS.bool=false
pubblicazioneUdbVtgA.bool=false

pubblicazioneUddSwgS.bool=false
pubblicazioneUddSwgA.bool=false
pubblicazioneUddUigS.bool=false
pubblicazioneUddUigA.bool=false
pubblicazioneUddVtgS.bool=false
pubblicazioneUddVtgA.bool=false

#SWG and UIG execution day
execution.day = 28

#VTG A execution day
execution.day.vtga = 3

#Sgs db name
sgs.db = ${hive.sgs.db}

#Sqoop tables
perimetroSwgSRaw.basepath=${sqoop.import.path}/sgs_perimetro_swg_s_raw_c
perimetroSwgARaw.basepath=${sqoop.import.path}/sgs_perimetro_swg_a_raw_c
perimetroUigSRaw.basepath=${sqoop.import.path}/sgs_perimetro_uig_s_raw_c
perimetroUigARaw.basepath=${sqoop.import.path}/sgs_perimetro_uig_a_raw_c
perimetroVtgSRaw.basepath=${sqoop.import.path}/sgs_perimetro_vtg_s_raw_c

perimetroSwgSRaw.table=sgs_perimetro_swg_s_raw_c
perimetroSwgARaw.table=sgs_perimetro_swg_a_raw_c
perimetroUigSRaw.table=sgs_perimetro_uig_s_raw_c
perimetroUigARaw.table=sgs_perimetro_uig_a_raw_c
perimetroVtgSRaw.table=sgs_perimetro_vtg_s_raw_c

#Perimetro tables
perimetroSwgS.basepath=${sgs.path.hdfs}/sgs_perimetro_swg_s
perimetroSwgA.basepath=${sgs.path.hdfs}/sgs_perimetro_swg_a
perimetroUigS.basepath=${sgs.path.hdfs}/sgs_perimetro_uig_s
perimetroUigA.basepath=${sgs.path.hdfs}/sgs_perimetro_uig_a
perimetroVtgS.basepath=${sgs.path.hdfs}/sgs_perimetro_vtg_s

perimetroSwgS.table=sgs_perimetro_swg_s
perimetroSwgA.table=sgs_perimetro_swg_a
perimetroUigS.table=sgs_perimetro_uig_s
perimetroUigA.table=sgs_perimetro_uig_a
perimetroVtgS.table=sgs_perimetro_vtg_s

#Rcu Tables
rcuGasVarTrattamentoP.basepath = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_TRATTAMENTO_p
rcuGasVarMisuratoreP.basepath = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_MISURATORE_p
rcuGasVarConvertitoreP.basepath = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_VAR_CONVERTITORE_p
rcuGasConnessioniDistr2P.basepath = /user/hive/warehouse/rcugas.db/RCUGAS/rcugas_connessioni_distr2_p
rcuGasPdrP.basepath = /user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_PDR_p

#Reg climatica
prtIstatRegioneClimaticaP.basepath = /user/hive/warehouse/acquirente_unico/sqoop_portcons/PRT.ISTAT_REGIONE_CLIMATICA_p

#exec track
executionTrack.basepath = ${sgs.path.hdfs}/sgs_execution_track

#consumptions
dailyConsumption.table=agg.daily_consumption_agg
dailyConsumption.basepath=/user/hive/warehouse/au.db/misure_gas_au/agg/daily_consumption_agg
dailyConsumptionEsclusi.table = agg.daily_consumption_agg_esclusi
dailyConsumptionEsclusi.basepath = /user/hive/warehouse/au.db/misure_gas_au/agg/daily_consumption_agg_esclusi
dailyConsumptionIncoerenti.table = agg.daily_consumption_agg_incoerenti
dailyConsumptionIncoerenti.basepath = /user/hive/warehouse/au.db/misure_gas_au/agg/daily_consumption_agg_incoerenti

#aggregation
aggregatoreInfoDett.basepath = ${sgs.path.hdfs}/sgs_aggregatore_info_dett
aggregatoreInfoDett.table =${hive.sgs.db}.sgs_aggregatore_info_dett

#publish
xmlOutput.basepath = ${xml.output.path}
xsd.basepath = ${deploy.path}/xsd/FlussiDatiMisuraPrelievoGAS-FlussoSGS.xsd
pdrPerFile.constant = 10
pubblicazioneInfoDett.basepath=${sgs.path.hdfs}/sgs_pubblicazione_info_dett
pubblicazioneInfoDett.table=${hive.sgs.db}.sgs_pubblicazione_info_dett
pubblicazioneInfo.basepath=${sgs.path.hdfs}/sgs_pubblicazione_info
pubblicazioneInfo.table=${hive.sgs.db}.sgs_pubblicazione_info
sgsReport.path=${sgs.path.hdfs}/sgs_report_1
sgsReport.table=${hive.sgs.db}.sgs_report_1