measures.rootpath=/user/hive/warehouse/au.db/misure_gas_au/cmg_gas
agg.output.rootpath=/user/eng_test/agg
rcugasMassivoP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_massivo_p
rcugasConnessioniDistr2Remi.basepath=/user/hive/warehouse/acquirente_unico/sqoop_portcons/RCUGAS.RCUGAS_CONNESSIONI_DISTR2_REMI_p
rcugasPdrDatiPrelievo.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_pdr_datiprelievo_p
rcugasFornituraP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_fornitura_p
rcugasSospensioniP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_sospensioni_p

rcugasBilanciamentoP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_bilanciamento_p
rcugasUdbP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_udb_p
rcugasRemiAnagraficaP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_remi_anagrafica_p
rcugasRemiAggregazioneP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_remi_aggregazione_p
rcugasItP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_it_p
rcugasGestTrasportoP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_gesttrasporto_p
rcuAziendaP.basepath=/user/hive/warehouse/rcugas_bck.db/rcu_azienda_p

rcugasDistributoreP.basepath=/user/hive/warehouse/rcugas_bck.db/v_agg_rcugas_distributore_p
rcuGasVarPrelAnnuoP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_var_prel_annuo_p
rcuGasVarProfiloP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_var_profilo_p
rcuGasVarTrattamentoP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_var_trattamento_p

rcuGasVarMisuratoreP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_var_misuratore_p
rcuGasVarConvertitoreP.basepath=/user/hive/warehouse/rcugas_bck.db/agg_rcugas_var_convertitore_p
settlegas.rootpath=/user/hive/warehouse/settle_gas.db
agg.db=eng_test

strong.exclusion.backuptable.basepath=/user/hive/warehouse/eng_test.db/strong_exclusion_backuptable_agg
deploy.path.strong.exclusion = /user/eng_test/agg/deploy
deploy.path.strong.forceExclusion=/user/eng_test/agg/deploy/force_exclusion

dataset.numberPartitions=3000

deploy.path= /home/eng_test/agg/deploy
deploy.path.hdfs = /user/eng_test/agg/deploy

hive.tdg=eng_test
hive.tdglocation=/user/eng_test/hive/tdg_tdg4_coeffk
hive.sqoop.location=/user/eng_test/hive

tdgCoeffK.basepath=/user/eng_test/hive/tdg_tdg4_coeffk
tdgCoeffK.table=eng_test.tdg_tdg4_coeffk

connection.string.oracle = /user/eng_test/agg/oracle_collaudo.properties
