package it.eng.au.portale_consumi_ee.model.rcus

case class RcusFornituraPModel(
                                n_id_scheda: String = null,
                                n_id_fornitura: String = null,
                                n_id_pod: String = null,
                                n_id_cliente: String = null,
                                d_inizio_titolarita: String = null,
                                d_fine_titolarita: String = null,
                                t_cod_contratto: String = null,
                                d_stipula_contratto: String = null,
                                d_mese_rinnovo: String = null,
                                n_iva: String = null,
                                b_disalimentabilita: String = null,
                                t_tariffa_distr: String = null,
                                t_codice_ateco: String = null,
                                n_id_fornitore: String = null,
                                t_ruolo_fornitore: String = null,
                                t_tipo_mercato: String = null,
                                b_salvaguardia: String = null,
                                t_bonus_sociale: String = null,
                                d_inizio_bonus: String = null,
                                d_fine_bonus: String = null,
                                t_comunic_bonus: String = null,
                                n_imposte: String = null,
                                n_id_indir_esazione: String = null,
                                n_id_indir_comunic: String = null,
                                t_nota: String = null,
                                d_aggiornamento: String = null,
                                d_archiviazione: String = null,
                                n_id_traccia: String = null,
                                n_id_s_prec: String = null,
                                n_id_s_succ: String = null,
                                b_valido: String = null,
                                t_diritto_tutela: String = null,
                                t_codice_ufficio: String = null,
                                t_pagamento_iva: String = null,
                                t_addiz_provinciale: String = null,
                                t_addiz_comunale: String = null,
                                t_telefono: String = null,
                                t_iva: String = null,
                                t_imposte: String = null
                              )
