package it.eng.au.portale_consumi_ee.model.rcus

case class RcusPodtecnPModel(
                              n_id_scheda: String = null,
                              n_id_pod: String = null,
                              n_potenza_disponibile: String = null,
                              n_potenza_impegnata: String = null,
                              n_tensione: String = null,
                              t_tipo_misuratore: String = null,
                              n_k_trasformazione: String = null,
                              d_inst_misuratore: String = null,
                              d_rimoz_misuratore: String = null,
                              t_nota: String = null,
                              d_aggiornamento: String = null,
                              d_archiviazione: String = null,
                              n_id_traccia: String = null,
                              n_id_s_prec: String = null,
                              n_id_s_succ: String = null,
                              b_valido: String = null,
                              n_num_cifre_ea: String = null,
                              n_num_cifre_er: String = null,
                              n_k_trasfor_att: String = null,
                              n_k_trasfor_rea: String = null,
                              n_k_trasfor_pot: String = null,
                              t_mat_misuratore_att: String = null,
                              t_mat_misuratore_rea: String = null,
                              t_mat_misuratore_pot: String = null,
                              d_inst_misurator_att: String = null,
                              d_inst_misurator_rea: String = null,
                              d_inst_misurator_pot: String = null,
                              n_num_cifre_att: String = null,
                              n_num_cifre_rea: String = null,
                              n_num_cifre_pot: String = null,
                              b_presenza_mis: String = null,
                              b_gest_forfait: String = null,
                              t_tipo_pod: String = null,
                              d_fine_tipo_pod: String = null,
                              d_oper_misurator_att: String = null,
                              d_oper_misurator_rea: String = null,
                              d_oper_misurator_pot: String = null,
                              t_motivazione: String = null
                             )
