### Parametri Job
# SBG
job.params.offset_sbg = 1
# Abilita/disabilita inclusioni ed esclusioni (TRUE/FALSE)
job.params.inclusion_sbg_enabled = TRUE
job.params.exclusion_sbg_enabled = TRUE
# Percorso file (HDFS)
file.path.inclusioni_sbg = ${deploy.path.properties}/inclusi_sbg.csv
file.path.esclusioni_sbg = ${deploy.path.properties}/esclusi_sbg.csv

# AGG
job.params.executionid_agg = 1706269610555
# Abilita/disabilita inclusioni ed esclusioni (TRUE/FALSE)
job.params.inclusion_agg_enabled = TRUE
job.params.exclusion_agg_enabled = TRUE
# Percorso file (HDFS)
file.path.inclusioni_agg = ${deploy.path.properties}/inclusi_agg.csv
file.path.esclusioni_agg = ${deploy.path.properties}/esclusi_agg.csv
# AGG BIT
job.params.data_back_in_time =
job.params.annomese_da =
job.params.annomese_a =

## Tabelle Hive
# Input
# SBG
hive.table.sbg_incoerenti = eng_test.daily_consumption_sbg_incoerenti_mid
hive.table.sbg_esclusi = eng_test.daily_consumption_sbg_esclusi_mid
hive.table.sbg_daily_consumption = eng_test.daily_consumption_sbg_mid
# AGG
hive.table.agg_incoerenti = eng_test.daily_consumption_agg_incoerenti_mid
hive.table.agg_esclusi = eng_test.daily_consumption_agg_esclusi_mid
hive.table.agg_daily_consumption = eng_test.daily_consumption_agg_mid
# Output
hive.table.mid_contatori = eng_test.mid_contatori
hive.table.mid_aggregatore_info = eng_test.mid_aggregatore_info

###################
### Pubblicazione
# file properties alpha
file.path.mid_alpha_valori = ${deploy.path.properties}/valori_alpha.csv

## Mid1
# posizione file output
file.path.mid1 = /mnt/isilonshare1_Parallelo/MID/AGG/AGG4
hive.table.mid1_dettaglio = eng_test.mid_mid1_dettaglio

# file esclusioni
file.path.mid1_esclusioni_pdr = ${deploy.path.properties}/excl_MID1_PDR_list.csv
file.path.mid1_esclusioni_distr = ${deploy.path.properties}/excl_MID1_DISTR_list.csv
file.path.mid1_esclusioni_tratt = ${deploy.path.properties}/excl_MID1_TRATT_list.csv
file.path.mid1_esclusioni_annomese = ${deploy.path.properties}/excl_MID1_AM_list.csv
# parametri
# preparazione (step1)
job.param.mid1_annomese_da = 202311
job.param.mid1_annomese_a = 202312
job.param.mid1_soglia = 1
# pubblicazione (step2)
job.param.mid1_executionid_dett = TODO
job.param.mid1_split = 80000
job.param.mid1_session = SESSION_MID1

## Mid2
file.path.mid2 = /mnt/isilonshare1_Parallelo/MID/TDG/TDG5/TDG5_80198650584
hive.table.mid2_dettaglio = eng_test.mid_mid2_dettaglio
hive.table.rcu_azienda_p = rcu.rcu_azienda_p
hive.table.rcugas_connessioni_distr2_remi_p = rcugas.rcugas_connessioni_distr2_remi_p
hive.table.variazioni_soc = atg.dd_variazioni_soc

# file esclusioni
file.path.mid2_esclusioni_pdr = ${deploy.path.properties}/excl_MID2_PDR_list.csv
file.path.mid2_esclusioni_distr = ${deploy.path.properties}/excl_MID2_DISTR_list.csv
file.path.mid2_esclusioni_tratt = ${deploy.path.properties}/excl_MID2_TRATT_list.csv
file.path.mid2_esclusioni_annomese = ${deploy.path.properties}/excl_MID2_AM_list.csv
# parametri
# preparazione (step1)
job.param.mid2_annomese_da = 202311
job.param.mid2_annomese_a = 202312
job.param.mid2_soglia = 1
# pubblicazione (step2)
job.param.csea_piva = 80198650584
job.param.mid2_executionid_dett = TODO
job.param.mid2_split = 80000
job.param.mid2_session = SESSION_MID2

####
# Reportistica
hive.table.mid_report1 = eng_test.mid_report1
hive.table.mid_report2 = eng_test.mid_report2


####################
### Path deploy
deploy.path.local = /home/eng_test/MID/gas/job
deploy.path.logs = /home/eng_test/MID/gas/logs
deploy.path.hdfs = /user/eng_test/MID/gas
deploy.path.properties = /user/eng_test/MID/gas/properties

# User per lancio script hive
system.user = eng_test
