package it.eng.au.aggregatoreConsumiSbg.controller.impl.incoerenti.confNoConf

import it.eng.au.aggregatoreConsumiSbg.controller.impl.incoerenti.traits.UddIncoerentiTraitSbg
import it.eng.au.aggregatoreConsumiSbg.controller.traits.IncoerentiConfNoConfTraitSbg

object UddIncoerentiConfNoConf extends IncoerentiConfNoConfTraitSbg with UddIncoerentiTraitSbg