#PYTHON IMPORT
daily.consumption.hdfs.path=/user/eng_test/sbg/daily_consumption_sbg2
py.hive.table.sbgmisure.db=eng_test
py.hive.table.sbgmisure.name=calcolo_consumi_sbg

#SPARK SUBMIT
isilon.path=/home/eng_test/clg/test
month.offset=2
sbg.type=POST
num.csv.lines=110000
sbgmisure-hdfs-path=/user/hive/warehouse/eng_test.db/calcolo_consumi_sbg
daily.consumption.table.name=eng_test.daily_consumption_sbg2
isilon.output.path=/mnt/settlementSYN_parallelo
hdfs.output.basepath.infoLog=/user/hive/warehouse/eng_test.db/aggregatore_info_log_clg