hadoop.username=sii_misure
sqoop.config.path=/apps/deploy/job.properties
gse.db=gse
dataman.db=gse_bi
hdfs.output.path=/user/hive/warehouse/gse.db
hdfs.deploy.path=/apps/GSE/deploy/calcolo_annuale
isilon.deploy.path=/home/sii_misure/GSE/deploy/calcolo_annuale
sh.mainone.path=/mnt/isilonshare1/Software_1/EE/sviluppi_misure/ELT_DATAMAN_GSE/script
