DROP TABLE misuregas.RCUGAS_PDR_DATIPRELIEVO;
CREATE TABLE misuregas.RCUGAS_PDR_DATIPRELIEVO stored as parquet as 
Select RCUGAS_PDR_DATIPRELIEVO.n_id_pdr,RCUGAS_PDR_DATIPRELIEVO.t_cod_cat_uso
FROM
(select
n_id_pdr,Max(T_ANNO) as T_ANNO
from
RCUGAS.RCUGAS_PDR_DATIPRELIEVO_p
group by n_id_pdr) as RCUGAS_PDR_DATIPRELIEVO1
join RCUGAS.RCUGAS_PDR_DATIPRELIEVO_p  as RCUGAS_PDR_DATIPRELIEVO on
RCUGAS_PDR_DATIPRELIEVO.n_id_pdr=RCUGAS_PDR_DATIPRELIEVO1.n_id_pdr
and  nvl(RCUGAS_PDR_DATIPRELIEVO.T_ANNO,'')=nvl(RCUGAS_PDR_DATIPRELIEVO1.T_ANNO,'');