isilon.deploy.path=/home/sii_misure_gas/CIG
hdfs.deploy.path=/apps/CIG

calcoloIndennizzi.isilon.deploy.path=${isilon.deploy.path}/calcolo_indennizzi/deploy
pubblicazioneIndennizzi.isilon.deploy.path=${isilon.deploy.path}/pubblicazione_indennizzi/deploy
ammissibilitaRendiconti.isilon.deploy.path=${isilon.deploy.path}/ammissibilita_rendiconti/deploy
pubblicazioneRendiconti.isilon.deploy.path=${isilon.deploy.path}/pubblicazione_rendiconti/deploy

calcoloIndennizzi.hdfs.deploy.path=${hdfs.deploy.path}/calcolo_indennizzi/deploy
pubblicazioneIndennizzi.hdfs.deploy.path=${hdfs.deploy.path}/pubblicazione_indennizzi/deploy
ammissibilitaRendiconti.hdfs.deploy.path=${hdfs.deploy.path}/ammissibilita_rendiconti/deploy
pubblicazioneRendiconti.hdfs.deploy.path=${hdfs.deploy.path}/pubblicazione_rendiconti/deploy