<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../def_dati_tecnici.xsd"/>
	<xs:include schemaLocation="../def_cliente.xsd"/>
	<xs:include schemaLocation="../def_identificativi.xsd"/>
	<xs:element name="Prestazione">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IdentificativiRichiesta" type="IdentificativiRichiestaBase"/>
				<xs:sequence minOccurs="1" maxOccurs="unbounded">
					<xs:element name="DatiPdR" type="DatiPdRAutoletturaValidazione"/>
				</xs:sequence>
			</xs:sequence>
			<xs:attribute name="cod_servizio" type="xs:string" use="required" fixed="TAS"/>
			<xs:attribute name="cod_flusso" type="xs:string" use="required" fixed="0150"/>
		</xs:complexType>
	</xs:element>
</xs:schema>
