# proprietà processo
output.file.csv_max_row=10000
# 25MB
output.file.zip_max_byte_size=25000000
output.file.temporary_path=/mnt/isilonshare1/CCE/tmpOutPath/
output.file.path=/mnt/isilonshare1/CCE/outPath/

# tabelle hive
hive.table.cceRichiestaPod=cce.cce_richiesta_pod
hive.table.cceRichiestaFiltro=cce.cce_richiesta_filtro
hive.table.cceEsito=cce.cce_esito
hive.table.cceEsitoExport=cce.cce_esito_export
hive.table.cceCalcoloCa=cce.cce_calcolo_ca
hive.table.cceCalcoloCaFlussi=cce.cce_calcolo_ca_flussi
# input
hive.table.cceCalcoloAnagrafica=cce.cce_calcolo_anag
hive.table.cceCalcoloP=cce.cce_calcolo_p
hive.table.cceCalcoloPein=cce.cce_calcolo_p_ein
hive.table.cceCalcoloPR=cce.cce_calcolo_pr
hive.table.cceCalcoloPRein=cce.cce_calcolo_pr_ein
hive.table.cceCalcoloTrattamento=cce.cce_calcolo_trattamento
hive.table.cceCalcTrack=cce.cce_calc_track


# properties per script SH (non necessario riportarle su params.properties)
# tabelle oracle
oracle.table.cceRichiestaPod=cce.cce_richiesta_pod
oracle.table.cceRichiestaFiltro=cce.cce_richiesta_filtro
oracle.table.cceEsito=cce.cce_esito
oracle.table.cceEsitoStaging=cce.cce_esito_stg
# tabelle hive per hcatalog
sqoop.db.import=cce
sqoop.table.cceRichiestaPod=cce_richiesta_pod
sqoop.table.cceRichiestaFiltro=cce_richiesta_filtro
sqoop.table.cceEsito=cce_esito_export

# percorsi rilascio e properties
# hdfs
deploy.path.hdfs=/apps/cce/pubblicazione
sqoop.config.path=/apps/deploy/job.properties
# local-linux
deploy.path.local=/mnt/isilonshare1/Software_1/cce/pubblicazione
deploy.path.logs=/mnt/isilonshare1/Software_1/cce/pubblicazione/logs
# user
hadoop_username=sii_misure_gas
