# HIVE
hive.cmg_ee=cmg_ee
hive.rcu=rcu
hive.rcus=rcus
hive.au=au
hive.table.report_ammissibilita_file=report_ammissibilita_file_ee
hive.table.report_decompressione_elt=report_decompressione
hive.table.report_ammissibilita_file_ee_tracking=report_ammissibilita_file_ee_tracking
hive.table.report_ammissibilita_pod_tracking=report_ammissibilita_pod_tracking
hive.table.report_ammissibilita_file_ee_tracking_staging=report_ammissibilita_file_ee_tracking_staging
hive.table.report_ammissibilita_pod_tracking_staging=report_ammissibilita_pod_tracking_staging
hive.location=/user/hive/warehouse/au.db/misure_ee_au
hive.rculocation=/user/hive/warehouse/rcu.db

hive.sqoop.location=/user/hive/warehouse/acquirente_unico/sqoop

# ISILON
root.path=/mnt/isilonshare1
sync.root=/mnt/isilonshare1
sync.1g=/TME_SYNC_Produzione_TMP
sync.2g=/2G_SYNC_Produzione_TMP
sync.dest.root=/mnt
sync.dest.1g=/TME_SYNC_Produzione
sync.dest.2g=/2G_SYNC_Produzione
tmp1G.path=/TMP_1Gb/isilonshare1G
tmp2G.path=/TMP_2Gb/isilonshare
merge.report.tracking.folder=${root.path}/report_ammissibilita_ee_tracking_folder

# DEPLOY
deploy.path=/mnt/isilonshare1/Software/EE
deploy.publish_report_script.path=${deploy.path}/bin/publish_reports
schedulazioni.path=/home/sii_misure/schedulazioni
schedulazioni.pipeline.path=${schedulazioni.path}/pipeline

# SPARK
deploy.mode=client
spark.num.executors=50
spark.executor.cores=6
spark.executor.memory=28G
spark.driver.cores=6
spark.driver.memory=28G

