isilon.rzg1Zip.inputPath=/mnt/Settlement/CIG/CIG1
isilon.rzg1Amm.outputPath=/mnt/Settlement/CIG/CIG1

cig.db=cig
aggregatoTotale.tableName=cig_aggregato_totale
cig.reportAmmissibilita.rzg1.basepath=/user/hive/warehouse/cig.db/cig_report_ammissibilita_rzg1
reportAmmissibilita.tableName=cig_report_ammissibilita_rzg1
cig.indennizziRzg2.basepath=/user/hive/warehouse/cig.db/cig_indennizzi_rzg2
indennizziRzg2.tableName=cig_indennizzi_rzg2
cig.deltaEuro.basepath=/user/hive/warehouse/cig.db/cig_delta_euro
deltaEuro.tableName=cig_delta_euro

isilon.deploy.path=/home/sii_misure_gas/CIG/ammissibilita_rendiconti/deploy
isilon.mailLog.path=/mnt/isilonshare1/Software_1/CIG/ammissibilita_rendiconti/log
hdfs.deploy.path=/apps/CIG/ammissibilita_rendiconti/deploy