#sqoop tables properties
hive.sgs.db=eng_test
hive.sgsPerimetroSwgSRawCPath=/user/eng_test/sgs/sqoop/sgs_perimetro_swg_s_raw_c
hive.sgsPerimetroSwgARawCPath=/user/eng_test/sgs/sqoop/sgs_perimetro_swg_a_raw_c
hive.sgsPerimetroUigSRawCPath=/user/eng_test/sgs/sqoop/sgs_perimetro_uig_s_raw_c
hive.sgsPerimetroUigARawCPath=/user/eng_test/sgs/sqoop/sgs_perimetro_uig_a_raw_c
hive.sgsPerimetroVtgSRawCPath=/user/eng_test/sgs/sqoop/sgs_perimetro_vtg_s_raw_c

connection.string.oracle = /user/eng_test/agg/oracle_collaudo.properties

deploy.path.hdfs = /user/eng_test/sgs/deploy
sgs.path.hdfs = /user/eng_test/sgs
deploy.path = /home/eng_test/sgs/deploy

xml.output.path = /mnt/settlementSYN_parallelo/TDG
sqoop.import.path = /user/eng_test/sgs/sqoop