package it.eng.au.portaleConsumi.schema.cmg_gas

import it.eng.au.portaleConsumi.schema.SchemaEnum

object PrtCmgTavPSchema extends SchemaEnum {
  val
  n_id_file,
  t_name_file,
  annomese_riferimento,
  cod_servizio,
  cod_flusso,
  d_caricamento,
  cod_pdr,
  matr_mis,
  matr_conv,
  data_com_autolet_cf,
  let_tot_prel,
  let_tot_conv,
  esito_val,
  note,
  anno,
  mese,
  piva_distr,
  piva_utente,
  local_file,
  mese_comp,
  data_prest,
  codprat_sii,
  trattamento,
  n_cifre_mis,
  n_cifre_conv,
  coeff_corr,
  freq_let,
  acc_mis,
  raccolta,
  esito_raccolta,
  causa_manc_raccolta,
  mod_alt_racc,
  dir_indennizzo,
  pros_fin_inizio,
  pros_fin_fine,
  vol_annuo_sost,
  classe_gruppo_mis,
  pre_conv,
  gruppo_mis_int,
  tipo_lettura,
  num_tentativi,
  data_racc,
  data_mis_eff,
  segn_mis_eff,
  segn_conv_eff,
  ammissibilita,
  annomese
  = Value
}
