package it.eng.au.portale_consumi_ee.model.swtch

case class SwtchPrtSePModel(
                             n_id_se: String = null,
                             n_id_pratica: String = null,
                             t_stato: String = null,
                             t_prot_rich: String = null,
                             t_codice_pod: String = null,
                             t_cli_rcu_cf: String = null,
                             t_cli_rcu_piva: String = null,
                             b_cli_cf_straniero: String = null,
                             b_cli_piva_estera: String = null,
                             d_data_contratto: String = null,
                             d_data_decorrenza: String = null,
                             b_revoca_timoe: String = null,
                             b_acquisto_credito: String = null,
                             t_cod_contr_disp: String = null,
                             t_contr_connessione: String = null,
                             b_ammissibile: String = null,
                             t_cod_causale: String = null,
                             t_motivazione: String = null,
                             n_id_rich: String = null,
                             t_ruolo_rich: String = null,
                             n_id_distr: String = null,
                             n_id_udd_u: String = null,
                             n_id_cc_u: String = null,
                             n_id_cc_e: String = null,
                             t_prot_distr: String = null,
                             b_dati_timoe: String = null,
                             t_cod_esito: String = null,
                             t_dett_esito: String = null,
                             d_data_flusso: String = null,
                             d_data_stato: String = null,
                             b_invalidata: String = null,
                             n_id_cliente_rcu: String = null,
                             n_id_riferimento_evento: String = null,
                             n_id_tipo_evento: String = null,
                             b_inframese: String = null
                           )
