#!/usr/bin/env bash

DEPLOY_PATH=${deploy.path}
STANDARD_FLOWS=(
    "TALStandard"
    "TMLStandard"
    "RMLStandard"
    "TGLStandard"
    "RGLStandard"
    "RSLStandard"
    "TAVStandard"
    "TASStandard"
    "RMVStandard"
    "TMVStandard"
    "FUIStandard"
    "A01Standard"
    "A40Standard"
    "D01Standard"
    "SM1Standard"
    "R01Standard"
    "A02Standard"
    "V01Standard"
    "SM2Standard"
    "M01Standard"
    "V02Standard"
    "AD2Standard"
    "AD2RStandard"
    "AD3Standard"
    "AD3RStandard"
    "AD4Standard"
    "AD4RStandard"
    "AD5Standard"
    "AD5RStandard"
    "S02Standard"
    "S40Standard"
    "R40Standard"
    "SWG1Standard"
    "FDDStandard"
    "D02Standard"
    "D01RStandard"
    "D02RStandard"
    "R01RStandard"
    "A40RStandard"
    "S40RStandard"
    "R40RStandard"
    "A01RStandard"
    "A02RStandard"
    "S02RStandard"
    "V01RStandard"
    "M01RStandard"
    "V02RStandard"
    "SM1RStandard"
    "SM2RStandard"
)

for flow in "${STANDARD_FLOWS[@]}"; do
    echo "Running $flow flow..."
    "$DEPLOY_PATH"/spark-submit-gas-ingestion.sh -f "$flow"
done
