output.path.log=/home/eng_test/partition_optimization/deploy/log
path.properties=/user/eng_test/partition_optimization
root.path.files=/home/eng_test/partition_optimization/deploy
is.local=cat
system.user=eng_test
