cig.aggregatoTotale.tableName=${cig.db}.${cig.aggregatoTotale.tableName}
cig.dettaglioPdr.tableName=${cig.db}.${cig.dettaglioPdr.tableName}

publication.type=CIG

isilon.basepath.tmp=${isilon.basepath.tmp}
isilon.basepath.out=${isilon.basepath.out}

cig.pubblicazioneIndennizzi.basepath=${cig.pubblicazioneIndennizzi.basepath}
cig.pubblicazioneIndennizzi.tableName=${cig.db}.${cig.pubblicazioneIndennizzi.tableName}

maxNumRowFile=25000
maxSizeThresholdZip=25000000

output.file.couples=IZG->CIG1,IZG->CIG2,DETTAGLIO->CIG1,DETTAGLIO->CIG2