include "ammissibilita.conf"

hive{
  table {
    misure {
        autoletture=${hive.table.misure.autoletture}
        misure_mensili_c=${hive.table.misure.misure_mensili_c}
        misure_non_orarie_c=${hive.table.misure.misure_non_orarie_c}
        misure_orarie_c=${hive.table.misure.misure_orarie_c}
        volture=${hive.table.misure.volture}
        etl_stage3m_2=${hive.table.misure.etl_stage3m_2}
        etl_stage33m_2=${hive.table.misure.etl_stage33m_2}
        registro_load=${hive.table.misure.registro_load}
        misure_storic=${hive.table.misure.misure_storic}
        misure_storic_nora=${hive.table.misure.misure_storic_nora}
        misure_storic_f=${hive.table.misure.misure_storic_f}
        misure_storic_f2=${hive.table.misure.misure_storic_f2}
        misure_storic_f2_erc_eri=${hive.table.misure.misure_storic_f2_erc_eri}
        consultazione=${hive.table.misure.consultazione}
        misure_storic_nora_erc_eri=${hive.table.misure.misure_storic_nora_erc_eri}
    }
    mongodbs
    {
        forniture_elettriche_tmp=${hive.table.mongodbs.forniture_elettriche_tmp}
        forniture_elettriche=${hive.table.mongodbs.forniture_elettriche}
    }
  }
}
ambiente
{
lavoro=${ambiente.lavoro}
}

