# Used for automation
monthDifference.timeBack=2

tsg.TabProfiliGiornStdPerc.basepath=${tsg.TabProfiliGiornStdPerc.basepath}
tsg.TabProfiliGiornStdPerc.tableName=${tsg.db}.${tsg.TabProfiliGiornStdPerc.tableName}

tsg.TabParametriCaratteristiciProfPrel.basepath=${tsg.TabParametriCaratteristiciProfPrel.basepath}
tsg.TabParametriCaratteristiciProfPrel.tableName=${tsg.db}.${tsg.TabParametriCaratteristiciProfPrel.tableName}

tsg.TSGTFC.tableName=${tsg.db}.${tsg.TSGTFC.tableName}
tsg.TSGVPG.tableName=${tsg.db}.${tsg.TSGVPG.tableName}

tsg.AtgTabProfiliGiornStdPerc.tableName=${atg.db}.${tsg.AtgTabProfiliGiornStdPerc.tableName}
tsg.AtgTabProfiliGiornStdPerc.basepath=${tsg.AtgTabProfiliGiornStdPerc.basepath}

tsg.AtgTabProfiliGiornStdPercBkp.tableName=${tsg.db}.${tsg.AtgTabProfiliGiornStdPercBkp.tableName}
tsg.AtgTabProfiliGiornStdPercBkp.basepath=${tsg.AtgTabProfiliGiornStdPercBkp.basepath}
rcugas.remiStato.tableName=${rcugas.db}.${rcugas.remiStato.tableName}
rcugas.remi.tableName=${rcugas.db}.${rcugas.remi.tableName}