package it.eng.au.portaleConsumi.model.hive.switch_gas

import java.sql.Timestamp

case class PrtSwgPModel(
                         n_id_swg: String = null,
                         n_id_pratica: String = null,
                         t_codice_pdr: String = null,
                         t_stato: String = null,
                         n_id_rich: String = null,
                         n_id_distr: String = null,
                         n_id_cc_entrante: String = null,
                         n_id_cc_uscente: String = null,
                         n_id_udd_uscente: String = null,
                         t_titolo: String = null,
                         d_data_richiesta: Timestamp = null,
                         t_cp_utente: String = null,
                         t_cp_distributore: String = null,
                         t_cf_cliente_finale: String = null,
                         t_piva_cliente_finale: String = null,
                         b_cf_straniero: String = null,
                         b_persona_fisica: String = null,
                         d_data_contratto: Timestamp = null,
                         d_data_decorrenza: Timestamp = null,
                         b_ammissibile: String = null,
                         t_cod_causale: String = null,
                         t_motivazione: String = null,
                         t_esito: String = null,
                         t_cod_esito: String = null,
                         t_dett_esito: String = null,
                         d_data_stato: Timestamp = null,
                         d_data_inserimento: Timestamp = null,
                         t_tipo_fornitura: String = null,
                         t_piva_cc: String = null,
                         t_revoca: String = null,
                         t_timg_pdr_chiuso_mor: String = null,
                         t_timg_date_sosp: String = null,
                         t_timg_date_sost: String = null,
                         t_timg_acc_mis: String = null,
                         t_timg_presenza_cmor: String = null,
                         d_tivg_data_att_fdd: Timestamp = null,
                         d_tivg_data_chiusura_pdr: Timestamp = null,
                         b_timg_tivg_calcolato: String = null,
                         b_ann_in_ritardo: String = null
                       )
