agg.db=agg
agg.rootpath=/user/hive/warehouse/au.db/misure_gas_au
dailyConsumption.tableName=daily_consumption_agg
dailyConsumptionIncoerenti.tableName=daily_consumption_agg_incoerenti
dailyConsumptionEsclusi.tableName=daily_consumption_agg_esclusi

dataset.numberPartitions=10

deploy.path=/home/gsv/deploy
deploy.path.hdfs=/apps/GSV/deploy

hive.gsv=gsv
hive.sqoop.location=/user/hive/warehouse/gsv.db
hive.gsvrichiestalocation=/user/hive/warehouse/gsv.db/gsv5_cons_richiesta
hive.gsvforniturelocation=/user/hive/warehouse/gsv.db/gsv5_cons_forniture
hive.gsvaggregatolocation=/user/hive/warehouse/gsv.db/gsv5_cons_aggr

connection.string.oracle = /apps/deploy/job.properties

ISILON_DEPLOY_PATH = /home/gsv/deploy/sqoop
