deploy.path.local = /home/eng_test/portale_consumi/dev/gas/job
deploy.path.logs = /home/eng_test/portale_consumi/dev/gas/logs
deploy.path.hdfs = /user/eng_test/portale_consumi/dev/gas

# User per lancio script hive
system.user = eng_test

params.job.days_interval_max = 1126
params.job.months_interval_max = 36
params.job.months_interval_split = 3
params.mongodb.max_doc_delta_forniture = 2000000
params.mongodb.max_doc_delta_misure = 2000000

#FORNITURE
hive.table.rcugas_clientefinale_p = rcugas.rcugas_clientefinale_p
hive.table.rcugas_connessioni_distr_p = rcugas.rcugas_connessioni_distr_p
hive.table.rcugas_fornitura_p = rcugas.rcugas_fornitura_p
hive.table.rcugas_indirizzi_p = rcugas.rcugas_indirizzi_p
hive.table.rcugas_pdr_datiprelievo_p = rcugas.rcugas_pdr_datiprelievo_p
hive.table.rcugas_pdr_misuratore_p = rcugas.rcugas_pdr_misuratore_p
hive.table.rcugas_pdr_p = rcugas.rcugas_pdr_p
hive.table.rcugas_residenza_p = rcugas.rcugas_residenza_p
hive.table.rcugas_venditore_p = rcugas.rcugas_venditore_p
hive.table.v_rcugas_distributore_p = rcugas.v_rcugas_distributore_p
hive.table.v_rcu_azienda_p = rcu.v_rcu_azienda_p
hive.table.switch_gas_prt_swg_p = switch_gas.prt_swg_p
hive.table.tdg_vuln_p = tdg.tdg_vuln_p
hive.table.rcugas_codice_offerta_p = rcugas.rcugas_codice_offerta_p
#MISURE
hive.table.cmg_gas_prt_cmg_rgl_p = cmg_gas.prt_cmg_rgl_p
hive.table.cmg_gas_prt_cmg_rml_p = cmg_gas.prt_cmg_rml_p
hive.table.cmg_gas_prt_cmg_rmv_p = cmg_gas.prt_cmg_rmv_p
hive.table.cmg_gas_prt_cmg_tal_p = cmg_gas.prt_cmg_tal_p
hive.table.cmg_gas_prt_cmg_tav_p = cmg_gas.prt_cmg_tav_p
hive.table.cmg_gas_prt_cmg_tgl_p = cmg_gas.prt_cmg_tgl_p
hive.table.cmg_gas_prt_cmg_tml_p = cmg_gas.prt_cmg_tml_p
hive.table.switch_gas_prt_vtg6_p = switch_gas.prt_vtg6_p

hive.table.forniture_processi_gas = eng_test.forniture_processi_gas
hive.table.forniture_misure_gas = eng_test.forniture_misure_gas
hive.table.misure_storic_f2 = eng_test.misure_storic_f2
hive.table.misure_data_calcolo = eng_test.misure_data_calcolo

#mongodb.db.uri = mongodb://test:test_au@172.16.16.162:27017/?connectTimeoutMS=10000&authSource=Test
#mongodb.client.uri = mongodb://test:test_au@172.16.16.162:27017
mongodb.db.uri = mongodb://test:test@172.16.16.166:27017,172.16.16.165:27017,172.16.16.164:27017/?connectTimeoutMS=10000&authSource=Forniture
mongodb.client.uri = mongodb://test:test@172.16.16.166:27017,172.16.16.165:27017,172.16.16.164:27017
mongodb.db.name = Forniture
mongodb.collection.fornitureGas = FornitureGas
mongodb.collection.misureGas33m = MisureGas33M
mongodb.collection.misureGas3m = MisureGas3M
mongodb.conf.readPreference = secondaryPreferred
mongodb.conf.writeConcern = majority
