<?xml version="1.0"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:include schemaLocation="../def_dati_tecnici.xsd"/>
	<xs:include schemaLocation="../def_cliente.xsd"/>
	<xs:include schemaLocation="../def_identificativi.xsd"/>
	<xs:include schemaLocation="../def_documentazione.xsd"/>
		
	<xs:element name="Prestazione">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="IdentificativiRichiesta" type="IdentificativiRichiestaCodDistrAcc" maxOccurs="1" minOccurs="1"/>
				<xs:element name="Esito" type="EsitoAccertamento" maxOccurs="1" minOccurs="1" />
				<xs:element name="DatiTecnici" type="PdrBase"></xs:element>
			</xs:sequence>
			<xs:attribute name="cod_servizio" type="xs:string" use="required" fixed="A40"/>
			<xs:attribute name="cod_flusso" type="xs:string"	use="required" fixed="0152"/>
		</xs:complexType>
	</xs:element>
</xs:schema>