output.path.log=/home/sii_misure_gas/partition_optimization/log
path.properties=/apps/partition_optimization/deploy
root.path.files=/mnt/isilonshare1/Software_1/partition_optimization/deploy
is.local=hdfs dfs -cat
system.user=sii_misure_gas