#AGG TABLES
dailyConsumption.table=${agg.db}.daily_consumption_agg
dailyConsumption.basepath=${agg.rootpath}/daily_consumption_agg
dailyConsumptionExcl.table = ${agg.db}.daily_consumption_agg_esclusi
dailyConsumptionExcl.basepath = ${agg.rootpath}/daily_consumption_agg_esclusi
dailyConsumptionIncGdM.table = ${agg.db}.daily_consumption_agg_incoerenti
dailyConsumptionIncGdM.basepath = ${agg.rootpath}/daily_consumption_agg_incoerenti

#GSV TABLES
gsvConsForniture.table = ${hive.gsv}.gsv5_cons_forniture
gsvConsForniture.basepath = ${hive.sqoop.location}/gsv5_cons_forniture
gsvConsRichiesta.table = ${hive.gsv}.gsv5_cons_richiesta
gsvConsRichiesta.basepath = ${hive.sqoop.location}/gsv5_cons_richiesta
gsvConsAggregato.table = ${hive.gsv}.gsv5_cons_aggr
gsvConsAggregato.basepath = ${hive.sqoop.location}/gsv5_cons_aggr

#NUMERO CONFIGURABILE DI PARTIZIONI IN SCRITTURA SULLA TABELLA HIVE
dataset.numberPartition=${dataset.numberPartitions}