hdfs.output.basepath.csv=/user/hive/warehouse/eng_test.db/CDP/cdp_dati_prelievo_gas
hdfs.output.basepath.csv.export=/user/hive/warehouse/eng_test.db/CDP/cdp_dati_prelievo_gas_export
hdfs.output.basepath.infoLog=/user/hive/warehouse/eng_test.db/aggregatore_info_log_cdp

cdp.db = eng_test
rcugas.db = eng_test
rcugasMassivo.db = eng_test
rcu.db = eng_test
hive.db = eng_test
isilon.basepath.tmp=/mnt/isilonshare1_Parallelo
isilon.basepath.out=/mnt/settlementSYN_parallelo

sqoop.config.path=/user/eng_test/cdp/deploy_aggregazione/sqoop.properties
params.config.path=/user/eng_test/cdp/deploy_aggregazione/params.properties
hadoop_username=eng_test
sqoop.null.character=\\\\N

spark.app.url=jdbc:oracle:thin:@(DESCRIPTION =(ADDRESS = (PROTOCOL = TCP)(HOST = 172.16.23.100)(PORT = 1521))(CONNECT_DATA = (SERVER = DEDICATED) (SERVICE_NAME = SIIPRE)))

isilon.deploy.path=/home/eng_test/cdp/aggregatore
hdfs.deploy.path=/user/eng_test/cdp/deploy_aggregazione