
timeZone=Europe/Rome

hive {
  db = ${hive.db}
  table {
    funzionali = dati_funzionali
    storici = dati_storici
    report = report_file
  }
}

xml {
  maxNPods {
    funzionali = ${xml.maxNPods.funzionali}
    storici = ${xml.maxNPods.storici}
  }
  tmpRootPath = ${output.path}/tmp
  xsdPath {
    funzionali = ${xml.xsd.path}/FlussiDatiMisuraPrelievoEE-FlussoF.xsd
    storici = ${xml.xsd.path}/FlussiDatiMisuraPrelievoEE-FlussoS.xsd
  }
}

zip {
  outputRootPath = ${output.path}/output
}