DROP TABLE IF EXISTS ${hive.table.misure.etl_stage3m_2};
CREATE TABLE ${hive.table.misure.etl_stage3m_2} (
    n_id_fornitura STRING,
    misure_orarie ARRAY<STRUCT<
        giorno: STRING,
        competenza_consumi: STRING,
        consumo_giornaliero_gg: STRING,
        lettura_misura_f1: STRING,
        lettura_misura_f2: STRING,
        lettura_misura_f3: STRING,
        lettura_misura_f4: STRING,
        lettura_misura_f5: STRING,
        lettura_misura_f6: STRING,
        delta_misure_f1: STRING,
        delta_misure_f2: STRING,
        delta_misure_f3: STRING,
        delta_misure_f4: STRING,
        delta_misure_f5: STRING,
        delta_misure_f6: STRING,
        potenza_max_erogata: STRING,
        tipo_misura: STRING,
        data_lettura: STRING
    >>,
    misure_mensili STRUCT<
        competenza_consumi: STRING,
        delta_misure_monoraria: STRING,
        lettura_misura_monoraria: STRING,
        lettura_misura_f1: STRING,
        lettura_misura_f2: STRING,
        lettura_misura_f3: STRING,
        lettura_misura_f4: STRING,
        lettura_misura_f5: STRING,
        lettura_misura_f6: STRING,
        delta_misure_f1: STRING,
        delta_misure_f2: STRING,
        delta_misure_f3: STRING,
        delta_misure_f4: STRING,
        delta_misure_f5: STRING,
        delta_misure_f6: STRING,
        tipo_misura: STRING,
        data_lettura: STRING,
        potf1: STRING,
        potf2: STRING,
        potf3:STRING,
        potm:STRING
    >,
    misure_non_orarie STRUCT<
        competenza_consumi: STRING,
        lettura_misura_monoraria: STRING,
        lettura_misura_f1: STRING,
        lettura_misura_f2: STRING,
        lettura_misura_f3: STRING,
        lettura_misura_f4: STRING,
        lettura_misura_f5: STRING,
        lettura_misura_f6: STRING,
        delta_misure_monoraria: STRING,
        delta_misure_f1: STRING,
        delta_misure_f2: STRING,
        delta_misure_f3: STRING,
        delta_misure_f4: STRING,
        delta_misure_f5: STRING,
        delta_misure_f6: STRING,
        tipo_misura: STRING,
        data_lettura: STRING,
        potf1: STRING,
        potf2: STRING,
        potf3: STRING,
        potm: STRING
    >,
    volture STRUCT<
        competenza_consumi: STRING,
        data_lettura: STRING,
        lettura_misura_monoraria: STRING,
        lettura_misura_f1: STRING,
        lettura_misura_f3: STRING,
        lettura_misura_f4: STRING,
        lettura_misura_f5: STRING,
        lettura_misura_f6: STRING,
        tipo_misura: STRING
    >,
    autoletture STRUCT<
        competenza_consumi: STRING,
        data_lettura: STRING,
        lettura_misura_monoraria: STRING,
        lettura_misura_f1: STRING,
        lettura_misura_f2: STRING,
        lettura_misura_f3: STRING,
        lettura_misura_f4: STRING,
        lettura_misura_f5: STRING,
        lettura_misura_f6: STRING
    >,
    pod STRING,
    cod_pod STRING,
    hash_value STRING,
    last_update BIGINT
)
PARTITIONED BY (competenza_consumi INT)
STORED AS PARQUET;

