deploy.path.erp=/home/eng_test/ERP/dev/deploy
hive.table.au.flusso_misure_interconnessione=eng_test.flusso_misure_interconnessione
hive.table.rcu.rcu_pod_p=rcu.rcu_pod_p
hive.table.au.aggregazioni_misure_quartorarie=eng_test.aggregazioni_misure_quartorarie
hive.table.au.v_aggregazioni_misure_quartorarie=eng_test.v_aggregazioni_misure_quartorarie
hive.table.au.v_aggregazione_misure_ip=eng_test.v_aggregazione_misure_ip
hive.table.au.pod_connessione=eng_test.pod_connessione
hive.table.rcu.rcu_azienda_p=rcu.rcu_azienda_p
hive.table.rcu.rcu_pod_distr_p=rcu.rcu_pod_distr_p
hive.table.rcus.rcus_pod_distr=rcus.rcus_pod_distr_p
hive.table.erp.erp_aggregato_o=eng_test.erp_aggregato_o
hive.table.erp.erp_aggregato_ip_o=eng_test.erp_aggregato_ip
hive.table.erp.erp_validated_int=eng_test.erp_validated_int
hive.table.erp.erp_dettaglio_int=eng_test.erp_dettaglio_int
hive.table.erp.erp_aggregato_int=eng_test.erp_aggregato_int
hive.table.au.flusso_misure_smis=eng_test.flusso_misure_smis
hive.table.au.flusso_misure_noaggr=eng_test.flusso_misure_noaggr
hive.table.au.flussi_tecnici=eng_test.flussi_tecnici
hive.table.rcu.rcu_pod_interconnessione_p=rcu.rcu_pod_interconnessioni_p
hive.table.erp.erp_validated_mis_no=eng_test.erp_validated_mis_no
hive.table.erp.erp_consumption_no=eng_test.erp_consumption_no
hive.table.erp.erp_daily_dima=eng_test.erp_daily_dima
hive.table.erp.erp_daily_no=eng_test.erp_daily_no
hive.table.erp.erp_aggregato_no=eng_test.erp_aggregato_no
hive.table.erp.erp_aggregato=eng_test.erp_aggregato
hive.table.tratt_pod.tratt_pod_all_annomese_partitioned=tratt_pod.tratt_pod_all_annomese_partitioned

#set up spark lunch properties

spark.num.executors=32
spark.executor.cores=4
spark.executor.memory=60g
spark.driver.cores=4
spark.driver.memory=40g

spark.executor.memoryOverhead=4g
spark.dynamicAllocation.enabled=true
spark.dynamicAllocation.minExecutors=10
spark.dynamicAllocation.maxExecutors=48
spark.dynamicAllocation.initialExecutors=32

#set parameters input
spark.app.energia_residuale_pariziale.paramentro.area=
spark.app.energia_residuale_pariziale.paramentro.annomese=
spark.app.energia_residuale_pariziale.ore=
ale.paramentro.singola_piva_distributore=
spark.app.energia_residuale_pariziale.paramentro.dati_output_path=
spark.app.energia_residuale_pariziale.paramentro.dati_output_mount=
spark.app.energia_residuale_pariziale.paramentro.piva_esclusa=05779661007
