settleGas.gasTds.parquetPath=${rootpath}/gas_tds_part
rcugas.rcugasMassivo.tableName=${rcugasMassivo.db}.${rcugasMassivo.tableName}
prt.istatRegClima.tableName=${prt.db}.${istatRegClima.tableName}
rcugas.connessioniDistr2.tableName=${rcugas.db}.${connessioniDistr2.tableName}
rcugas.bilanciamento.tableName=${rcugas.db}.${bilanciamento.tableName}
prtRcugas.prtVsg.tableName=${prtRcugas.db}.${prtVsg.tableName}
switchRcugas.prtVtg.tableName=${switchRcugas.db}.${prtVtg.tableName}
switchRcugas.prtVtgAggRcu.tableName=${switchRcugas.db}.${prtVtgAggRcu.tableName}
prtRcugas.prtVsgAggRcu.tableName=${prtRcugas.db}.${prtVsgAggRcu.tableName}

hdfs.output.cod_prof_std_da_tds=${output.rootpath}/cod_prof_std_da_tds

exclusion.pdr.filter.isActive=false
exclusion.pdr.filter.csv.path=${exclusion.pdr.filter.csv.path}

filterPdr.forzatura.isActive=false
filterPdr.forzatura.path=${filterPdr.forzatura.path}

start.data.ricezione=2021/08/12
end.data.ricezione=2021/10/08

freeze.date=2021-10-08
anno.competenza=2022

rcugas.massivo.executionid=1635239472110

cod_prof_std_da_tds.tableName=${output.db}.cod_prof_std_da_tds